#+title: Note

记录一下 cs225 ( 基于 cpp 的数据结构 ) 的学习

中间会夹杂很多其他学到或者用到的东西, 不一定跟 cs225 有关, 比如说在 cs225 过程中用到的 cli 工具, shell, vim 这些奇怪的东西

我认为这个课程是一个很好的熟悉 linux 还有对应开发环境, 开发工具, 底层概念的机会, 所以会记录很多这些东西

对一些 lecture 的内容记录可能不多, 有些内容不知道怎么命名就瞎起名字了

其实似乎应该叫做 linux 下面的开发体验记录以及 cs225 课程笔记, 而不只是 cs225 课程笔记

这个 note 并不全面, 甚至可能不成文, 他的作用主要是让我 keep focused, 不会事无巨细的记录每一个知识点, 有一些我会了的东西不会记录, 有一些不会的但是我觉得太难了, 不足以清晰的使用文字说明清楚的我也不会记录 ( prefer 纸质, 可能会上传 pdf )

* lecture 01

Encapsulation 封装, 是指分开 interface 和 implementation

namespace 解决复杂工程里面同名函数问题, 可 using namespace, 但是建议不要, 要习惯 namespace::xxxxx 这种 style, 比如 std::cout

constructor, default constructor ( 如果没写 constructor 会默认生成一个 automatic default constructor, 这个 constructor 会给该 class 里面所有东西赋默认值, 比如 float/double 给0.0, int 給0, pointer 给 NULL ), 自定义的 constructor, constructor 可以有很多个

指针 re-cap

header file 记得 #ifndef XXXX_H 来避免重复 include

convention 里面, xxx.h 放 declaration, xxx.c/xxx.cpp 里面放 definition / implementation


* 一些有用的知识

ECE220 / ECE120 / STM32 legacy

** 编译
*** 1. preprocess
主要是把 #include xxx.h 这种东西替换为 xxx.h source file 里面的文本, 对 macro 进行文字替换
比如说 #include "xxx.h" 在 preprocess 阶段做的就是把 xxx.h 文件的文本复制过来, 替换 #include "xxx.h" 这一行
我们上面写 guard, 即 #ifndef XXXX_H 的原因就是, 你可能在一个 source file 里面 include 了同一个文件多次, 这样你重复 declare 了一个东西多次, 可能会报错, 你加这个东西, 就会先判断, 然后如果没 include 过再 include, 保证一个文件只被 include 一次

*** 2. compile
编译器把 xxx.c 文件独立编译成对应的机器码 .o 文件, 每个 .c 文件独立编译, 未实现但是有声明是可以的, 只要语法正确即可
这个意思是说, 假如你在 xxx.h 里面写了某个函数的 declaration, 然后在 yyy.c 里 #include "xxx.h", 然后你在 xxx.c 里面实现了 xxx.h 里面 declare 的函数, 你在编译 yyy.o 的时候, yyy.c 里面并没有这个 xxx.h 里声明的函数的实现, 即使你不写 xxx.c 这个编译也是成功的

在 vim 里面查看二进制文件 ( elf 格式: :%!xxd, %表示全局, !表示外部命令, xxd 是一个解析二进制码的工具 ), 是时候对 vim 再进一步了

编译常见 option
a. -std=gnu99: 使用什么规范什么标准
b. -c: compile only, 不 link
c. -g: enable gdb debug, debug 选项
d. -O0: 优化与否, -O0 表示不优化便于 debug, 数字越大表示优化的越厉害
e. 关于容错和警告: -Wall 是 warning all 的意思, 警告大部分错误 ( 尽管声称是 warning all ), -Wextra 额外警告, 比 -Wall 更多, -pedantic 严格遵循标准 ( 学究 )

*** 3. link
把各个 .o 文件链接起来, 生成 executable image, 这个时候会有什么重复定义, 声明了没找到这些问题
比较 tricky 的地方是, 即使你在 xxx.c 里面不 #include xxx.h ( xxx.c 里面实现了 xxx.h 里面声明的函数 ), 编译器还是可以正确 link 的, 只不过没人这么干

当然, 很多时候在写 gcc 指令的时候, 我们不分开 compile 和 link, 两个是一起的

常见指令: gcc ..... -o executable, -o 后面的名字是 executable image, 然后 ./executable 就可以执行命令了
g++ -std=c++1y  -lpng -lpthread -lm xxx.o o executable
-lpng 前面的 -l 表示 lib, 然后 png 是系统 lab 库, 一般在 /usr/lib/x86_64-linux-gnu 这个里面, 里面有 .so 这种动态库 ( ros 2 control 里面用的那个 ), 也有 .a 这种静态库, 我们可以使用 file 指令查看这个东西的性质, 比如:
(base) zhb:/usr/lib/x86_64-linux-gnu$ file libImath-3_1.so.29
libImath-3_1.so.29: symbolic link to libImath-3_1.so.29.8.0

*** make 和 Makefile
贴吧上看见一个很好的介绍 https://tieba.baidu.com/p/591519800
要会自己独立写基本的 Makefile, 要能看懂并且在已有的基础上修改复杂的 Makefile, 这玩意实际上可以调用 shell 指令还是很 powerful的,
还有用于更复杂的 cmake
东西太多了暂时就不记录了, 经常用经常写自然就会了, 开个坑专门记录这些工具吧, 放在这个文件的最后

** memory
以 stm32 的内存设计为例, lc 3 内存位置忘记了懒得去查, 但是 lc3 也是和 stm32 的内存设计差不多的, stm32 的内存还更真实一点

哦, 找到 lc3 memory setting 了: https://github.com/hanbinzheng/ece220/blob/main/LC3_BASICS/memory_layout

这个是一个 stm32 h723 link 使用的 .ld 脚本: https://github.com/hanbinzheng/infantry/blob/main/STM32H723XG_FLASH.ld

关于 stm32 h7 芯片物理上有哪些存储, 这些存储有哪些特点, 以及在 memory 里面这些存储是如何规划的
下面的东西在声明我有哪些地方是合法的, 内存的哪些地方是可以放东西的
FLASH / ROM 断电不丢失, RAM 断电丢失, SRAM: Static RAM, MCU 里面基本都是 SRAM, SRAM 的 static 的意思是只要通电数据就不会丢失

TCM: Tightly Coupled Memory, 它是直接挂在 CPU 内部总线上的存储空间, 专门为 cpu 服务绕过了普通外设总线(AHB/APB), cpu 访问/写极快, 他们也算 RAM, 断电也丢失

注意, FLASH / ROM 不是不能写, 我们可以通过烧录去写, 下面说的不能写 ( 不能 w ) 是指不能在程序运行的时候快速的写

下面是简化版的 .ld 文件, 用于展示内存布局的

#+begin_src conf
/* Entry Point */
ENTRY(Reset_Handler)

/* Highest address of the user mode stack */
_estack = ORIGIN(DTCMRAM) + LENGTH(DTCMRAM);    /* end of RAM */
/* Generate a link error if heap and stack don't fit into RAM */
_Min_Heap_Size = 0x200;      /* required amount of heap  */
_Min_Stack_Size = 0x400; /* required amount of stack */

/* specify memory sections */
MEMORY
{
DTCMRAM (xrw) : ORIGIN = 0x20000000, LENGTH = 128K  /* DTCM, CPU 专属访问读写极快, Dtat TCM, 主要放的是 CPU 高频访问的数据 */
RAM_D1  (xrw) : ORIGIN = 0x24000000, LENGTH = 320K  /* SRAM Region 1, rwx 都行, 可被 CPU/DMA/外设访问, 访问延迟大于 TCM  */
RAM_D2  (xrw) : ORIGIN = 0x30000000, LENGTH = 32K   /* SRAM Region 2, 同上 */
RAM_D3  (xrw) : ORIGIN = 0x38000000, LENGTH = 16K   /* SRAM Region 3, 同上 */
ITCMRAM (xrw) : ORIGIN = 0x00000000, LENGTH = 64K   /* ITCM, CPU 专属访问极快, Instruction TCM, 极端实时的代码指令 */
FLASH   (rx)  : ORIGIN = 0x08000000, LENGTH = 1024K /* FLASH, 只能 rx, 不能 w, 因此一般放不会修改的东西, 比如常量, 程序代码, 向量表 */
}

/* Define output sections */
SECTIONS
{
        /* The startup code goes first into FLASH */
        .isr_vector : { /* 中断向量表, 在 FLASH 开头 */ } >FLASH

        /* The program code and other data goes into FLASH */
        .text : { /* 所有程序, .text 和 .text* 的都放在这里 */ } >FLASH

        /* Constant data goes into FLASH */
        .rodata : { /* 常值, .rodata 和 .rotata*, ( constants, strings, etc. ) */ } >FLASH

        /* ARM 特定段, 没研究过, 但是这俩都是 READONLY 的, 也在 FLASH */
        .ARM.extab : { /* ARM异常处理表 */ } >FLASH
        .ARM : { /* ARM异常索引表 */ } >FLASH

        /* 给 cpp 的, 我的 stm32 里面是纯 c, 没有 cpp, 没研究过 */
        .init_array : { /* C++静态构造函数数组 */ } >FLASH
        .fini_array : { /* C++静态析构函数数组 */ } >FLASH

        /* C/CPP 初始化, 没研究过 */
        .preinit_array (READONLY) : { /* C++/C 运行时初始化机制的一部分，用于在 main 函数之前执行初始化代码 */ } >FLASH

        /* Initialized data sections goes into RAM, load LMA copy after code */
        /* 运行时在 DTCMRAM 中, 加载时在 FLASH 中, 启动时把 FLASH 中的初始值 memcpy 到 DTCMRAM 中的 .data 对应位置 */
        .data : { /* 有初始值的 "静态存储期对象", 如全局变量, static 全局, static 局部 * / } >DTCMRAM AT> FLASH

        /* Uninitialized data section */
        .bss : { /* 没有显式初始化的静态存储期对象, 不占 Flash 直接放 DTCMR, 如未初始化的全局/static 全局/static 局部 */ } >DTCMRAM

        /* buffer specified for dma1 and dma */
        .dma12_buffer (NOLOAD) : { /* DMA 没有办法访问 DTCM, 所以给开一个地方在 SRAM 上面 */ } >RAM_D2

        /* User_heap_stack section, used to check that there is enough RAM left */
        ._user_heap_stack : { /* user 使用的 heap 段, 用于 malloc */ } >DTCMRAM

}
#+end_src

你会发现这里没有 stack 的地方, 这个是因为 stack 不是预先规定的, stack 是 CPU 的 SP 寄存器 + RAM 空间
规定一下 convention, 一般称地址较大的为高地址, 地址较小的为低地址, 比如说 0x0010 和 0x1000, 0x1000 算高地址, 0x0010 算低地址
stack top: 当前 stack pointer 指向的位置, stack bottom: stack 被分配的那一端的边界
主流 CPU 上, stack 是从高地址向低地址生长, PUSH 代表 SP 减少, POP 代表 SP 变大,
_estack 代表 stack 的分配边界, 最高的那个地址, stack pointer 从 _estack 这个地址开始向低地址生长, 有一些恶心的 bug 比如说 stack 长到了 heap 里面
stack overflow: stack 踩到了 heap 和 .bss 段

STM32H723内存映射:
#+begin_src txt
0x0000 0000 ┌─────────────┐ 别名区 ( 自动映射到Flash或RAM )
            │             │
0x0800 0000 ├─────────────┤ Flash起始 ( 程序在这里 )
            │   .text     │ ← 代码段
            │  .rodata    │ ← 只读数据
            │ .data初始化值 │
0x0810 0000 ├─────────────┤
            │             │
0x2000 0000 ├─────────────┤ RAM起始
            │   .data     │ ← 已初始化变量 ( 从Flash复制过来 )
            │   .bss      │ ← 未初始化变量 ( 清零 )
            │    堆(heap) │ ← malloc 使用
            │             │
            │    _estack  │ ← stack base/bottom, RAM 结束, stack pointer 从这里开始向低地址生长
0x2008 0000 └─────────────┘
#+end_src

** variable 相关
关于变量存储位置, 作用域, 生命周期, 非常重要

1. 一般局部变量, 即函数内部使用的一般变量 (无static关键字), 作用域是该函数体内部, 储存位置在 run time stack 上面, 生命周期是函数被调用时创建/初始化, 到函数 return 时生命周期结束, 比如 void function(int a, int b) {} 里面的 c 这个局部变量
   这个在 ECE220 写 run time stack 的 lc3 汇编的时候已经学的很明白了
2. static 局部变量, 一般的局部变量加上一个 static 关键字, 比如. void function(int a, int b) { static int c = a + b; }, 这个变量的作用域也是该函数内部, 即只有该函数内部才能访问这个变量, 但是这个变量的生命周期是整个程序执行的时间, 主要放在 .data/.bss 段 ( 取决于有没有初始化 )
3. 全局变量, 如直接写在 .c 文件里 ( 不在任何一个函数内部 ), 作用域是全部程序 ( 注意, 如果 local variable 和 global variable 重名, 那在函数内使用的是 local 的 ), 即任何一个程序都可以访问 ( 使用这个全局变量的程序要有 extern 关键字声明这个变量存在 ), 否则无法直接使用, 这个东西的储存位置在 .bss 或者 .data 段 ( 取决于有没有初始化 ), 生命周期是整个程序的执行时间, 注意, 全局变量的名字不能重复
4. static 全局变量, 跟全局变量唯一的区别是作用域被限定为了这个 .c 文件, 只有这个文件里的函数可以使用

** c 指针数组类型判断

我们要从运算符的角度去理解 c 里面的类型判断, 根据变量的优先级判断

先说明白一下, a[i] 里面的 [] 运算符相当于 *(a + i), 他的优先级是高于 * 运算符的

1. int *p;
   对变量 p 进行 * 运算, 得到的是 (*p), 也就是说读取 p 这个地址里存的东西得到的是一个 int, 所以 p 是一个指向 int 的指针

2. int a[10];
   0 ～ 9 里面的任意一个数字 i, 对变量 a 进行 a[i] 运算, 得到的是一个int, 所以说 a 是一个长度为10的数组

3. int *a[10];
   运算优先级上 [] 高于 *, 因为 a[i] 是*(a + i), 这里有一个括号, *(*(a + i)) 得到的是一个 int, 所以说 a 首先是一个数组, 然后对 a 进行 (*(a + i)) 得到的是 int * 类型, 即指向 int 的指针, 然后再 *, 得到 int, 所以说 a 是一个存了10个int* 变量的数组

4. int (*p)[10];
   这里的时候我们先进行的是 * 这个运算, 对 (*p) 得到的结果在进行 [] 运算, 即(*p)[i] 得到的是 int, 所以说 (*p) 是一个数组的首地址, 或者说是一个数组, p就是一个指向数组的指针

   也就是说大概是这样的, int a[10];, 然后 int (*p) [i] = &a;

5. 往下叠 buff...
   上面差不多讲清楚了, 然后就可以根据运算的优先级, 爱咋叠 buff 咋叠 buff 了

** c关键字和 GCC 提示指令
1. extern
   用于声明全局变量的

   比如说在 xxx.c 里面写了 extern int a;, 声明这里有一个全局变量 a, 但是在别的地方不知道在哪里 ( 可能在别的文件, 也可能在这个文件的后面 ), 但是我 extern int a; 声明之后, xxx.c 后面的内容就可以使用 a 这个变量了

   我们有时候会这样 (这个实际上是使用全局变量的标准模式), 在 xxx.h 里面写 extern int a;, 然后在 xxx.c 里面写 int a = 0;, 当你在其他 .c 文件里 #include "xxx.h" 之后, 经过 preprocess, extern int a; 这个声明会出现在其他文件里, 让其他文件可以访问这个全局变量, 在 xxx.c 里, 你 #include "xxx,h", preprocess 的时候有了 extern int a; 这个声明, 然后你在后面写 int a = 0;, 给了变量 a 这个定义

2. static
   表示 local, 表示这个东西仅属于当前 函数/文件, 其他 函数/文件 用不了, 这个使得我们可以重名, 比如说在 xxx.h 里面写 static int add(int a, int b) {return a + b};, 然后不同 #include "xxx.h" 的 c 文件都有这个 add 函数的 local 版本, 不会出问题, 但是如果你没有写 static, 就会出现很多个 add 函数 ( 没有 static 的时候, 这个函数默认是 global 的 ), 这个时候编译器就会报错

   static 的 variable 在 .bss 或者 .data 段, static 的函数在 .text 段, 但是只有该函数/文件可以使用

3. inline
   用于内联, 内联是一种编译器优化，建议编译器把函数调用替换为函数体本身

   如果没有内联                                      内联之后
   int square(int x) { return x * x; }             inline square(int x) {return x * x;}
   int y = square(5);                              int y = square(5);

   // 编译后:
   // call square  ; 调用函数                        // mov y, (5 * 5)   ; 直接计算结果，不调用函数
   // mov result to y

   inline 的用法:
   (1) 头文件定义函数, 编译的时候就直接展开了, 不会出现我们在 2. 里面提到的有多个函数定义的问题
   (2) 性能优化, 因为直接展开了, 没有函数调用开销, 适合用来写小函数, 比 #define 这种 macro 安全, 而且性能几乎没有区别, 我习惯用 static inline 代替有逻辑的 macro

4. const

   const 表示是指编译器会阻止对该变量做语意上的修改, 如果你通过一些奇技淫巧用指针绕过的话, 还是可以改的

   const 修饰它左边最近的东西, 如果左边没, 就修饰它右边的, const int a; 和 int const a; 完全一样

   指针相关的 const, 这个很容易搞混

   指向 const 的指针
   #+begin_src c
    const int *p;   // 或 int const *p;

    int x = 5;
    int y = 6;
    p = &x;
    ,*p = 10;   // 编译错误，指向的数据不能改
    p = &y;    // 指针本身可以改
   #+end_src

   const 指针 ( 指针本身不可改 )
   #+begin_src c
    int * const p = &x;
    *p = 10; // 可以修改指向的值
    p = &y; // 指针本身不能修改
   #+end_src

   指向 const 数据的 const 指针 ( 双重 const )
   #+begin_src c
   const int * const p = &x;
   #+end_src

   在 cpp 里面, 这个也是类似的
   #+begin_src cpp
   PNG const & a = ...;
   #+end_src
   这里的 const 修饰的是 PNG, 然后从 a 开始往左读, 是 reference to const PNG, 不能改变这个 PNG 的值, 这个是用来传参的一个重要办法, 避免拷贝, 也避免改变传如的参数

   还有一个 const 的例子
   #+begin_src cpp
   bool operator==(PNG const& other) const;

   // 等价形式
   bool operator==(PNG const& other, PNG const* const this);
   // PNG const * const this, 左边的 const 修饰 PNG, 表示不改变 PNG, 右边的 const 修饰 (PNG const *), 表示不改变这个指针
   #+end_src

5. __attribute__

   这个不是 c 的关键字, 是给 GCC 的提示和指令, 是 GCC 的特性而不是 c 语言的特点

   __attribute__ 是 GCC 的编译器指令, 用于: 给编译器额外的优化提示/给编译器额外的优化提示/启用特定的语言扩展/提供调试信息

   因为我用的也不多, 我只在处理 DMA 无法 access DTCM 的时候手动放置 buffer 的时候用了一次, 所以这里多放了几个例子, 虽然我不觉得这些例子会用到, 但是别人用到的时候要看得懂

   基本语法
   #+begin_src c
    // 单个属性
    type name __attribute__((attribute_name));

    // 多个属性
    type name __attribute__((attr1, attr2, attr3));

    // 函数属性
    return_type func_name(args) __attribute__((attribute_name));
   #+end_src

   函数优化提示
   #+begin_src c
    // 1. 内联控制
    void __attribute__((always_inline)) fast_func() { ... }
    void __attribute__((noinline)) big_func() { ... }

    // 2. 热/冷函数提示
    void __attribute__((hot)) critical_path() { ... }   // 经常执行
    void __attribute__((cold)) error_handler() { ... }  // 很少执行

    // 3. 纯函数/常量函数
    int __attribute__((pure)) calculate(int a, int b) {
         // 纯函数：只依赖参数，无副作用
         return a + b;
    }
    double __attribute__((const)) pi() {
         // 常量函数：相同输入永远相同输出，且不读全局变量
         return 3.1415926;
    }

    // 4. 不返回函数
    void __attribute__((noreturn)) panic() {
         while(1);  // 永不返回
    }
   #+end_src

   内存布局控制
   #+begin_src c
    // 1. 指定段
    uint8_t buffer[1024] __attribute__((section(".dma_buffer")));
    const char str[] __attribute__((section(".rodata.custom")));

    // 2. 对齐控制
    uint32_t data __attribute__((aligned(32)));  // 32字节对齐
    struct S __attribute__((aligned(64))) { ... };  // 结构体对齐

    // 3. 打包结构体（取消填充）
    struct __attribute__((packed)) Packet {
         uint8_t cmd;
         uint32_t data;  // 通常会有3字节填充，packed取消填充
    };

    // 4. 弱符号（允许覆盖）
    int __attribute__((weak)) default_value = 0;
    void __attribute__((weak)) default_handler() { ... }
   #+end_src

** cpp 入门特性

这里主要讲一下 ECE 220 用到的 cpp 入门的一些特性

*** 初始成员列表

在创立并初始化一个对象的时候, 一般流程是:
1. 分配内存 ( 为整个 object )
2. 初始化 base class 部分 ( 如果有 inheritance )
3. 按照声明顺序初始化所有数据成员 ( 始化的顺序是成员的声明顺序, 如果有初始成员列表, 使用初始成员列表的值进行初始化, 没有则默认  )
4. 执行构造函数体 ( 注意, 是构造函数题, 不是构造函数 )

初始成员列表性能上比赋值的办法快, 而且对于一些 const 的变量, 只能使用初始成员列表来做, 还有 reference 也只能用初始成员列表的办法初始化 ( reference 是 "语意上的一个 object ", 只有在初始化的时候表示 "指向哪个对象/内存地址", 后面的 = 都是改变那片内存地址上的对象的值 )

#+begin_src cpp
class MyClass {
private:
    std::string name;     // class object
    int id;               // 基本的类型
    const int version;    // const
    std::vector<int>& ref_vec;  // reference

public:
    // 在构造函数体内赋值
    MyClass(std::string n, int i, int v, std::vector<int>& vec) {
        name = n;          // name已经调用了 name 的默认构造函数, 即已经初始化了, 这里实际是 operator= 赋值
        id = i;            // 基本类型重新赋值, 影响比较小
        // version = v;    // const 的变量已经被初始化了, 这里是赋值, 但是 const 不能赋值
        // ref_vec = vec;  // reference 可以理解成 const 指针, 或者根本的, 就没有 "reference" 这种类型, reference 就是对象本身, 哪个对象是初始化的时候就确定了
    }

    // 使用初始成员列表
    MyClass(std::string n, int i, int v, std::vector<int>& vec)
        : name(n),         // 直接调用拷贝构造函数
          id(i),           // 基本类型直接初始化
          version(v),      // const attribute 初始化, 必须初始成员列表
          ref_vec(vec) {   // reference attribute 必须有初始化
        // ........
    }
};
#+end_src

#+RESULTS:

在底层, 赋值初始化会让整个再多一次赋值的操作, 效率会低

*** reference

reference 就是指向的那个 object, 只是语意上换了一个东西表示, 这让你可以操作底层的东西而无需使用指针, 你可以把它在底层理解成一个 const pointer ( int * const, 而不是 int const *, 换句话说, 指向哪里不能再变了, 但是指向的地址存的值是可以改变的 ), 但是实际上并没有那么一个变量, 编译器在看到 reference 变量的时候就只会把它当作 "该对象本身", 想象中等同于一个 * pointer 的感觉, 但是要记住实际上没有那么一个临时pointer变量


#+begin_src cpp
int main() {
	int a = 0;
	int & b = a;

	std::cout << "&a: " << &a << std::endl;
	std::cout << "&b: " << &b << std::endl;

	b = 100;
	std::cout << "a = " << a << std::endl;
	std::cout << "b = " << b << std::endl;

	return 0;
}
#+end_src

结果是:
#+begin_src bash
zhb ~/Desktop % ./a.out
&a: 0x16bcfed88
&b: 0x16bcfed88
a = 100
b = 100
#+end_src

这就是为什么我们要在初始化成员列表里面初始化 reference 了, 因为初始化的时候流程是:
1. 分配空间
2. 如果有 inheritance, 那么初始化 base class 的
3. 对于本 class 的每一个 attribute 进行默认初始化 ( reference 这里被初始化了, 但是默认初始化的时候没有指定对象是什么, 所以这个 reference 是没法用的 ), 你可以通过初始列表去干预这里, 比如说委托构造, 或者初始化成员列表
4. 执行函数体

*** operator

在 cpp 里, 运算符重载就是成员函数或普通函数, 只有名字是特殊的

#+begin_src cpp
return_type operator<op>(parameter_list) [cv] [ref] [noexcept];
#+end_src

这个没有任何神奇的, 只是一个函数名叫 operator<op> 的函数, 其中这个 operator 的左值是这个 operator 对应的 object, 然后这个右值是传入这个 method 的 arguments

比如
#+begin_src cpp
// operator function declaration
bool PNG::operator==(PNG const& other) const;

// you can write
bool c = (a == b); // a and b are PNG type objects

// this is equivalent to
bool c = q.operator==(b);
#+end_src

[cv] (const / volatile): 最常见的是 const, 如果你写 bool operator==(const Sphere& other) const;, 最后的那个 const 意味着这个运算符不会修改当前对象, 如果你有一个 const Sphere s1，它只能调用带 const 修饰的成员函数/运算符

[ref] (& / &&) —— 引用限定符 (cpp11): 它限制了运算符是给“左值”用还是“右值”用, &: 只能由 lvalue 调用, &&: 只能由rvalue调用

[noexcept] (C++11): 告诉编译器这个运算保证不会抛出异常, 编译器看到这个后会进行极致优化, 对于移动构造函数和移动赋值运算符来说加上 noexcept 非常关键

*** inheritance

忘记了, 暂时还没碰到, 先放着, 碰到了学了再写

*** function overload / virtual function

忘记了, 暂时还没碰到, 先放着, 碰到了学了再写


* lecture 02

** more on constructor

可以在 default constructor 里面调用 custom constructor 去完成 initialization, 叫做委托构造函数 ( delegating constructor )

#+begin_src cpp
#include "sphere.h"
namespace cs225 {
    // delegating constructor: 委托构造函数
    Sphere::Sphere() : Sphere(1.0) {} // 在 initialization list 的位置调用 custom constructor

    Sphere::Sphere(double r) : r_(r) {
        // other logic
    } // custom constructor
}
#+end_src

讲一下这个语法
Sphere::Sphere() : Sphere(1.0) {} 里面最右边的那个冒号叫做: 构造函数初始化列表 ( constructor initializer list ), 是 cpp 里面唯一一个可以在对象 "出生瞬间" 初始化东西的地方, 相当于是说他定义了, 在这个对象一旦被声明和初始化的时候的 behavior 是什么

#+begin_src cpp
Constructor
  : initializer1,
    initializer2,
    ...
{
    // constructor body
}
#+end_src

这里面的 initializer 可以是下面两者之一: 1. list initialization, 2. delegating initialization

但是你只能选择 list initialization 或者 delegating initialization, 不能同时两者

再强调一遍 cpp object 的初始化过程:
1. 分配内存
2. 执行 constructor initializer list 的相关内容 ( 只能在 initializer list 的地方干预, 否则就是执行每一个东西的默认的初始化 )
3. 执行构造函数体 {}

这个冒号后面的地方是我们唯一可以干预的地方

凡是 "对象一出生就必须确定的东西", 只能写在 : 后面, 比如 const, reference, delegating construction, base class object

注意区分初始化成员列表和委托构造函数, 初始化成员列表和委托构造函数的语法一摸一样, 但是你只能选择初始化成员列表或者委托构造函数中的一种, 一个是直接初始化成员, 另一个是委托给另一个构造函数

体会一下 cpp 的哲学 RAII:
RAII = Resource Acquisition Is Initialization
资源的获取 = 对象的初始化, 资源的释放 = 对象的析构

** stack & heap, RAII

一个从低地址向高地址增长 ( heap ), 一个从高地址向低地址增长 ( stack )

注意, cpp 里面不用 malloc 和 free, 用的是 new 和 delete, 其中 new 和 malloc 还不一样, new 分配地址 + 调用初始化函数, 但是 malloc 是只有分配地址, delete 会调用 destructor 同时释放内存

pain point 是如果你忘记了 delete 会内存泄漏, 如果 new 之后代码抛出错误, 还没运行到 delete 内存也会泄露, 还有对同一个指针 delete 两次会导致崩溃

从 cpp11 开始 ( 并在 Cpp14/17 中完善), 我们提倡 RAII ( 资源获取即初始化 ), 简单说就是用一个对象来包装原始指针, 当这个对象"死"掉 ( 离开作用域 ) 时, 它会自动在析构函数里帮我们调用 delete
RAII: Resource Acquisition Is Initialization,
资源获取 = 对象初始化, 资源释放 = 对象析构,
RAII 的核心只有一句话: 把资源的生命周期绑定到一个栈对象的生命周期上

当然现代有了 smart pointers, 比如 unique_ptr, 还有 shared_ptr, 这个以后碰到了再写

** memory location 重温

重温了一下 run time stack, 以及使用 lldb (md, gdb 不支持这个, 绷不住了) 去看了一下 undefined behavior, 下面是这个例子

cpp 文件, 这个 Sphere 的 object 是在 run time stack 上面被创建的, 在调用下面的函数的时候这个 stack 大概率已经被 clear 了
#+begin_src cpp
#include "sphere.h"
#include <iostream>

using namespace cs225;

Sphere *CreateUnitSphere() {
  Sphere s(1);
  return &s;
}

int main() {

  Sphere *s = CreateUnitSphere();

  double r = s->getRadius();
  std::cout << "r: " << r << std::endl;
  double v = s->getVolume();
  std::cout << "v: " << v << std::endl;

  return 0;
}
#+end_src

compile and run ( on mac )
#+begin_src zsh
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % g++ -g -c sphere.cpp
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % g++ -g -c sphere-badCreate.cpp
sphere-badCreate.cpp:8:11: warning: address of stack memory associated with local variable 's' returned [-Wreturn-stack-address]
    8 |   return &s;
      |           ^
1 warning generated.
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % g++ sphere.o sphere-badCreate.o -o bad_create
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % ./bad_create
r: 1
v: 0
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 %
#+end_src

在 ubuntu24.04 上面 compile + run
#+begin_src bash
(base) zhb:~/Desktop/code-lecture02$ g++ -c -g sphere.cpp
(base) zhb:~/Desktop/code-lecture02$ g++ -c -g sphere-badCreate.cpp
sphere-badCreate.cpp: In function ‘cs225::Sphere* CreateUnitSphere()’:
sphere-badCreate.cpp:8:10: warning: address of local variable ‘s’ returned [-Wreturn-local-addr]
    8 |   return &s;
      |          ^~
sphere-badCreate.cpp:7:10: note: declared here
    7 |   Sphere s(1);
      |          ^
(base) zhb:~/Desktop/code-lecture02$ g++ sphere.o sphere-badCreate.o -o bad_create
(base) zhb:~/Desktop/code-lecture02$ ./bad_create
Segmentation fault (core dumped)
(base) zhb:~/Desktop/code-lecture02$
#+end_src

gdb 去查看发生了啥
#+begin_src bash
Breakpoint 1, main () at sphere-badCreate.cpp:13
13        Sphere *s = CreateUnitSphere();
(gdb) info locals
s = 0x7ffff7cb738f <_GLOBAL__sub_I_eh_alloc.cc(void)+431>
r = 6.9533490978045684e-310
v = 6.9533558074180129e-310
(gdb) print &s
$1 = (cs225::Sphere **) 0x7fffffffddc8
(gdb) print &r
$2 = (double *) 0x7fffffffddd0
(gdb) print &v
$3 = (double *) 0x7fffffffddd8
(gdb) step
CreateUnitSphere () at sphere-badCreate.cpp:6
6       Sphere *CreateUnitSphere() {
(gdb) s
7         Sphere s(1);
(gdb) print &s
$4 = (cs225::Sphere *) 0x7fffffffdda0
(gdb) finish
Run till exit from #0  CreateUnitSphere () at sphere-badCreate.cpp:7
0x00005555555552e1 in main () at sphere-badCreate.cpp:13
13        Sphere *s = CreateUnitSphere();
Value returned is $5 = (cs225::Sphere *) 0x0
(gdb) print s
$6 = (cs225::Sphere *) 0x7ffff7cb738f <_GLOBAL__sub_I_eh_alloc.cc(void)+431>
(gdb) print *s
$7 = {r_ = 6.8523770472794107e+38}
(gdb) s
15        double r = s->getRadius();
(gdb) print r
$8 = 6.9533490978045684e-310
(gdb) s
cs225::Sphere::getRadius (this=0x0) at sphere.cpp:13
13          return r_;
(gdb) s

Program received signal SIGSEGV, Segmentation fault.
0x0000555555555208 in cs225::Sphere::getRadius (this=0x0) at sphere.cpp:13
13          return r_;
(gdb) s

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
#+end_src

他得到的返回值甚至不是原来的 stack 地址, 只能说 UB 是真的 Undefined Behavior
还有这里的 stack 的分布并不是真的是 local variable 先声明的先 push, 呃, 这个, emm, 只能说比较灵活吧, 但是有的地方是先声明先分配的

我们再试验一下这个 stack 的问题, 把他 print 出来
macbook 上面
#+begin_src bash
s->getRadius(): 4.17291e-314
&s (main): 0x16d7d2d18
 s (main): 0x16d7d2cb8
&r (main): 0x16d7d2d10
 r (main): 4.17291e-314
&v (main): 0x16d7d2d08
 v (main): 0
#+end_src

只能说两个表现很不一样了, 两个东西的 UB 还有 stack behavior 完全不一样呢, UB 就是完全 Undefined, 啥都有可能发生 ( compiler 的 preference 了 )

我还发现 ubuntu 和 mac 的 run time stack 的生长方向好像不一样, 先创建的 variable 在 mac 上是在高地址, 但是在 ubuntu 上是低地址:
ubuntu:
#+begin_src bash
(gdb) print &s
$1 = (cs225::Sphere **) 0x7fffffffddc8
(gdb) print &r
$2 = (double *) 0x7fffffffddd0
(gdb) print &v
$3 = (double *) 0x7fffffffddd8
(gdb) step
#+end_src
mac:
#+begin_src zash
&s (main): 0x16d7d2d18
 s (main): 0x16d7d2cb8
&r (main): 0x16d7d2d10
 r (main): 4.17291e-314
&v (main): 0x16d7d2d08
 v (main): 0
#+end_src

还有一个例子:

#+begin_src cpp
#include <iostream>

using namespace std;

int main() {

  int first = 42;
  int arr[6];

  cout << &first << endl;
  cout << &(arr[0]) << endl;
  cout << &(arr[1]) << endl;
  cout << &(arr[2]) << endl;

  return 0;
}
#+end_src

编译之后在 ubuntu 上面跑
#+begin_src bash
(base) zhb:~/Desktop/code-lecture02$ g++ stack-array.cpp
(base) zhb:~/Desktop/code-lecture02$ ./a.out
0x7ffc30b2507c
0x7ffc30b25080
0x7ffc30b25084
0x7ffc30b25088
(base) zhb:~/Desktop/code-lecture02$
#+end_src

编译之后在 mac 上面跑
#+begin_src bash
~/Desktop/cs225/lecture/lecture02/code-lecture02 $ g++ stack-array.cpp
~/Desktop/cs225/lecture/lecture02/code-lecture02 $ ./a.out
0x16fa6acf8
0x16fa6ad00
0x16fa6ad04
0x16fa6ad08
~/Desktop/cs225/lecture/lecture02/code-lecture02 $
#+end_src

这下两个一样了, 但是我发现这个顺序好像并不是我们在 lc3 里面学到的那样先 declare 的先 push, 我们再写个东西 check 一下

#+begin_src cpp
#include <iostream>

void f(int i) {
	int a = i;
	std::cout << "a: " << a << " Address of a: " << &a << std::endl;
	if (i > 0) {
		f(i - 1);
	}
}


int main(void) {
	f(3);
	return 0;
}
#+end_src

macbook
#+begin_src bash
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % g++ stack_growth.cpp
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % ./a.out
a: 3 Address of a: 0x16bd82d18
a: 2 Address of a: 0x16bd82cf8
a: 1 Address of a: 0x16bd82cd8
a: 0 Address of a: 0x16bd82cb8
#+end_src

ubuntu
#+begin_src bash
(base) zhb:~/Desktop$ g++ stack_growth.cpp
(base) zhb:~/Desktop$ ./a.out
a: 3 Address of a: 0x7ffe11687384
a: 2 Address of a: 0x7ffe11687354
a: 1 Address of a: 0x7ffe11687324
a: 0 Address of a: 0x7ffe116872f4
(base) zhb:~/Desktop$
#+end_src

run time stack 确实是从高地址往低地址增长的

总的来说, 就是这个 run time stack 确实是一般从高地址向低地址增长, 但是一个函数内部, 变量声明的先后和这个 stack 上变量的位置没有必然的关系

总之, 我们获得了两个确定的结论:
1. run time stack 总的方向上, 是从高地址向低地址增长的
2. 一个 array 内部, &(array[0]) < &(array[1]) < ...., 而且大概率紧密排列

其他都不是确定的, 没有一个固定的标准, run time stack 内部的 behavior 完全是编译器爱咋干就咋干


* lecture 03

我只能说这节课体验极差, 老师什么都没有讲清楚, 讲的就是一坨狗屎, 但是老师看上去自己确乎是懂的, 只是不想讲清楚, 不像某些 220 老师, 看上去自己都不懂, 下面整理清楚

** 1. 重识 reference
*** (1) reference semantics
reference: an alias of an existing object

之前一直使用的是 const pointer 的角度去理解这个 reference, 这样是有问题的, reference 实际上真的就是一个 alias, 是在编译器处理阶段就解决的, 并不是分配了一个 const pointer 类型的 variable, 或者说, reference variable 根本就不是一个 variable, 并没有真的在 stack 或者 heap 上面分配内存给这个 reference variable, 这个似乎是有点像 macro, 就是在编译的时候就直接结束了, 他就真的只是这个变量的一个 alias

一个 reference 的基本要求是:
- Must be initialized when declared.
- Cannot be reassigned to refer to a different object.
- No null references.

如果在被创建的时候没有被初始化, 会直接编译错误, 而不是 Undefined Behavior

这个是验证代码
#+begin_src cpp
#include <iostream>

int main() {
    int * x = new int;
    int & y = *x;

    y = 4;

    std::cout << "&x, on stack: " << &x << std::endl;
    std::cout << "x, on heap: " << x << std::endl;
    std::cout << "*x, value: " << *x << std::endl;

    std::cout << "y " << y << std::endl;
    std::cout << "&y: " << &y << std::endl;
    // std::cout << "*y" << *y << std::endl; // invalid

    return 0;
}
#+end_src

然后我们运行一下:
#+begin_src bash
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ reference.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./a.out
&x, on stack: 0x16b576d30
x, on heap: 0x600000c9c030
*x, value: 4
y 4
&y: 0x600000c9c030
#+end_src

在 programmer 的层面, reference 实际上就是对象的 alias, 也就是说, coding 的时候我们代指的就是那个真实的对象, 我们并没有在任何一个地方去分配一个实际的地址给这个 reference variable, 他实际上就是一个对象的 memory 的 alias, 但是在编译器的行为上, 传参数的时候, 你使用 reference 传参等价于传递一个指针, 或者说几乎等价, 老师上课说的 "pass parameter by reference" 没有 copy 是错的, 或者至少说, 在语意上是不严谨的, 你要访问这个 object, 你是一定要知道他的物理地址的, 不然没法访问, 他说的 "没有 copy " 是在人类语意上的说法, 但是在衡量这个开销的时候, 肯定是从调用函数的时候底层的表现来讲的, 在调用的时候肯定是往 stack 里面压入一个地址的, 不可能什么东西都不传递

虽然在硬件的 ABI 上面, pointer 和 reference 似乎没什么区别 ( 简化的来看, reference 就是一个 const pointer ), 但是在语意上, 两者还是有区别的, 比如说, 你传递一个参数为 pointer, 这个可以是 NULL, 或者说用 cpp 的办法是 nullptr, 并没有保证说是这个东西一定指向一个 object, 但是如果是一个 reference 的话, 这个东西在语意上是一个 object, 或者说是一块 memory 的 alias, 所以他是有保证的

*** (2) reference 用于传参
接下来讲一下传参数的三种办法, pass by value, pass by pointer, pass by reference, 顺便复习一下 const 的用法

#+begin_src cpp
// pass by object
void function(const class_name object);
void function(class_name const object);

// pass by pointer
void function(const class_name *object);
void function(class_name const *object);

// pass by reference
void function(const class_name &object);
void function(class_name const &object);
#+end_src

复习一下, const 修饰的是他左边的东西, 就是他左边的东西是不可以改变的, 比如说 int const *x;, 这里 int 是不可改变的, 也就是说, 指针 x 可以指向不同的 int, 但是x不能修改他指向的东西的值
如果写成了 int * const x;, 这种写法表示 int * 是不可改变的, 也就是说指针不能重新指向别的 int, 但是指针可以修改这个指向的 int 的值

void function(const Class object), 这个写法等价于 void function ( Class const object ), ( const 修饰左边的东西，如果没有的话就修饰右边最近的东西), 这里反正都是表示传入的是一个 const object, 但是实际上因为传入的是 object, 反正是 copy 的, 你反正没有办法改变原来的值, 所以 const 关键字加不加意义不大

void function(const Class * pointer), 这个写法也等价于 void function (Class const * pointer), 这个表示的是, pointer 指向的是一个 const object, 也就是说你不能通过这个 pointer 去修改这个pointer 指向的 object, 但是你的 pointer 可以指向不同的 const object

void function(const Class & reference), 等价于 void function(Class const & reference), 这个 const 表示这个 reference alias 指向的那个 object 是不可以改变的, 但是因为你的 reference 在初始化之后就不能重新绑定了, 所以实际上你的 reference 也不能当另一个 object 的 alias

所以我们一般在传递参数的时候, 因为 reference 不可重新绑定的特性, 以及 const 关键字修饰表示这个 reference 绑定的 object 不能被改变, 所以说 void function(const class_name &object); 的传参方式是最安全的

*** (3) tricky example

因为 pass by reference + const 的安全特性, 他对调用 const reference 的函数也做出了要求, 他要求这个函数不会改变 const reference 这个 object 而这个很容易被忘记, 一个比较 tricky 的 example 如下:

sphere.cpp
#+begin_src cpp
#include "sphere.h"
#include <math.h>

Sphere::Sphere(double r) : r_(r) {
    ;
}

double Sphere::getVolume() {
    return (4.0 / 3.0 * 3.141592654 * pow(r_, 3));
}

Sphere joinSpheres(const Sphere s1, const Sphere s2) {
    double totalVolume = s1.getVolume() + s2.getVolume();
    double newRadius = pow(
        (3.0 * totalVolume) / (4.0 * 3.141592654),
        1.0/3.0);
    Sphere result(newRadius);
    return result;
}
#+end_src

main.cpp
#+begin_src cpp
#include "sphere.h"

int main() {
    Sphere *s1 = new Sphere(4);
    Sphere *s2 = new Sphere(5);
    Sphere s3 = joinSpheres(*s1, *s2);
    delete s1; s1 = nullptr;
    delete s2; s2 = nullptr;
    return 0;
}

#+end_src

直接编译会有编译错误:
#+begin_src bash
zhb ~/Desktop % g++ -std=c++11 -c -g sphere.cpp
sphere.cpp:13:26: error: 'this' argument to member function 'getVolume' has type 'const Sphere', but function is not marked const
   13 |     double totalVolume = s1.getVolume() + s2.getVolume();
      |                          ^~
sphere.cpp:8:16: note: 'getVolume' declared here
    8 | double Sphere::getVolume() {
      |                ^
sphere.cpp:13:43: error: 'this' argument to member function 'getVolume' has type 'const Sphere', but function is not marked const
   13 |     double totalVolume = s1.getVolume() + s2.getVolume();
      |                                           ^~
sphere.cpp:8:16: note: 'getVolume' declared here
    8 | double Sphere::getVolume() {
      |                ^
2 errors generated.
#+end_src

这个是因为, 在函数 joinSpheres 里面, 我们传递的参数是 const reference, 也就是说, 我们要求不修改传入的 object, 但是在 class Sphere 的 member function getVolume 里面, 我们并没有给 getVolume 加上 const 关键字 ( 保证 *this 里面的任何一个 attribute 都不变 ), 但是在 joinSpheres 里面我们调用了 s1.getVolume() 和 s2.getVolume(), 所以编译器报错了

加上 const 关键字修饰 getVolume 以后就可以正常编译了:

sphere.cpp
#+begin_src cpp
#include "sphere.h"
#include <math.h>

Sphere::Sphere(double r) : r_(r) {
    ;
}

double Sphere::getVolume() const {
    return (4.0 / 3.0 * 3.141592654 * pow(r_, 3));
}

Sphere joinSpheres(const Sphere s1, const Sphere s2) {
    double totalVolume = s1.getVolume() + s2.getVolume();
    double newRadius = pow(
        (3.0 * totalVolume) / (4.0 * 3.141592654),
        1.0/3.0);
    Sphere result(newRadius);
    return result;
}
#+end_src

#+begin_src bash
zhb ~/Desktop % g++ -std=c++11 -c -g sphere.cpp
zhb ~/Desktop % g++ -std=c++11 -c -g main.cpp
zhb ~/Desktop % g++ main.o sphere.o -o executable
#+end_src


** 2. 重识 constructor

*** (1) default constructor 复习
这个东西老师是真的没有讲清楚, 我受不了了, 他为什么不讲清楚, 他妈的知道不知道自己去查这个东西, 自己跟 gpt 交互去学这个是很累的? 他两句话就能讲清楚, 做一个表格也就十分钟的事情, 却浪费我半个多小时去打字向 gpt 提问, 我真的是受不了了, 为什么要有意或者无意的提高知识获取的难度, 打字打多了手都酸了, 受不了一点

算了, 不管了, 先说清楚以下的东西:
1. default constructor: 定义是, 如果我们有 class class_name, object of class_name 的 default constructor 是一个不接受任何参数的 constructor for class_name, 评判一个 constructor 是不是 default 的唯一标准是接受不接受参数
2. implicitly-declared default constructor: 对 class_name 这个 class, 你没有写任何一个 constructor, 然后编译器会自动帮你生成一个 constructor, 这个 constructor 不接受任何参数, 所以是一个 default constructor, 你一旦写了任何一个 constructor, 那编译器就不会给你生成这个 implicitly-declared default constructor
3. user-provided default constructor: 你自己写的 default constructor

好了, 关于 default constructor 的定义就这么多, 接下来举例子看表现 ( 注意, cpp 里面, class 的东西没写 public 的话默认是 private 的, struct 里的东西没写 private 的话, 默认是 public 的 )

#+begin_src cpp
#include <iostream>

class B {
    public:
    int b;
    double c;
};

class A {
    public:
    int x;
    std::vector<int> v;
    B b;
};

class C {
    public:
    int x;
    std::vector<int> v;
    B b;

    C() {
        std::cout << "class C default constructor, fuck you cpp" << std::endl;
    }
};

class D {
    public:
    int x;
    std::vector<int> v;
    B b;

    D(int r) : x(r){
        std::cout << "class D custom constructor, fuck you cpp" << std::endl;
    }
};

int main() {
    // test behavior of class A, implicitly-declared default constructor
    A obj_a;
    A obj_a_ = A();

    // test behavior of class C, custom default constructor
    C obj_c;
    C obj_c_ = C();

    // test behavior of class D, no implicitly-declared default constructor
    D obj_d; // compile error
    D obj_d_ = D();
}
#+end_src

编译错误如下:
#+begin_src cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ default-constructor.cpp
default-constructor.cpp:48:7: error: no matching constructor for initialization of
      'D'
   48 |     D obj_d; // compile error
      |       ^
default-constructor.cpp:33:5: note: candidate constructor not viable: requires
      single argument 'r', but no arguments were provided
   33 |     D(int r) : x(r){
      |     ^ ~~~~~
default-constructor.cpp:27:7: note: candidate constructor (the implicit copy
      constructor) not viable: requires 1 argument, but 0 were provided
   27 | class D {
      |       ^
default-constructor.cpp:27:7: note: candidate constructor (the implicit move
      constructor) not viable: requires 1 argument, but 0 were provided
   27 | class D {
      |       ^
default-constructor.cpp:49:16: error: no matching constructor for initialization
      of 'D'
   49 |     D obj_d_ = D();
      |                ^
default-constructor.cpp:33:5: note: candidate constructor not viable: requires
      single argument 'r', but no arguments were provided
   33 |     D(int r) : x(r){
      |     ^ ~~~~~
default-constructor.cpp:27:7: note: candidate constructor (the implicit copy
      constructor) not viable: requires 1 argument, but 0 were provided
   27 | class D {
      |       ^
default-constructor.cpp:27:7: note: candidate constructor (the implicit move
      constructor) not viable: requires 1 argument, but 0 were provided
   27 | class D {
      |       ^
2 errors generated.
#+end_src

修正错误 (把有关 D 的东西直接注释掉) 之后, 运行结果

#+begin_src bash
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ default-constructor.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./a.out
class C default constructor, fuck you cpp
class C default constructor, fuck you cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $
#+end_src

可见我们对这个东西的理解是对的, 对于 class C 来说, 这里直接调用的是 custom 的 default constructor

*** (2) copy constructor

copy constructor 的判定是 "函数签名层面的", 不是 "你在函数里做了什么", 对 class A 来说, copy constructor 是一个构造函数, 满足
(1) 构造函数名是 A
(2) 第一个参数是 const A & 类型或等价形式
(3) 其余参数 (如果有) 都有默认值 ( 但是我们一般不考虑其他参数 )

copy constructor 是在使用一个已经有的 object 对另一个新的 object 进行初始化的时候调用的, 而不是对一个已经有的 object assign value 的时候调用的 ( 这个是 operator= )

Automatic Copy Constructor 对 pointer 只是进行了 shallow copy, 所以如果你需要 copy 这个 pointer 指向的地址的内容的话, 你需要自己写 custom copy constructor

对于不止一个参数的 copy constructor, 我们澄清一下:
#+begin_src cpp
A(const A &other, int x = 0); // copy constructor
A(const A &other, int x);
#+end_src

第一个参数永远是 "被拷贝对象", 剩下的参数是可选的且必须有默认值, 保证无参调用时也可以调用这个函数 (因为在大多数情况下 copy constructor 会在只给一个对象的时候被调用), 如果你写了一个额外参数但不给默认值, 编译器就不再认它是 copy constructor

典型形式:
#+begin_src cpp
// copy constructor
A(const A& other);
A(A const& other);

// 不是 copy constructor, 即使你真的在做 copy 这个任务
A(const A other);
#+end_src

不使用 A(const A other) 这个形式的原因是, 这里的参数是使用 value 传递的, 你要得到这个 value, 就要调用 copy constructor, 但是你的 copy constructor 又是值传递的, 这样会无限递归

再次强调, copy constructor 在 "初始化新对象" 时被调用, 而不是在 assign value 的时候被调用

#+begin_src cpp
ClassName a;
ClassName b = a;   // 不是赋值是初始化, copy constructor, 等价于 A b(a);
b = a;  // 这个是赋值, 等价于 b.operator=(a);
#+end_src

写个小程序验证一下
#+begin_src cpp
#include <iostream>

class aClass {
    public:
        int a;
        double b;
        aClass() {
            ;
        }

        aClass(const aClass & another) : a(another.a), b(another.b) {
            std::cout << "custom copy constructor called" << std::endl;
        }

        aClass operator=(const aClass & another) {
            this->a = another.a;
            this->b = another.b;
            std::cout << "operator = is called" << std::endl;
            return another;
        }
};

int main() {
    aClass a;
    aClass b = a;
    b = a;
    return 0;
}
#+end_src

编译运行, 得到
#+begin_src bash
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ copy-constructor.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./a.out
custom copy constructor called
operator = is called
custom copy constructor called
#+end_src

这里有三次 copy constructor 被调用, 第三次是在 operator= 的返回的时候, 因为我们返回的类型不是 reference, 是一个 aClass 的 object, 所以这里调用了一次 copy operator, 你可以通过改写这个 operator& 的返回类型, 变成 const reference 返回, 这样就不会有多余拷贝 ( 也是标准的 reference 版的预防成为 lvalue 的 operator= 的写法 )

#+begin_src cpp
#include <iostream>

class aClass {
    public:
        int a;
        double b;
        aClass() {
            ;
        }

        aClass(const aClass & another) : a(another.a), b(another.b) {
            std::cout << "custom copy constructor called" << std::endl;
        }

        aClass const & operator=(const aClass & another) {
            this->a = another.a;
            this->b = another.b;
            std::cout << "operator = is called" << std::endl;
            return another;
        }
};

int main() {
    aClass a;
    aClass b = a;
    b = a;
    return 0;
}
#+end_src

编译运行结果
#+begin_src bash
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./a.out
custom copy constructor called
operator = is called
#+end_src

当然, 写成
#+begin_src cpp
aClass & operator=(const aClass & another) {
    this->a = another.a;
    this->b = another.b;
    using namespace std;::cout << "operator = is called" << std::endl;
    return *this;
}
#+end_src

也是可以的, 这个写法非常有趣, 事实上这个就是 STL 的标准的 operator= 的写法, 返回的是 reference, 绑定的是 operator= 的 lvalue, 这个允许了 (a=b) = c 这种写法

关于 implicitly-declared copy constructor, 这个东西是 element-wise member copy, 就是说, 如果你的 class 有一个 attribute 是 type * ptr;, 那么他只是复制一遍 ptr 这个地址, 不会把 ptr 指向的 object 再复制一遍, 如果你已经写了一个 copy constructor, 那这样编译器就不会自动给你生成 implicitly-declared copy constructor, 这样就会报错

当然, 你可以使用 defaulted copy constructor, 就是像下面这样

#+begin_src cpp
struct A {
    A(const A&) = default;
};
#+end_src

这个意思是, 你 explicitly 要求要一个 copy constructor, 但是要求他表现的跟 implicitly-declared constructor 一样

*** (3) puzzle example

我们下面分析一下一个 sphere 的例子, 讲一下理论上应该怎么 behave, 实际上应该怎么样

#+begin_src cpp
#include "sphere.h"
#include <iostream>

using namespace std;

namespace cs225 {

  Sphere::Sphere() : Sphere(1.0) {
    cout << "Default ctor" << endl;
  }

  Sphere::Sphere(double r) {
    cout << "1-param ctor" << endl;
    r_ = r;
  }

  Sphere::Sphere(const Sphere &s) {
    cout << "copy ctor" << endl;
    r_ = s.r_;
  }


  double Sphere::getRadius() const {
    return r_;
  }

  void Sphere::setRadius(double r) {
    r_ = r;
  }

  double Sphere::getVolume() const {
    return (4 * r_ * r_ * r_ * 3.14159265) / 3.0;
  }

}
#+end_src

这里面的 constructor 讲明白了你在调用哪个, 然后我们实现一下 copy by value 的 函数

**** a. pass by value

#+begin_src cpp
#include "sphere.h"
#include <math.h>

using namespace cs225;

Sphere joinSpheres(Sphere s1, Sphere s2) {

  double totalVolume = s1.getVolume() + s2.getVolume();

  double newRadius = pow((3.0 * totalVolume) / (4.0 * 3.141592654), 1.0/3.0);

  Sphere result(newRadius);

  return result;
}


int main() {

  Sphere *s1 = new Sphere(4);
  Sphere *s2 = new Sphere(5);

  Sphere s3 = joinSpheres(*s1, *s2);

  return 0;
}
#+end_src

理论上来说, 我们得到的应该是
1. Sphere *s1  = new Sphere(4) 是一个 one parameter constructor
2. Sphere *s2  = new Sphere(5) 是一个 one parameter constructor
3. 传参是传 value, joinSpheres(*s1, *s2) 里面 *s1 和 *s2 各一次 copy constructor
4. Sphere result(newRadius); 是一个 one parameter constructor
5. return 的时候从 result 这个 local variable 把参数复制到 joinSpheres stack 的 return value 的值, 调用一次 copy constructor
6. Sphere s3 = joinSpheres(*s1, *s2);, return 的值赋给 s3, 再调用一次 copy constructor

跑一下验证一下:
#+begin_src cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ -c -o0 sphere.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ -c -o0 joinSpheres-byValue.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ sphere.o joinSpheres-byValue.o -o byVaule
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./byVaule
1-param ctor
1-param ctor
copy ctor
copy ctor
1-param ctor
~/Desktop/cs225/lecture/lecture03/code-lecture03 $
#+end_src

实际上我们猜测的后面两个 copy constructor 都没有被调用

这个是因为, 在现代 cpp 中有 NRVO (Named Return Value Optimization) 优化, 这个优化的语意是这种情形的 result 直接构造在调用方的返回对象存储位置上, c++11 起, 允许后面两个 copy 不发生, c++17 起, 直接强制规定这两个 copy 不发生, 所以我们这里的 joinSpheres 里面的 result 那个对象是直接建立在 s3 上面的, 我们 gdb 进去看一看

#+begin_src bash
(base) zhb:~/Desktop$ g++ -c -g sphere.cpp
(base) zhb:~/Desktop$ g++ -c -g byValue.cpp
(base) zhb:~/Desktop$ g++ sphere.o byValue.o -o byValue
(base) zhb:~/Desktop$ gdb ./byValue
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./byValue...
(gdb) b main
Breakpoint 1 at 0x1439: file byValue.cpp, line 21.
(gdb) run
Starting program: /home/zhb/Desktop/byValue

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at byValue.cpp:21
21	int main() {
(gdb) info locals
s1 = 0x12000
s2 = 0x2e78786362696c67
s3 = {r_ = 6.9533558074168272e-310}
(gdb) p &(s3)
$1 = (cs225::Sphere *) 0x7fffffffdec0
(gdb) p &(s3.r_)
$2 = (double *) 0x7fffffffdec0
(gdb) n
23	  Sphere *s1 = new Sphere(4);
(gdb) n
1-param ctor
24	  Sphere *s2 = new Sphere(5);
(gdb) n
1-param ctor
26	  Sphere s3 = joinSpheres(*s1, *s2);
(gdb) b cs225::Sphere::Sphere(double)
Breakpoint 2 at 0x555555555275: file sphere.cpp, line 13.
(gdb) continue
Continuing.
copy ctor
copy ctor

Breakpoint 2, cs225::Sphere::Sphere (this=0x7fffffffdec0, r=5.7387935458815473) at sphere.cpp:13
13	    cout << "1-param ctor" << endl;
(gdb) p this
$3 = (cs225::Sphere * const) 0x7fffffffdec0
(gdb) exit
A debugging session is active.

	Inferior 1 [process 46315] will be killed.

Quit anyway? (y or n) y
(base) zhb:~/Desktop$
#+end_src

你会发现这个 this 指针就是 s3 的地址, 只能说老师对于这个东西的理解还是很久之前的, 现代 cpp 已经不这么做了

**** b. pass by const value

不想写了, 自己跑一下 lecture/lectore03/code-lecture03 里面的 demo 吧, 我感觉上面的已经分析的很清楚了, ppt 里面也有, 相信如果上面 pass by value 的例子看懂之后你一定是会的


* lecture 04

这节课的核心是 resource management, 主要是一些概念上的介绍, coding 和 hardware 层面的东西比较少

或者说, 我前面 lecture 01/02/03 还有知识铺垫做的比较全面导致这里似乎没有那么多具体知识点可以讲 🤪

the rule of three 实际上可以扩展到 the rule of five ( 算上 movement constructor 还有 movement assign operator, 为 cpp11 往后的语言特性设计的 ), 这个以后碰到了再说

这里要开始着重体会 cpp 里面的设计哲学 RAII (resource acquaintance is initialization)

还有说一下, in cpp, never copy code, 要抽象逻辑然后复用, copy code 的时候你大概率是做错了 ( 比如对于 copy constructor 和 operator=, 里面都涉及从一个 object 创建/修改另一个 object, 可以把这个逻辑抽象为 copy_ 作为一个 private 函数, 然后在 copy constructor 和 operator= 里面调用这个 private member function copy_ )

** 1. destructor

the last function being called for an existing instance before it appears, the purpose is to cleanup this resource

当一个 object 被创建的时候, constructor 被 called, 当一个 object 被 destroyed 的时候, 有一些东西也要被 called, 这个东西就是 destructor, 注意 destructor 没有 manually called 的情况, 他就是 automatically called, like your object is deleted from the heap, or gets out of scope on the stack, 你永远不应该 manually call destructor

至于一个 object 什么时候被 destroyed? 当一个 object 的生命周期结束了, 他就会被 destroyed

default destructor is provided, and it has no parameters, 语法是跟 classname 同名, 但是多一个 ~, 没有任何参数

#+begin_src cpp
class Sphere {
    public:
        Sphere(); // default constructor
        ~Sphere(); // destructor
}
#+end_src

default destructor 又叫 Implicitly-defined Destructor, 它的函数体是空的 {}, 他的行为是会自动且递归地调用类中所有成员变量的析构函数以及基类的析构函数, 对于基本类型 ( int, double, ..) 的指针, 他并不会 delete [] 指针指向的东西, 这个就很灾难了, memory leakage, surprise!!!

编译器认为指针只是一个数值 ( address ), 它不知道这个地址背后是一块需要手动释放的资源, 这就是为什么你必须自定义析构函数并调用 delete

** 2. operator
*** (1) 基本的 operator overload

cpp 里面可以 overload 很多 operator, 语法设计和逻辑在 cpp 入门特性/operator 那里讲过了, 不再重提, 这里列举一下可以被 overload 的 operator

arithmetics: + - * / % ++ --
bitwise: & | ^ ~ << >>
assignment: =
comparison: == != > < >= <=
logic: ! && ||
other: [] () ->

这节课的重点是在说 resource management, 所以我们着重重新讲一下 assignment operator

*** (2) operator=

如果我不写 operator=, 只要你的类里没有一些极端情况 ( 比如包含 const 成员或引用成员, 这些不可更改), 编译器会自动生成一个默认的赋值运算符

自动实现的函数签名是:

#+begin_src cpp
T& T::operator=(const T& other) {
    // assignment logic
    return *this; // 默认的 behavior 是返回 operator= 的 lvalue 的 reference
}
#+end_src

这个 implicitly-defined copy assignment operator 的行为是执行 member-wise assignment, 也就是说它对类中的每个成员调用其对应的 operator=

对于内置类型 (int, 指针), 它执行的是 shallow copy, 这个很容易造成混乱

我们自己写 assignment operaotr 的时候, 要遵循上面的函数签名的写法, 里面实现的逻辑可以改, 但是函数签名一定要是这个

下面讲一下为什么会选择使用上面描述的函数签名

最主要的原因是, 在 cpp 里面 built in class 的 assignment 返回的都是 reference to the object itself, 我们需要 matching 这个操作

cpp 里面, a = b 返回的是 a reference to object a, 也就是 a reference to the lvalue of the operator =, 这个是一个 convention, 尽管你可以随便定义

下面讲解一下逻辑:

首先确定一下, 我们要么 return object, 要么 return reference, 不会 return pointer 的, 因为 return pointer 的话类型对不上, 很不合理
其次, 我们如果只是希望 return value 做 rvalue 的话 ( 也就是说, 你只会写 a = (b = c); 不会写 (a = b) = c; ), 那 return object 和 return reference 都可以, return object 会多一次创建对象 ( 因为有  NRVO, 即 Named Return Value Optimization 的存在, 所以不会 copy construct 好多次, 但是 construct 一次是不可避免的 ), 所以不如直接 return const reference
但是如果我们希望 return value 也能做 lvalue 的话 ( 也就是说你希望 a = (b = c) 和 (a = b) = c 都是合法的 ), 那 return object 是不行的, 我们只能 return reference 了, return 的一般是 *this, 也就是说 operator= 的 lvalue 这个 object, 因为一般我们 operator= 的 rvalue 是不希望被改变的, 所以我们一般传参传的是 const class_name & another, 我们希望 return value 做 lvalue 的话返回这个肯定是不行的 ( 还有就是这个 parameter 是 const reference, 不是 reference, 编译的时候实际会报错 )

** 3. the rule of three
*** (1) The rule of three
看上面的 implicitly-declared operator=/destructor 的表现 ( shallow copy 还有把内置类型的指针当作一般数值而不 delete ), 我们知道的是, 一旦我们 new 了东西我们就不能相信这个默认的 destructor/operator=, 我们要自己处理, 实际上这个情景要求我们同时自己实现 copy constructor, operator=, destructor, 或者说, 一旦我们需要实现这三者的任何一个, 我们基本就要把这三者都实现, 这个就是 the rule of three

the rule of three 的具体含义:

#+begin_quote
如果你发现你的类需要手动实现以下任意一个函数, 那么你极大概率需要同时实现剩下两个:
- Destructor: 释放资源
- Copy Constructor: 确保拷贝时资源也被正确处理
- Copy Assignment Operator: 确保赋值时旧资源释放，新资源拷贝
#+end_quote

这个是 RAII 的具体体现, 或者说是 cpp 下管理资源的具体体现

当然还有 the rule of five, 还有 the rule of zeor, the rule of three 是自己裸的手动管理资源的时候要做的, 当涉及智能指针了之后会有不一样的地方

*** (2) The Rule of Five:
#+begin_quote
If it is necessary to define any one of these three functions in a class, it will be necessary to define all five of these functions:
- Copy constructor
- Assignment operator
- The destructor
- Move constructor
- Move assignment operator
#+end_quote

对于 move constructor 还有 move assignment operator, 这里只做简要讲解:

Move Constructor (Steals resources from a temporary instead of copying), syntax: Sphere(const Sphere&& s);
Move Assignment (Releases current resources, then takes ownership from s), syntax: Sphere & operator=(const Sphere&& s);

**** move constructor & move assignment operator
下面是 gemini 的讲解, 我觉得很对, 就直接 copy 过来了:

move constructor 和 move assignment operator 不展开讲了, 以后碰到再说, 他解决的问题是 "原先资源的传递只能 copy 所有内容, 效率极低", Move的用途就在于不申请新内存不拷贝数据, 而是直接将源对象内部的指针 "偷" 过来并将源对象的指针置空 (nullptr), 这本质上是将昂贵的深拷贝降级为极其廉价的指针赋值

Move Constructor: 它的参数是一个 右值引用 (T&&), 右值引用告诉编译器 "这个源对象是一个临时的快要死掉的东西, 你可以随便蹂躏它的内部成员"
实现逻辑:
1. 接管资源: 将源对象的指针成员直接赋值给当前对象的指针
2. 切断联系(关键): 将源对象的指针设为 nullptr, 这一步至关重要, 否则源对象析构时会 delete 掉你刚刚“偷”过来的内存 ( 触发 RAII 保护机制 )
#+begin_src cpp
// 假设 Sphere 内部有一个 double* data_
Sphere(Sphere&& other) noexcept {
    this->data_ = other.data_;  // 指针拷贝
    other.data_ = nullptr;      // 令源对象失去所有权防止析构时释放内存
}
#+end_src

Move Assignment Operator: 签名通常是 Sphere& operator=(Sphere&& other) noexcept;
实现逻辑上, 移动赋值比移动构造多了一步，因为它必须处理当前已经持有的资源
1. 自赋值检查: 判断 this == &other
2. 释放旧资源: delete 掉当前对象原本持有的堆内存 ( 防止泄漏 )
3. 转移所有权: 同移动构造, 把 other 的指针拷贝过来
4. 源对象置空: other.data_ = nullptr
5. 返回 *this
#+begin_src cpp
Sphere& operator=(Sphere&& other) noexcept {
    if (this != &other) {
        delete data_;           // 1. 扔掉自己的旧货
        data_ = other.data_;    // 2. 偷别人的新货
        other.data_ = nullptr;  // 3. 让别人彻底放手
    }
    return *this;
}
#+end_src

为什么必须加 noexcept？

在嵌入式开发或高性能场景中这非常重要, 像 std::vector 这种容器在扩容 (reallocate) 时, 如果你的移动构造函数没有标记 noexcept, 它为了保证强异常安全性会退而求其次使用拷贝构造, 如果你忘了加 noexcept 你写的移动逻辑可能永远不会被调用, 导致性能大幅下降

*** (3) The Rule of Zero

从 the rule of five, 我们可以得到一个 collary, 即 "The Rule of Zero": 你的类应该尽量不手动编写任何一个上述五个函数, 因为容易出错

这怎么做到？ 利用 RAII 对象, 如果你的类成员全部是 "知道如何管理自己" 的对象 ( 比如 std::vector, std::string, std::unique_ptr ), 编译器生成的默认行为就完全正确

#+begin_quote
Classes that declare custom destructors, copy/move constructors or copy/move assignment operators should deal exclusively with ownership. Other classes should not declare custom destructors, copy/move constructors or copy/move assignment operators.

–Scott Meyers
#+end_quote


* lab_intro && lab_debug

做这两个 lab 的时候感觉还是学到了很多东西的

** cs 里面没有 magic

这里记录一个我在做 lab_intro 的时候感觉错了的地方, 后来发现没有问题, 是我还停留在 c 下面, 没有熟悉 cpp 的特性

main.cpp
#+begin_src cpp
int main() {
  cs225::PNG png, result;

  png.readFromFile("alma.png");
  result = grayscale(png);
  result.writeToFile("out-grayscale.png");

  return 0;
}
#+end_src

PNG.cpp
#+begin_src cpp
namespace cs225 {
  PNG::PNG() {
    width_ = 0;
    height_ = 0;
    imageData_ = NULL;
  }

  bool PNG::readFromFile(string const & fileName) {
    vector<unsigned char> byteData;
    unsigned error = lodepng::decode(byteData, width_, height_, fileName);

    if (error) {
      cerr << "PNG decoder error " << error << ": " << lodepng_error_text(error) << endl;
      return false;
    }

    delete[] imageData_;
    imageData_ = new HSLAPixel[width_ * height_];

    for (unsigned i = 0; i < byteData.size(); i += 4) {
      rgbaColor rgb;
      rgb.r = byteData[i];
      rgb.g = byteData[i + 1];
      rgb.b = byteData[i + 2];
      rgb.a = byteData[i + 3];

      hslaColor hsl = rgb2hsl(rgb);
      HSLAPixel & pixel = imageData_[i/4];
      pixel.h = hsl.h;
      pixel.s = hsl.s;
      pixel.l = hsl.l;
      pixel.a = hsl.a;
    }

    return true;
  }
}
#+end_src

lodepng.cpp
#+begin_src cpp
#ifdef LODEPNG_COMPILE_DECODER

unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h, const unsigned char* in,
                size_t insize, LodePNGColorType colortype, unsigned bitdepth)
{
  unsigned char* buffer;
  unsigned error = lodepng_decode_memory(&buffer, &w, &h, in, insize, colortype, bitdepth);
  if(buffer && !error)
  {
    State state;
    state.info_raw.colortype = colortype;
    state.info_raw.bitdepth = bitdepth;
    size_t buffersize = lodepng_get_raw_size(w, h, &state.info_raw);
    out.insert(out.end(), &buffer[0], &buffer[buffersize]);
    lodepng_free(buffer);
  }
  return error;
}

unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h,
                const std::vector<unsigned char>& in, LodePNGColorType colortype, unsigned bitdepth)
{
  return decode(out, w, h, in.empty() ? 0 : &in[0], (unsigned)in.size(), colortype, bitdepth);
}

unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h,
                State& state,
                const unsigned char* in, size_t insize)
{
  unsigned char* buffer = NULL;
  unsigned error = lodepng_decode(&buffer, &w, &h, &state, in, insize);
  if(buffer && !error)
  {
    size_t buffersize = lodepng_get_raw_size(w, h, &state.info_raw);
    out.insert(out.end(), &buffer[0], &buffer[buffersize]);
  }
  lodepng_free(buffer);
  return error;
}

unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h,
                State& state,
                const std::vector<unsigned char>& in)
{
  return decode(out, w, h, state, in.empty() ? 0 : &in[0], in.size());
}

#ifdef LODEPNG_COMPILE_DISK
unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h, const std::string& filename,
                LodePNGColorType colortype, unsigned bitdepth)
{
  std::vector<unsigned char> buffer;
  unsigned error = load_file(buffer, filename);
  if(error) return error;
  return decode(out, w, h, buffer, colortype, bitdepth);
}
#endif /* LODEPNG_COMPILE_DECODER */
#endif /* LODEPNG_COMPILE_DISK */
#+end_src

lodepng.h
#+begin_src cpp
#ifdef LODEPNG_COMPILE_DECODER
/*Same as lodepng_decode_memory, but decodes to an std::vector. The colortype
is the format to output the pixels to. Default is RGBA 8-bit per channel.*/
unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h,
                const unsigned char* in, size_t insize,
                LodePNGColorType colortype = LCT_RGBA, unsigned bitdepth = 8);
unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h,
                const std::vector<unsigned char>& in,
                LodePNGColorType colortype = LCT_RGBA, unsigned bitdepth = 8);
#ifdef LODEPNG_COMPILE_DISK
/*
Converts PNG file from disk to raw pixel data in memory.
Same as the other decode functions, but instead takes a filename as input.
*/
unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h,
                const std::string& filename,
                LodePNGColorType colortype = LCT_RGBA, unsigned bitdepth = 8);
#endif /* LODEPNG_COMPILE_DISK */
#endif /* LODEPNG_COMPILE_DECODER */

#ifdef LODEPNG_COMPILE_DECODER
/* Same as other lodepng::decode, but using a State for more settings and information. */
unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h,
                State& state,
                const unsigned char* in, size_t insize);
unsigned decode(std::vector<unsigned char>& out, unsigned& w, unsigned& h,
                State& state,
                const std::vector<unsigned char>& in);
#endif /*LODEPNG_COMPILE_DECODER*/
#+end_src

你看, 在 main.cpp 里面, 我们的 default constructor 会给 image_data 赋 nullptr, 给 width_ 和 height_ 赋 0, 然后我们用了 png.readFromFile("alma.png"), 然后去看这个函数的源代码, 发现这里面使用了 decode 函数  unsigned error = lodepng::decode(byteData, width_, height_, fileName); 然后后面就直接 imageData_ = new HSLAPixel[width_ * height_], 按照 c 里面的想法这里就 new 了 0 个, 因为 width_ 和 height_ 是没有办法改变的, 但是 cpp 里面有 reference, 然后我们去看 decode 的源代码, 发现确实是这样, 我们用的是 reference

但是又有一个问题, 在 PNG.cpp 里面我们使用的 decode 和 lodepng.cpp 里面任何一个 decode 函数的函数签名都不一样, 自然怀疑到 default value, 然后去看 hpp 文件, 果然如此

这里强调一点, 默认参数必须且只能在函数的首次声明中出现, 通常就是放在 .h 文件里

cs 里面没有 magic, 你以为的 magic 都是 human design

** debugging workflow

#+begin_quote
cs 225 的第二个 lab lab_debug 给出了一个很好的 debug 的方法
From: DEBUGGING: The 9 Indispensable Rules for Finding Even the Most Elusive Software and Hardware Problems by David J. Agans
#+end_quote

*** 1. Understand the System.

- Without a solid understanding of the system (the system defined as being both the actual machine you are running on as well as the general structure behind the problem you are trying to solve), you can’t begin to narrow down where a bug may be occurring. Start off by assembling knowledge of:
  - What the task is
  - What the code’s structure is
  - What the control flow looks like
  - How the program is accomplishing things (library usage, etc)
- When in doubt, look it up—this can be anything from using Google to find out what that system call does to simply reading through your lab’s code to see how it’s constructed.

*** 2. Make it Fail.

- The best way to understand why the bug is occurring is to make it happen again—in order to study the bug you need to be able to recreate it. And in order to be sure it’s fixed, you’ll have to verify that your fix works. In order to do that, you’ll need to have a reproducible test case for your bug.
- A great analogy here is to turn on the water on a leaky hose—only by doing that are you able to see where the tiny holes might be (and they may be obvious with the water squirting out of them!).
- You also need to fully understand the sequence of actions that happen up until the bug occurs. It could be specific to a certain type of input, for example, or only a certain branch of an if/else chain.

*** 3. Quit Thinking and Look.

- After you’ve seen it fail, and seen it fail multiple times, you can generally have an idea of at least what function the program may be failing in. Use this to narrow your search window initially.
- Start instrumenting your code. In other words, add things that print out intermediate values to check assumptions that should be true of variables in your code. For instance, check that that pointer you have really is set to NULL.
- Guessing initially is fine, but only if you’ve seen the bug before you attempt to fix it. Changing random lines of code won’t get you to a solution very fast, but will result in a lot of frustration (and maybe even more bugs)!

*** 4. Divide and Conquer.

- Just like you’d use binary search on an array to find a number, do this on your code to find the offending line! Figure out whether you’re upstream of downstream of your bug: if your values look fine where you’ve instrumented, you’re upstream of the bug (it’s happening later on in the code). If the values look buggy, you’re probably downstream (the bug is above you).
- Fix the bugs as you find them—often times bugs will hide under one another. Fix the obvious ones as you see them on your way to the root cause.

*** 5. Change One Thing at a Time.

- Use the scientific method here! Make sure that you only have one variable you’re changing at each step—otherwise, you won’t necessarily know what change was the one that fixed the bug (or whether or not your one addition/modification introduces more).
- What was the last thing that changed before it worked? If something was fine at an earlier version, chances are whatever you changed in the interim is what’s buggy.

*** 6. Keep an Audit Trail.

Keep track of what you’ve tried! This will prevent you from trying the same thing again, as well as give you an idea of the range of things you’ve tried changing.

*** 7. Check the Plug.

Make sure you’re assumptions are right! Things like “is my Makefile correct?” or “am I initializing everything?” are good things to make sure of before blindly assuming they’re right.

*** 8. Get a Fresh View.

- Getting a different angle on the bug will often times result in a fix: different people think differently, and they may have a different perspective on your issue.
- Also, articulating your problem to someone often causes you to think about everything that’s going on in your control flow. You might even realize what is wrong as you are trying to describe it to someone! (This happens a lot during office hours and lab sections!)
- When talking to someone, though, make sure you’re sticking to the facts: report what is happening, but not what you think might be wrong (unless we’re asking you what you think’s going on).

*** 9. If you didn’t fix it, it ain’t fixed.

When you’ve got something you think works, test it! If you have a reproducible test case (you should if you’ve been following along), test it again. And test the other cases too, just to be sure that your fix of the bug didn’t break the rest of the program.

** debug 常用操作

可以使用 __LINE__ macro 来实现打印当前行, 然后根据 [[https://zhuanlan.zhihu.com/p/1905773368868865384][南京大学蒋炎岩: 副教授实名举报计算机专业学生编程水平不如小学生]] 里面的 super 小学生提供的办法 ( 汗颜, ece大二下了, 对 preprocess 和 gcc 的熟悉程度确实还不如小学生 ), 我们可以形成如下的调试办法:

#+begin_src cpp
// debug log
#ifdef DEBUG_ON
#define LOG(...) std::cout << "Line [" << __LINE__ << "]: " << __VA_ARGS__ << std::endl
#else
#define LOG(...) do {} while (0)
#endif
#+end_src

然后我们只需要在编译的时候加入一个 flag -DDEBUG_ON:

#+begin_src bash
gcc -DDEBUG_ON xxxx.c -o xxxx
#+end_src

gcc 里面的 -D 表示 define, 当然还有些在 gcc 里面 #include 文件的办法, 这里暂时就不写了, 下面展现一下如何使用 makefile 来加入和不加入 DEBUG_ON 这个 flag

#+begin_src makefile
CXXFLAGS = -Wall -Werror -pedantic -g -c -O0

# some contents

# Degbug option
.PHONY: debug
debug: CXXFLAGS += -DDEBUG_ON
debug: all
#+end_src

然后你可以 make -j 表示不加入 DEBUG_ON 这个标签, 所有的 LOG() 就会被替换为 do {} while(0), 非常的安全, 啥都没有, 如果你是 make debug -j, 那么就会在 CXXFLAGS 里面加入 -DDEBUG_ON 标签, 这样就会 define 了 DEBUG_ON, 然后 LOG() 就会被替换为打印消息, 非常 nice

再次声明, ECE大二的本科生对 preprocess 和 gcc 的熟悉程度不如小学生确实是很可耻的


* quiz 1

quiz 1 是 38/40, 记录一下怎么 gg 的, 主要原因是 cpp 的语法不熟悉还有手瓢:
** 1. delete 的语法相关
delete 在删除一般的 object 的时候是不需要 delete [] object; 的, 但是在删除数组的时候需要 delete [] array; 因为 new[] 会在头部存数组的长度, 比如说
#+begin_src cpp
int *_array = new ClassName[10];
#+end_src

实际上 new 和 delete 的行为非常好玩, 还有他们底层调用的是 malloc 和 free, 我们先讲一下 malloc 的性质

malloc 不在乎类型, malloc(size_) 只会在内存里面给你 size_ 个 byte 的地址, 返回的类型是一个 void * 指针, 然后我们需要自己去进行类型转换

假设 malloc(size_) 返回的 void * 给了 ptr 这个变量, 然后在 ((char *)ptr - 8) 到 ((char *)ptr - 1) 这 8 个 byte 里面会储存 size_ + 8 这个值 ( 硬编码了向前 8 byte ), 这样 free(ptr) 的时候他就可以先进行 (char *) ptr - 8, 然后读取 (char *) ptr - 8 到 (char *) ptr - 1 这快区域里面的 size_ + 8 值, 知道要 free 多少内存区域, 然后从 (char *) ptr - 8 这个地址开始 free

其中 (char *)ptr - 8 到 (char *)ptr - 1这8 byte 叫做 chunk size, 是专门用于记录这次 malloc 的 meta data 的

值得注意的是在 (char *)ptr - 8 到 (char *)ptr - 1 这 8 byte 里面还储存了 (char *)ptr - 8 往前的内存地址是不是 in use ( PREV_INUSE )

是这样, 在现代 64 位的计算机里面我们自己分配的小的内存块必须是 16byte 的整数倍 ( 为了内存对齐, 这样的话计算起来会快很多 ), 所以我们 malloc(size_) 的时候理论上最小只需要占用 size_ + 8 个 byte, 但是为了满足内存对齐, 我们会占用 \( 16 \times \lceil \frac{\text{size} + 8}{16} \rceil \) 个 byte, 也就是说在 (char *)ptr - 8 到 (char *) ptr - 1 这 8 byte 里面存的值应该是
   \( 16 \times \lceil \frac{\text{size} + 8}{16} \rceil \) 而不是 size_t + 8, 多出来的 \( 16 \times \lceil \frac{\text{size} + 8}{16} \rceil - (\text{size} + 8) \) 个 byte 会被填充到 (char *) ptr + size_t 之后

我们实际上还需要记录比 (char *)ptr - 8 更低的地址是不是空闲, 理论上还需要更多的 byte, 但是我们发现, 因为这个内存对齐的原因, 所以 size_t 一定是 16 的倍数, 所以从 (char *)ptr - 8 到 (char *) ptr - 1 这 8 byte 里面最低的三位一定是0, 所以我们可以用这三位来记录比 (char *)ptr - 8 更低的地址的状态, 在我的 ubuntu24.04 上面, 我们使用的是最低的那一位记录 previous 是否 in use (PREV_INUSE), 如果最低位是0, 代表并不是 in use, 如果是 1, 代表 in use

然后再说 new 和 delete

如果是 new 一个 int/float/double 这样的基本类型, 或者是 new 一个 int[size]/float[size]/double[size] 这样基本类型的数组的话, 他的行为基本是跟 malloc 一致的 ( 实际上 new 函数就是在调用底层的 malloc ), 理论上我们 free 就行了, 理是这个理, 但是实际上会出问题, 我们等一下看

如果是 new 一个 class 的 instance 的话, new 函数的做法实际上是:
1. 先调用 malloc, ClassType *ptr = malloc(sizeof(ClassType));
2. 在 ptr 指向的地址上调用 ClassType 的 constructor
3. 返回 ptr

我们可以看出, 这个东西只是多了一个调用构造函数, 和 malloc 并没有实质的区别, delete 实际上就是 调用 destructor 然后最后 free

注意, 这里 free 之前需要调用 destructor 的原因是该 object 可能有一些指针或者数组作为成员, 我们需要释放这些资源, 直接 free 这片内存会导致 memory leakage

但是在 new ClassName[size] 的时候就出问题了, 因为根据上面的解释, 我们并不知道有几个 object, 换句话说 delete 不知道要调用几次 destructor 释放资源之后才能用 free, 所以我们有多了一个 cookie, 就是说 new ClassName 实际上做的是:
1. ClassType *ptr = malloc(sizeof(ClassType) * size + 8) + 8;
2. for i in range(0, size), 对 (ptr + i) 进行调用 constructor
3. 返回 ptr然后

我们注意到, 这里多 malloc 了 8 byte ( 叫做 cookie ), 这 8 byte 里面存储了 size 这个值, 这样我们 delete 的时候就可以根据 cookie 里面存的值来调用 destructor, 这个操作要求的语法是 delete []

好了, 我们来 gdb 一下, 我们检查如下的 verify.cpp 文件
#+begin_src cpp
#include <iostream>
#include <cstdlib>

class Widget {
public:
    int data;
    Widget() { data = 0x11111111; }
    ~Widget() { std::cout << "Destructor of Widget called" << std::endl; }
};

class Trivial {
public:
    int data;
    Trivial() { data = 0x22222222; }
    // 注意：这里没有析构函数
};

int main() {
    // 1. 验证 malloc
    void* m = std::malloc(40); // 申请 40 字节

    // 2. 验证 new 单个对象
    Widget* p_single = new Widget();

    // 3. 验证 new[] 数组 (带析构函数)
    Widget* p_array = new Widget[10];

    // 4. 验证 new[] 数组 (标准类型/无析构函数)
    int* p_int = new int[10];
    Trivial* p_trivial = new Trivial[10];

    // 作为断点
    std::cout << "Address m:       " << m << std::endl;
    std::cout << "Address p_array: " << p_array << std::endl;
    std::cout << "Address p_array: " << p_array << std::endl;

    delete[] p_array; // 验证析构调用
    return 0;
}
#+end_src

然后我们编译, 然后 gdb 进去看看;

#+begin_src bash
(base) zhb:~/Desktop$ g++ -g verify.cpp -o verify
(base) zhb:~/Desktop$ gdb ./verify
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./verify...
(gdb) break main
Breakpoint 1 at 0x121a: file verify.cpp, line 20.
(gdb) run
Starting program: /home/zhb/Desktop/verify

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc3000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at verify.cpp:20
20	    void* m = std::malloc(40); // 申请 40 字节
(gdb) n
23	    Widget* p_single = new Widget();
(gdb) print m
$1 = (void *) 0x55555556b2b0
(gdb) x/8bx (char *)m - 8
0x55555556b2a8:	0x31	0x00	0x00	0x00	0x00	0x00	0x00	0x00
(gdb) n
26	    Widget* p_array = new Widget[10];
(gdb) n
29	    int* p_int = new int[10];
(gdb) n
30	    Trivial* p_trivial = new Trivial[10];
(gdb) n
33	    std::cout << "Address m:       " << m << std::endl;
(gdb) print p_array
$2 = (Widget *) 0x55555556b308
(gdb) x/16bx (char *)p_array - 16
0x55555556b2f8:	0x41	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x55555556b300:	0x0a	0x00	0x00	0x00	0x00	0x00	0x00	0x00
(gdb) print p_single
$3 = (Widget *) 0x55555556b2e0
(gdb) x/16bx (char *)p_single - 16
0x55555556b2d0:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x55555556b2d8:	0x21	0x00	0x00	0x00	0x00	0x00	0x00	0x00
(gdb) print p_int
$4 = (int *) 0x55555556b340
(gdb) x/16bx (char *)p_int - 16
0x55555556b330:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x55555556b338:	0x31	0x00	0x00	0x00	0x00	0x00	0x00	0x00
(gdb) print p_trivial
$5 = (Trivial *) 0x55555556b370
(gdb) x/16bx (char *)p_trivial - 16
0x55555556b360:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x55555556b368:	0x31	0x00	0x00	0x00	0x00	0x00	0x00	0x00
(gdb) n
Address m:       0x55555556b2b0
34	    std::cout << "Address p_single:" << p_single << std::endl;
(gdb) n
Address p_single:0x55555556b2e0
35	    std::cout << "Address p_array: " << p_array << std::endl;
(gdb) n
Address p_array: 0x55555556b308
36	    std::cout << "Address p_int:   " << p_int << std::endl;
(gdb) n
Address p_int:   0x55555556b340
38	    delete[] p_array; // 验证析构调用
(gdb) n
Destructor of Widget called
Destructor of Widget called
Destructor of Widget called
Destructor of Widget called
Destructor of Widget called
Destructor of Widget called
Destructor of Widget called
Destructor of Widget called
Destructor of Widget called
Destructor of Widget called
39	    return 0;
(gdb) q
A debugging session is active.

	Inferior 1 [process 67767] will be killed.

Quit anyway? (y or n) y
(base) zhb:~/Desktop$
#+end_src

完美验证, 之所以都是 0x21 和 0x31 是因为内存对齐, 那个 1 是作为状态位检查更低地址的内存是不是 in use

我们看见了 new 一个 object 在内存布局上实际上跟 malloc 并没有什么实际区别 ( 都是 8 byte 的 chunk size ), 但是 new 一个 ClassName 的数组的时候, 我们可以看见两个数字, 一个就是 array 的 object, 也就是对 p_array 里面输出的 0x0a, 然后也可以观察到, int array, single object, 还有没有 destructor 的 object array 都是没有 cookie 的, 这个也符合之前的分析

但是是不是 int array 就可以用 delete 而不是 delete [] 呢? 并不是这样, 即使按照分析是这样, 下面给出一个例子

#+begin_src cpp
int main() {
	int *arr = new int[3];
        delete arr;
	return 0;

}
#+end_src

从内存布局的理论上来说, 用 delete 或者 free 才是对的, 但是可以试一下
#+begin_src cpp
#include<cstdlib>

int main() {
	int *arr = new int[3];
        delete arr;
	return 0;

}
#+end_src

运行, 发现内存泄漏, 说明有点问题

#+begin_src bash
(base) zhb:~/Desktop$ g++ test.cpp -g
(base) zhb:~/Desktop$ valgrind --leak-check=full ./a.out
==68169== Memcheck, a memory error detector
==68169== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==68169== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==68169== Command: ./a.out
==68169==
==68169== Mismatched free() / delete / delete []
==68169==    at 0x484988F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==68169==    by 0x10918E: main (test.cpp:5)
==68169==  Address 0x4e2d080 is 0 bytes inside a block of size 12 alloc'd
==68169==    at 0x48485C3: operator new[](unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==68169==    by 0x10917E: main (test.cpp:4)
==68169==
==68169==
==68169== HEAP SUMMARY:
==68169==     in use at exit: 0 bytes in 0 blocks
==68169==   total heap usage: 2 allocs, 2 frees, 73,740 bytes allocated
==68169==
==68169== All heap blocks were freed -- no leaks are possible
==68169==
==68169== For lists of detected and suppressed errors, rerun with: -s
==68169== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
(base) zhb:~/Desktop$
#+end_src

再用 delete 而不是 delete[] 试一下
#+begin_src
(base) zhb:~/Desktop$ g++ test.cpp -g
(base) zhb:~/Desktop$ valgrind --leak-check=full ./a.out
==68262== Memcheck, a memory error detector
==68262== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==68262== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==68262== Command: ./a.out
==68262==
==68262== Mismatched new/delete size value: 4
==68262==    at 0x484A5B9: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==68262==    by 0x109198: main (test.cpp:5)
==68262==  Address 0x4e2d080 is 0 bytes inside a block of size 12 alloc'd
==68262==    at 0x48485C3: operator new[](unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==68262==    by 0x10917E: main (test.cpp:4)
==68262==
==68262== Mismatched free() / delete / delete []
==68262==    at 0x484A61D: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==68262==    by 0x109198: main (test.cpp:5)
==68262==  Address 0x4e2d080 is 0 bytes inside a block of size 12 alloc'd
==68262==    at 0x48485C3: operator new[](unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==68262==    by 0x10917E: main (test.cpp:4)
==68262==
==68262==
==68262== HEAP SUMMARY:
==68262==     in use at exit: 0 bytes in 0 blocks
==68262==   total heap usage: 2 allocs, 2 frees, 73,740 bytes allocated
==68262==
==68262== All heap blocks were freed -- no leaks are possible
==68262==
==68262== For lists of detected and suppressed errors, rerun with: -s
==68262== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
(base) zhb:~/Desktop$
#+end_src

看, 还是有问题, 这个跟现代 cpp 标准要求一定是 delete[] 有关, 这个是个 UB, 发生了什么我也不知道, 暂时也没有兴趣研究了, 就这样吧

好了, 无论怎么说, 现在应该已经掌握了什么时候用 delete 什么时候用 delete [] 了 🤪

** 2. 关于 cpp 函数传参的默认值
cpp 里面, 在 .h 文件里声明的时候要给默认参数赋值, 在 .cpp 文件里不需要且不能对对应的参数给默认值, cpp 语法里面默认值只能给一次 ( 给了两次会报错 ), 而且为了其他用这个函数的文件也能知道这个函数的某一个参数有默认值, 必须写在 .h 文件里, 这个在之前的某次实验里面提到过了

** 3. 小糖人错误:
1. memory leakage 写成了 memry leakage
2. 写两个 for 循环嵌套, 判断条件里第一个 x <= c1 写对了, 第二个 y <= c2 的小于等于写成了数学的小于等于, 没招了


* lecture 07

这里我们讲一下 inheritance, polymorphism, virtual function, pure virtual function, abstract class 之类相关的东西

顺便一提, zjui 的课水的不能再水了, 不知道他在上什么东西, 首先一下子就从 lecture 04 跳到了 lecture 07, 其次一节课只是非常简单的讲解了一下 inheritance 相关的东西, 没有上手 coding, 没有调试, 就对着 ppt 干讲, 不像 uiuc 的教授, 好歹会放个 gdb 调试结果或者代码运行结果, 真的无语了, 我觉得编程课你总得写点代码然后当场调试吧, 而且讲课讲的超级超级无敌浅

好了, 下面开始讲 inheritance 吧, inheritance 的意思就是 derive one class from another class, 主要内容分为 data 的继承还有 member function 的继承

** 1. inheritance: 继承 data
inheritance 分成 data 的继承, 还有 member function 的继承, 我们先讲比较简单的数据的继承, 当我们从 father class 继承的时候, 我们做的实际上是直接先把 father class 的 data 全都拿过来, 然后再在 father class 的 data 的后面分配 child class 的 data, 具体例子如下:

#+begin_src cpp
#include <iostream>

class Base {
      public:
        Base(int base_val) : base_val_(base_val) {}
        int base_val_;
};

class Derived : public Base {
      public:
        Derived(int base_val, int der_val)
            : Base(base_val), der_val_(der_val) {}
        int der_val_;
};

int main() {
        Base base = Base(1);
        Derived der = Derived(1, 2);
	std::cout << base.base_val_ << std::endl;
        return 0;
}
#+end_src

#+begin_src bash
(base) zhb:~/Desktop$ g++ -g test.cpp -o test
(base) zhb:~/Desktop$ gdb ./test
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test...
(gdb) break main
Breakpoint 1 at 0x1195: file test.cpp, line 16.
(gdb) run
Starting program: /home/zhb/Desktop/test

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc3000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at test.cpp:16
16	int main() {
(gdb) n
17	        Base base = Base(1);
(gdb) n
18	        Derived der = Derived(1, 2);
(gdb) n
19		std::cout << base.base_val_ << std::endl;
(gdb) print &base
$1 = (Base *) 0x7fffffffdeec
(gdb) print sizeof(Base)
$2 = 4
(gdb) print &der
$3 = (Derived *) 0x7fffffffdef0
(gdb) print sizeof(Derived)
$4 = 8
(gdb) x/4bx (char *) (&base)
0x7fffffffdeec:	0x01	0x00	0x00	0x00
(gdb) x/8bx (char *) (&der)
0x7fffffffdef0:	0x01	0x00	0x00	0x00	0x02	0x00	0x00	0x00
(gdb) q
A debugging session is active.

	Inferior 1 [process 73197] will be killed.

Quit anyway? (y or n) y
#+end_src

看这里, Base class 的大小就是 int, 即 4 byte, Derived class 的大小就是两个 int, 即 8 byte

然后你看这里, base 的地址是 0x7fffffffdeec, 然后往后的 4 byte 是 0x01	0x00	0x00	0x00, 也就是我们给的值 1
然后 der 的地址是 0x7fffffffdef0, 刚好是 0x7fffffffdeec 往后 4 byte, 然后他的大小是 8 byte
0x7fffffffdeec:	0x01	0x00	0x00	0x00	0x02	0x00	0x00	0x00
可见在内存里面是先放了 1 (Base class 的 data), 然后再放了 2 (Derived class 的 data)

然后我们可以看见, 这里是在初始成员列表里面调用了 base class 的 constructor, 还有 initialization list, 这个跟我们之前的理解是一致的:
1. 分配内存
2. 执行 constructor initializer list 的相关内容 ( 只能在 initializer list 的地方干预, 否则就是执行每一个东西的默认的初始化 )
3. 执行构造函数体 {}
这里先分配内存, 然后执行 initialization list 里面的内容, 因为 base class 的 data 在最前面, 所以我们需要先调用 base class 的 constructor, 然后再是本 class 的 member 的 initialization list

然后注意到, 继承的语法是这样的:
#+begin_src cpp
class Derived : public Base {
                /* balabalabala */
}
#+end_src
这里有一个 public, 我们先回顾一下 cpp 里面的 public, private, protected 分别是什么意思, 如果写:
#+begin_src cpp
class ClassType {
        public:
                /* some code */
        private:
                /* some code */
        protected:
                /* some code */
};
#+end_src
首先, public, private, protected 这些东西在内存上是没有区别的, 他只是在给编译器一个指令, 在编译的时候检查访问权限, 其中:
public: 所有东西都能访问, 包括但不限于本 class 内部的 member function, 本 class 外部的 function 或者任何操作, 还有继承本 class 的 child class 可以访问
private: 除了本 class 内部的 member function, 其他任何东西都不能访问
protected: 只有本 class 内部的 member function 还有本 class 的 child class 可以访问

上面是针对一个 class 的内部区域的标记, 同时, 我们继承一个 class 的时候可以选择 public 继承, private 继承, 还有 protected 继承, 无论怎么继承, child class 都会继承 father class 的所有 data ( 包括 public 的部分, private 的部分, protected 的部分 ), 只不过对应类型会有所变化
#+begin_src cpp
class ClassType {
        public:
                uint32_t pub_member_;
        private:
                uint32_t pri_member_;
        protected:
                uint32_t pro_member_;
};

class Derived1 : public ClassType {
                /* some code */
};

class Derived2: protected ClassType {
                /* some code */
};

class Derived3 private ClassType {
        /* some code */
};
#+end_src
不论 Derived1, Derived2, Derived3, 都会继承 ClassType 的所有数据成员 ( 在这里, 即 pub_member_, pri_member_, pro_member_ ), 只不过随着你继承方式的不同, child class 对 father class 对 data 在编译的时候可见于不可见不同, 但是这不意味着内存里面没有 father class 的数据成员, 具体总结如下:

|--------------------------+------------------------------------+----------------------------------+---------------------------|
| father class 的 data     | public 的 pub_member_              | protected 的 pro_member_         | private 的 pri_member_    |
|--------------------------+------------------------------------+----------------------------------+---------------------------|
| public 继承的 Derived1    | 可见, 仍为 Derived1 的 punlic       | 可见, 仍为 Derived1 的 protected  | 不可见不可访问, 但是内存仍存在 |
|--------------------------+------------------------------------+----------------------------------+---------------------------|
| protected 继承的 Derived2 | 可见, 但是变成 Derived2 的 protected | 可见, 还是 Derived2 的 protected  | 不可见不可访问, 但是内存仍存在 |
|--------------------------+------------------------------------+----------------------------------+---------------------------|
| provate 继承的 Derived3   | 可见, 但是变成 Derived3 的 private   | 可见, 但是变成 Derived3 的 private | 不可见不可访问, 但是内存存在  |
|--------------------------+------------------------------------+----------------------------------+---------------------------|

物理现实是 child class 容纳了 father class 的所有 data member, 但是语法上你如果通过 child class 去访问 father class 的 private member, 编译器会报错, 这个只是因为编译器在检查, 不代表内存里面没有这个东西

我们下面写个小 demo 来演示一下我们上面介绍的继承成员的规则:

#+begin_src cpp demo.cpp
#include <iostream>

class Base {
private:
    int private_val = 0xA1A1A1A1; // 私有，子类不可见
protected:
    int protected_val = 0xB2B2B2B2;
public:
    int public_val = 0xC3C3C3C3;
};

class Derived1 : public Base {
public:
    int child_val = 0xD4D4D4D4;
};

class Derived2 : public Base {
public:
    int child_val = 0xE5E5E5E5;
};

class Derived3 : public Base {
public:
    int child_val = 0xF6F6F6F6;
};

int main() {
    Derived1 der1;
    Derived2 der2;
    Derived3 der3;
    Base base;
    return 0;
}
#+end_src

编译, 然后 gdb 进去看一下:

#+begin_src bash
(base) zhb:~/Desktop$ g++ -g demo.cpp -o demo
(base) zhb:~/Desktop$ gdb ./demo
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./demo...
(gdb) break main
Breakpoint 1 at 0x1155: file demo.cpp, line 27.
(gdb) run
Starting program: /home/zhb/Desktop/demo

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc3000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at demo.cpp:27
27	int main() {
(gdb) n
28	    Derived1 der1;
(gdb) n
29	    Derived2 der2;
(gdb) n
30	    Derived3 der3;
(gdb) n
31	    Base base;
(gdb) n
32	    return 0;
(gdb) print sizeof(Derived1)
$1 = 16
(gdb) print sizeof(Base)
$2 = 12
(gdb) x/16xb (char *)(&der1)
0x7fffffffdec0:	0xa1	0xa1	0xa1	0xa1	0xb2	0xb2	0xb2	0xb2
0x7fffffffdec8:	0xc3	0xc3	0xc3	0xc3	0xd4	0xd4	0xd4	0xd4
(gdb) x/16xb (char *)(&der2)
0x7fffffffded0:	0xa1	0xa1	0xa1	0xa1	0xb2	0xb2	0xb2	0xb2
0x7fffffffded8:	0xc3	0xc3	0xc3	0xc3	0xe5	0xe5	0xe5	0xe5
(gdb) x/16xb (char *)(&der3)
0x7fffffffdee0:	0xa1	0xa1	0xa1	0xa1	0xb2	0xb2	0xb2	0xb2
0x7fffffffdee8:	0xc3	0xc3	0xc3	0xc3	0xf6	0xf6	0xf6	0xf6
(gdb) x/12xb (char *)(&base)
0x7fffffffdeb4:	0xa1	0xa1	0xa1	0xa1	0xb2	0xb2	0xb2	0xb2
0x7fffffffdebc:	0xc3	0xc3	0xc3	0xc3
(gdb) q
A debugging session is active.

	Inferior 1 [process 73890] will be killed.

Quit anyway? (y or n) y
#+end_src

你看, 正如我们所介绍的, child class 是会继承 parent class 的所有 member 的, 只是编译的时候 parent class 的 public, protected, private 区域和 child class 的 public, protected, private 继承方式决定了编译的时候检查访问权限的不同, 但是没有访问权限不代表这个东西不存在, 编译错误只是代表编译器根据语法不同意你访问

** 2. inheritance: 继承 member function
*** (1) this 指针和 cpp 里的 member function

要搞清楚 cpp 里面的 member function 是怎么回事, 我们就必须搞清楚 cpp 里面的函数是怎么调用的

#+begin_src cpp
class ClassType {
        public:
                uint32_t member_;
                uint64_t get_member(void);
        private:
                uint64_t private_member_;
}
#+end_src

对于上述 class 的 object, 我们如果打印出他的 size 的话, 我们会发现只有 4 + 8 = 12 byte, 也就是说, object 在内存上实际上只保留了数据而没有保留 member function, member function 是作为一般函数被放在 .text 段而不是跟 object 一样被放在 heap 或者 stack 上面, obj.get_member() 这个函数实际上被编译成了类似 uint64_t get_member(ClassType *obj) 这样的形式, 换句话说, 所有的 member function 在编译的时候都会多一个类型为本class的指针作为参数, 然后当我们 obj.member_func() 的时候, 编译器实际上隐式的把我们的 obj 的地址传入了 .text 段段函数里作为第一个参数, 这个效果相当于 c 语言里的

#+begin_src c
struct ClassType {
        uint32_t member_;
        uint64_t private_member_; // 这里访问权限没有办法
};

uint64_t get_member(struct ClassType *obj) {
        return obj->private_member_;
}
#+end_src

然后传入的第一个参数就是 this 指针

但是好玩的是, 我们 print sizeof(ClassType) 的时候会发现 this 指针根本就不存在 object 的内存里面, 确实, 这个是运行时存在 register 里面由计算机传递给 member function 的

*** (2) 静态绑定, 同名函数的 hide

比如 parent class 有一个没有标记 virtual 的 func 函数, child class 也命名了一个叫做 func 的同名函数, 编译器在调用函数时只看指针或引用的类型而不看内存里对象的实际类型

#+begin_src cpp hide.cpp
#include <iostream>

class Base {
public:
    void show() { std::cout << "Base::show\n"; }
};

class Derived : public Base {
public:
    // 隐藏了 Base::show
    void show() { std::cout << "Derived::show\n"; }
};

int main() {
    Derived d;
    Base& b_from_d = d;

    Base b;
    Derived& d_from_b = b;

    d.show();
    b_from_d.show();
    b.show();
    d_from_b.show();
}
#+end_src

这里发现是编译错误:
#+begin_src
(base) zhb:~/Desktop$ g++ -g hide.cpp -o hide
hide.cpp: In function ‘int main()’:
hide.cpp:19:25: error: invalid initialization of reference of type ‘Derived&’ from expression of type ‘Base’
   19 |     Derived& d_from_b = b;
      |                         ^
(base) zhb:~/Desktop$
#+end_src
我们会发现这里编译错误了, 注意只能使用 child class 去 initialize father class, 而不能使用 father class 的 obj 去初始化 child class 的 obj

修正之后:
#+begin_src cpp
#include <iostream>

class Base {
public:
    void show() { std::cout << "Base::show\n"; }
};

class Derived : public Base {
public:
    // 隐藏了 Base::show
    void show() { std::cout << "Derived::show\n"; }
};

int main() {
    Derived d;
    Base& b_from_d = d;
    Derived& d_from_d = d;

    d.show();
    b_from_d.show();
    d_from_d.show();
}
#+end_src

编译然后运行:

#+begin_src bash
(base) zhb:~/Desktop$ g++ -g hide.cpp -o hide
(base) zhb:~/Desktop$ ./hide
Derived::show
Base::show
Derived::show
#+end_src

这里 Derived class 的 member function 会把 Base class 的同名 member funcion 隐藏 ( d 调用的是 Derived class 的 member function, 隐藏了 Base class 的同名 member function ), 但是可以看见, 编译器在这里只认调用 member function 的 object 的 type, 什么 type 就调用什么 type 对应的 member function, 比如 b_from_d 即使是用了 d 进行初始化, 还是调用了 Base class 的 member function, 这叫静态绑定 ( Static Binding )函数地址在编译阶段就填好了

这里是有点 tricky 的, 看一下最后补档里面的 comprehensive example, 这里会把什么时候静态绑定, 什么时候走 vtable 讲述的很清楚

*** (3) about virtual function

在没有 virtual 的情况下, 函数调用是静态绑定的, 编译器在编译时看到 p->func() 会直接根据 p 的指针类型 ( 比如 Base* )跳转到 Base::func 的地址执行

当你加上 virtual 关键字编译器会做两件事:
1. 生成虚表 (vtable): 为这个类专门开辟一块内存 ( 在 .rodata 段 ), 里面按顺序存着该类所有虚函数的地址
2. 注入虚表指针 (vptr): 在对象的内存首部增加一个 8 字节的指针, 指向上述的虚表

此时 p->func() 不再是直接跳转到 func 对应的地址, 而变成了p->vptr -> vtable -> func_address -> 执行, 这个就是动态绑定

注意, 这里是每个 class 都生成自己对应的一个 vtable, 比如说 class Base, 还有 class Derived : public Base, 那么 Base 和 Derived 都有一张自己的 vtable

#+begin_src cpp virtual.cpp
#include<iostream>

class Base {
public:
    int member1_ = 1;
    int member2_ = 2;
    virtual void f1() { std::cout << "Base::f1\n"; }
    virtual void f2() { std::cout << "Base::f2\n"; }
};

class Derived : public Base {
public:
    int der_member1_ = 3;
    int der_member2_ = 4;
    void f1() override { std::cout << "Derived::f1\n"; }
    // 没有重写 f2
};

int main() {
        Derived d;
        Base b;
        Base &b_from_d = d;

        d.f1();
        d.f2();
        b.f1();
        b.f2();
        b_from_d.f1();
        b_from_d.f2();

        return 0;
}
#+end_src

然后编译执行:

#+begin_src bash
(base) zhb:~/Desktop$ g++ -g virtual.cpp -o virtual
(base) zhb:~/Desktop$ ./virtual
Derived::f1
Base::f2
Base::f1
Base::f2
Derived::f1
Base::f2
#+end_src

再深入的 gdb 进去看一下
#+begin_src bash
(base) zhb:~/Desktop$ g++ -g virtual.cpp -o virtual
(base) zhb:~/Desktop$ gdb ./virtual
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./virtual...
(gdb) break main
Breakpoint 1 at 0x1175: file virtual.cpp, line 19.
(gdb) run
Starting program: /home/zhb/Desktop/virtual

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc3000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at virtual.cpp:19
19	int main() {
(gdb) n
20	        Derived d;
(gdb) n
21	        Base b;
(gdb) n
22	        Base &b_from_d = d;
(gdb) n
24	        d.f1();
(gdb) n
Derived::f1
25	        d.f2();
(gdb) n
Base::f2
26	        b.f1();
(gdb) n
Base::f1
27	        b.f2();
(gdb) n
Base::f2
28	        b_from_d.f1();
(gdb) n
Derived::f1
29	        b_from_d.f2();
(gdb) n
Base::f2
31	        return 0;
(gdb) print sizeof(Base)
$1 = 16
(gdb) print sizeof(Derived)
$2 = 24
(gdb) x/16bx (char *)(&b)
0x7fffffffded0:	0x78	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
0x7fffffffded8:	0x01	0x00	0x00	0x00	0x02	0x00	0x00	0x00
(gdb) x/24bx (char *)(&d)
0x7fffffffdee0:	0x58	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
0x7fffffffdee8:	0x01	0x00	0x00	0x00	0x02	0x00	0x00	0x00
0x7fffffffdef0:	0x03	0x00	0x00	0x00	0x04	0x00	0x00	0x00
(gdb) x/16bx (char *)(&b_from_d)
0x7fffffffdee0:	0x58	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
0x7fffffffdee8:	0x01	0x00	0x00	0x00	0x02	0x00	0x00	0x00
(gdb) x/24bx (char *)(&b_from_d)
0x7fffffffdee0:	0x58	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
0x7fffffffdee8:	0x01	0x00	0x00	0x00	0x02	0x00	0x00	0x00
0x7fffffffdef0:	0x03	0x00	0x00	0x00	0x04	0x00	0x00	0x00
#+end_src


注意到这里我们刻意让 sizeof(Base) 为 16 byte, sizeof(Derived) 为 24 byte, 这样是为了避免自动填充影响教学, cpp 里面对于 class 大小的规则是: 类的大小必须是其 "最宽基本类型成员" 大小的整数倍, 比如这里 Derived 是 24 byte, 其最宽的基本类成员是 vptr, 也就是 8 byte, 24 byte 是 8 byte 的整数倍, 所以不需要填充, 这里 Base 是 16 byte, 最宽的基本类成员也是 vptr, 也不需要填充, 但是如果我们把 Base 给变成 12 byte 的理论大小 ( 比如说只有一个 int 作为 member data ), 那这样的话 sizeof(Base) 的输出还是 16 byte, 这个是因为 12 不是 vptr 8 byte 的整数, 要填充

然后我们看, Base 和 Derived 的前 8 byte 都是 vptr, 指向的是 Base class 的 vtable 和 Derived class 的 vtable, 然后后面储存的是 Base 和 Derived class 里面的数据
Base object b 的 vptr 是 0x7fffffffded0:	0x78	0x7d	0x55	0x55	0x55	0x55	0x00	0x00, 即 0x0000555555557d78
Derived object d vptr 是 0x7fffffffdee0:	0x58	0x7d	0x55	0x55	0x55	0x55	0x00	0x00, 即 0x0000555555557d58
然后
这两个值指向的是 class Base 和 class Derived 的 vtable, 注意到这是两个 vtable, 然后 vtable 里面存储的是 function pointer, 即 .text 段里面的函数实现, 等下我们可以把 vtable 的东西打印出来看看
然后 Base object b 后面紧跟着的 member1_ 和 member_2, 即 0x01 和 0x02, 然后 Derived class 后面紧跟着的是 Base class 的两个 member: member1_ = 0x01, member2_ = 0x02, 然后是 Derived class 的 member data: der_member1_ = 0x03, der_member2_ = 0x04, 完美

好, 我们继续下去, 看看这个 vptr 里面到底是啥:
#+begin_src bash
(gdb) x/2a 0x555555557d78
0x555555557d78 <_ZTV4Base+16>:	0x555555555242 <_ZN4Base2f1Ev>	0x55555555526e <_ZN4Base2f2Ev>
(gdb) x/2a 0x555555557d58
0x555555557d58 <_ZTV7Derived+16>:	0x55555555529a <_ZN7Derived2f1Ev>	0x55555555526e <_ZN4Base2f2Ev>
#+end_src

x/2a 指令是 x: examine, 查看内存内容, 2: 表示读取两个word (两个 8 byte), a: 表示把读取到的内容识别为地址, 在 64 位机上它会自动读取 8 byte, 并尝试在符号表 ( Symbol Table ) 里找这个地址对应的函数名

这里 0x555555557d78 是 Base class 的 vtptr 的值, 然后往后读 2 x 8 = 16 byte, 读到的东西是 0x555555555242 <_ZN4Base2f1Ev> 和 0x55555555526e <_ZN4Base2f2Ev>, 也就是 Base class 的 f1 function 和 f2 function 的地址 ( 函数被编译完之后存在 .text 段 )
0x555555557d58 是 Derived class 的 vptr 的值, 往后读 16 byte, 读到的东西是 0x55555555529a <_ZN7Derived2f1Ev> 和 0x55555555526e <_ZN4Base2f2Ev>, 也就是 Derived class 的 f1 ( 重写了 Base class 的 f1 ), 以及注意, 这里是 0x55555555526e <_ZN4Base2f2Ev>, 也就是 Base class 的 f2 function

因为我们在 Derived class 里面没有重写 Base class 的 virtual function f2, 所以这里还是用的 Base class 的 f2 function, 这个也就是为什么 d.f2() 会得到 Base::f2 这个输出的原因

至于为什么 Base &b_from_d = d; 然后 b_from_d.f1() 输出的是 Derived 的 f1, 这个是因为我们看 b_from_d 的 vptr, 发现他跟 d 的 vptr 完全一样, 从底层来讲, 他自然而然就是会跟 Derived class 的 object 会有一摸一样的表现, 如果从 cpp 的语法上来说的话, reference 只是给一个 alias, 他指向的就是 Derived class 的 object d 的内存, 或者说, b_from_d 和 d 是同一个东西! 我们可以看一下:

#+begin_src bash
(gdb) print &d
$3 = (Derived *) 0x7fffffffdee0
(gdb) print &b_from_d
$4 = (Base *) 0x7fffffffdee0
(gdb)
#+end_src

只是类型不一样罢了, 但是地址是一摸一样的, 一摸一样

我们还能观察到, Base class object b 的 vptr 指向的地址是 0x0000555555557d78, Derived class object d 的 vptr 指向的地址是 0x0000555555557d58, 中间刚好差了 2 x 16 = 32 bytes, 注意到我们的 machine 是每个地址 8 byte, 如果只是存了两个函数的地址的话, 应该只要 2 x 8 = 16 byte, 但是中间隔了 32 byte, 这个是为什么呢? 我们可以打印出来看一下:

#+begin_src bash
(gdb) x/64bx (char *)(0x555555557d58)
0x555555557d58 <_ZTV7Derived+16>:	0x9a	0x52	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d60 <_ZTV7Derived+24>:	0x6e	0x52	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d68 <_ZTV4Base>:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x555555557d70 <_ZTV4Base+8>:	0xa0	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d78 <_ZTV4Base+16>:	0x42	0x52	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d80 <_ZTV4Base+24>:	0x6e	0x52	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d88 <_ZTI7Derived>:	0xe8	0xeb	0xe6	0xf7	0xff	0x7f	0x00	0x00
0x555555557d90 <_ZTI7Derived+8>:	0x28	0x60	0x55	0x55	0x55	0x55	0x00	0x00
#+end_src

这里我们可以看到

然后我们仔细研究一下这两个 vptr, 我们发现 Base class object b 的 vptr 指向的地址是 0x0000555555557d78, Derived class object d 的 vptr 指向的地址是 0x0000555555557d58, 中间刚好差了 2 x 16 = 32 bytes, 注意到我们的 machine 是每个地址 8 byte, 所以理论上如果只存了函数指针的话, 应该只有 16 byte, 这个是因为 vtable 不只是存了函数指针, linux 下一个 vtable 应该是这样的:
|--------+---------------+-------------------------------------------------------------------|
| offset | content       | description                                                       |
|--------+---------------+-------------------------------------------------------------------|
|      0 | offset_to_top | 面对多继承时到对象起始地址的偏移                                        |
|--------+---------------+-------------------------------------------------------------------|
|     +8 | typeinfo 指针 | 指向 RTTI (Run-Time Type Information), 支持 typeid 和 dynamic_cast |
|--------+---------------+-------------------------------------------------------------------|
|    +16 | vfunc1        | 第一个函数指针, 即 object 的前 8 byte 的 vptr 指向的地方                |
|--------+---------------+-------------------------------------------------------------------|
|    +32 | vfunc2        | 第二个函数指针                                                      |
|--------+---------------+-------------------------------------------------------------------|

可以 gdb 进去验证一下:
#+begin_src bash
(gdb) x/64bx (char *)(0x555555557d58) - 16
0x555555557d48 <_ZTV7Derived>:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x555555557d50 <_ZTV7Derived+8>:	0x88	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d58 <_ZTV7Derived+16>:	0x9a	0x52	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d60 <_ZTV7Derived+24>:	0x6e	0x52	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d68 <_ZTV4Base>:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x555555557d70 <_ZTV4Base+8>:	0xa0	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d78 <_ZTV4Base+16>:	0x42	0x52	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d80 <_ZTV4Base+24>:	0x6e	0x52	0x55	0x55	0x55	0x55	0x00	0x00
#+end_src

offset_to_top: 从当前 vptr 所在的地址到整个对象起始地址的偏移量, 在单继承中, Base 部分就在 Derived 对象的最开头, vptr 的位置就是对象的开头, 所以偏移量为 0, 在多继承 ( 例如 class C : public A, public B) 中, 对象 C 会有两个 vptr, 指向 B 那部分的 vptr 位于对象中间，它的 offset_to_top 就会是一个负数, 告诉编译器: " 往回退 X 字节才是这个对象的真正起点 "

typeinfo 指针: vtable 中最重要的 metadata
当你使用 typeid(obj) 或者是 dynamic_cast<Target*>(ptr) 时编译器就是通过 vptr -> vtable -> typeinfo 这条线找到这个类到底是谁
0x555555557d50 位置存的是 0x555555557d88, 而 0x555555557d88 正好是 <_ZTI7Derived> 的起点, 虚表里的这个槽位精准地指向了存储类信息的结构体

我们再看
0x555555557d88 <_ZTI7Derived>:	0xe8	0xeb	0xe6	0xf7	0xff	0x7f	0x00	0x00
0x555555557d90 <_ZTI7Derived+8>:	0x28	0x60	0x55	0x55	0x55	0x55	0x00	0x00
这两行, 这里变成了 _ZTI, 也就是 Type Info, Derived 类的类型描述符, 在 _ZTI7Derived 这个结构体里通常包含:
1. 指向父类 typeinfo 的指针 ( 这样 dynamic_cast 才能沿着继承树往上找 )
2. 指向类名字符串的指针 ( 即 _ZTS7Derived, TS 是 Type String )

#+begin_src bash
(gdb) x/s 0x555555556028
0x555555556028 <_ZTS7Derived>:	"7Derived"
#+end_src

这就是 typeid().name() 返回的东西

再往下就是更多别的 cpp 的特性了, 到这里我们已经把 inheritance 和 polymorphism 的底层实现原理看完了, there is no magic in cs, 实际上 cpp 这些特性了完全可以用 c 里面的 struct 和 function pointer 实现, 只不过要手动传递 this 指针, 手动维护 vtable, 手动储存 vptr, 仅此而已, 我们已经很清楚这些了, u1s1, 我觉得 cpp 很丑陋, 不如 c, 在 c 里面这些都是透明的, cpp 里面我们需要 gdb 进去一点一点看内存, 当然这样我们也搞得很清楚了

最后我们再干点坏事, 我们可以把 Base class object b 的 vptr 指向 Derived class 的 vtable, 然后调用 b.f1(), 我们会发现他用的是 Derived class 的 f1, 然后我们再把整个 Derived class 的 vtable 的第一个函数指针改了, 让他指向 Base class f1 这个函数的地址, 然后调用 Derived class 的 object d:
#+begin_src bash
(gdb) set *(long*)0x7fffffffded0 = 0x555555557d58
(gdb) print b.f1()
Derived::f1
$7 = void
(gdb) set *(long*)0x555555557d58 = 0x555555555242
(gdb) print d.f1()
Base::f1
$8 = void
(gdb)
#+end_src

excellent! 完全如我们所想, 我们已经在底层把 virtual function 和 polymorphism 搞得很清楚很清楚了

*** (4) pure virtual function & abstract class

我们上面已经把 virtual function 和 polymorphism 在底层搞得无比清楚了, 理解什么是 pure virtual function 和 abstruct class 就跟喝水一样简单了

从语法上讲, 在 virtual function 后面加一个 = 0 就变成了 pure virtual function, pure virtual function 是没有实现的, 他只是占个位置, 从底层上来说, pure function 所在的 vtable 的位置不是一个普通的 .text 段的函数指针, 是一个特殊的符号地址, 比如在 Linux GCC 下叫 __pure_virtual_called

只要一个 class 里面包含至少一个 pure virtual function, 他就变成了 abstract class, 编译器在编译阶段如果看到你实例化 abstract class, 他会直接报错, 原因是如果允许创建 abstract class 的 object, 那么它的 vptr 就会指向 abstract class 的 vtable, 当我们调用那个 pure virtual function 的时候程序就会跳转到 __pure_virtual_called 然后报错崩溃, 为了安全编译器从源头上禁止了这种行为

写一个小 demo 验证一下
#+begin_src cpp demo
#include <iostream>

class Shape { // abstract class
public:
    virtual void draw() = 0; // pure function
    virtual void sayHi() { std::cout << "Hi from Shape\n"; }
};

class Circle : public Shape {
public:
    void draw() override { std::cout << "Drawing Circle...\n"; }
};

int main() {
    Shape s; // 编译直接报错无法实例化
    Circle c;
    Shape* p = &c;
    p->draw();
    p->sayHi();
    return 0;
}
#+end_src

然后编译:
#+begin_src bash
(base) zhb:~/Desktop$ g++ -g demo.cpp -o demo
demo.cpp: In function ‘int main()’:
demo.cpp:15:11: error: cannot declare variable ‘s’ to be of abstract type ‘Shape’
   15 |     Shape s; // 编译直接报错无法实例化
      |           ^
demo.cpp:3:7: note:   because the following virtual functions are pure within ‘Shape’:
    3 | class Shape { // abstract class
      |       ^~~~~
demo.cpp:5:18: note:     ‘virtual void Shape::draw()’
    5 |     virtual void draw() = 0; // pure function
      |                  ^~~~
(base) zhb:~/Desktop$
#+end_src

改正之后我们编译, 然后 gdb 进去看看
#+begin_src bash
(base) zhb:~/Desktop$ g++ -g demo.cpp -o demo
(base) zhb:~/Desktop$ gdb ./demo
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./demo...
(gdb) break main
Breakpoint 1 at 0x1175: file demo.cpp, line 14.
(gdb) run
Starting program: /home/zhb/Desktop/demo

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc3000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at demo.cpp:14
14	int main() {
(gdb) n
15	    Circle c;
(gdb) n
16	    Shape* p = &c;
(gdb) n
17	    p->draw();
(gdb) n
Drawing Circle...
18	    p->sayHi();
(gdb) n
Hi from Shape
19	    return 0;
(gdb) print sizeof(Shape)
$1 = 8
(gdb) print sizeof(Circle)
$2 = 8
(gdb) x/8bx (char *)(&c)
0x7fffffffdee8:	0x78	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
(gdb) x/2a 0x0000555555557d78
0x555555557d78 <_ZTV6Circle+16>:	0x555555555208 <_ZN6Circle4drawEv>	0x5555555551dc <_ZN5Shape5sayHiEv>
(gdb) x/32bx (char *) 0x0000555555557d78 - 16
0x555555557d68 <_ZTV6Circle>:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x555555557d70 <_ZTV6Circle+8>:	0x88	0x7d	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d78 <_ZTV6Circle+16>:	0x08	0x52	0x55	0x55	0x55	0x55	0x00	0x00
0x555555557d80 <_ZTV6Circle+24>:	0xdc	0x51	0x55	0x55	0x55	0x55	0x00	0x00
#+end_src

这里可以看到 Circle 这个 class 的 vtable 完全是正常的, 然后我们查看一下 Sphere 这个 abstract class 的 vtable

有趣的是, abstract class 的 vtable 并不能通过 &object 然后通过最前面的 8 byte 去查看, 并且在 GCC 的优化下, 实际上我们的二进制文件并不生成 Shape 这个 abstract class 的 vtable ( 因为编译器觉得没必要 ), 如下:

#+begin_src bash
(base) zhb:~/Desktop$ nm -C demo | grep "vtable for Shape"
(base) zhb:~/Desktop$ nm -C demo | grep "Shape"
00000000000011dc W Shape::sayHi()
0000000000003da0 V typeinfo for Shape
0000000000002038 V typeinfo name for Shape
(base) zhb:~/Desktop$
#+end_src

然后在伟大的 gemini 的指引下, 我们就强制给 Shape 的 draw function 一个定义:

#+begin_src cpp
#include <iostream>

class Shape {
public:
    virtual void draw() = 0; // 纯虚
    virtual void sayHi();    // 只在这里声明，不要写 { ... }
};

// 在类外面实现, 这叫 Out-of-line definition
void Shape::sayHi() {
    std::cout << "Hi from Shape\n";
}

class Circle : public Shape {
public:
    void draw() override { std::cout << "Drawing Circle...\n"; }
};

int main() {
    Circle c;
    c.draw();
    return 0;
}
#+end_src

然后执行如下指令:
#+begin_src bash
(base) zhb:~/Desktop$ g++ -g demo.cpp -o demo
(base) zhb:~/Desktop$ gdb ./demo
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./demo...
(gdb) break main
Breakpoint 1 at 0x11a2: file demo.cpp, line 19.
(gdb) run
Starting program: /home/zhb/Desktop/demo

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at demo.cpp:19
19	int main() {
(gdb) n
20	    Circle c;
(gdb) n
21	    c.draw();
(gdb) n
Drawing Circle...
22	    return 0;
(gdb) p /a &_ZTV5Shape
$1 = 0x555555557d68 <_ZTV5Shape>
(gdb) x/2a &_ZTV5Shape + 2
Cannot perform pointer math on incomplete type "<data variable, no debug info>", try casting to a known type, or void *.
(gdb) x/2a (void**)&_ZTV5Shape + 2
0x555555557d78 <_ZTV5Shape+16>:	0x7ffff7cbbfa0 <__cxxabiv1::__cxa_pure_virtual()>	0x55555555516a <_ZN5Shape5sayHiEv>
(gdb)
#+end_src

具体的解释如下
1. p /a &_ZTV5Shape
   这是 Shape class 的 vtable 的符号名,C++ 支持函数重载和类, 但 Linker 只认识唯一的字符串, 所以编译器会对名字进行 "魔改" ( Mangling ), _Z 是 clang 或者 gcc 的前缀, TV 表示 Table Virtual (vtable), 5Shape 里面 5 是 class name 的字符数, Shape 就是 class name, 在 C++ 的二进制层面, _ZTV5Shape 被定义为一个数据的标签, 加上 & 是为了明确告诉 GDB 我要看这个符号所在的内存地址, /a 是 GDB 的格式化参数 ( Format ), p (print) 后面跟 /a 表示以 Address 格式打印
2. x/2a &_ZTV5Shape + 2
   很显然了是什么意思, 我们之前讲 vtable 的时候说过, vptr 指向的是 offset + 16 byte 的地方, 然后 _ZTV5Shape 代表 vtable, 所以这里 &_ZTV5Shape + 2 代表以这个格式 + 2, 也就是 16 byte
3. 报错
   原因是编译器生成的虚表符号 ( 如 _ZTV5Shape ) 在调试信息里通常没有定义具体的类型 ( 不像 int 或 long ), GDB 只知道这是一个标签不知道它代表的是什么大小的对象, 所以它说 incomplete type, 意思是我不知道 + 1 应该跨越几个字节, 所以我们这里 (void **) 这是一种强行解释, 就是你告诉 GDB " 别管这个符号原本是什么把它当成一个存储 void* ( 通用指针 ) 的数组首地址 ", 因为 void* 在 64 位系统上大小明确为 8 字节, 所以 gdb 就能明确算出 +2 是移动 16 byte

好了, 终于到我们想看的 Shape class 的 vptr 指向的部分了
0x555555557d78 <_ZTV5Shape+16>:	0x7ffff7cbbfa0 <__cxxabiv1::__cxa_pure_virtual()>	0x55555555516a <_ZN5Shape5sayHiEv>

这里面的 <__cxxabiv1::__cxa_pure_virtual()> 就是 pure virtual function 在 vtable 里面的样子, 这个是由 C++ 标准库提供的特殊函数地址, 如果你用黑魔法调用了它, 它唯一的功能就是打印那句著名的错误信息并 abort() 整个程序
<_ZN5Shape5sayHiEv> 则是一个正常的函数指针指向的地址, 跟我们在 virtual 里面看到的一摸一样没有任何区别

好了, 在本小节的最后, 让我们调用一下 0x7ffff7cbbfa0 <__cxxabiv1::__cxa_pure_virtual()> 这个函数结尾

#+begin_src bash
(gdb) call __cxa_pure_virtual()
pure virtual method called
The program being debugged entered a std::terminate call, most likely
caused by an unhandled C++ exception.  GDB blocked this call in order
to prevent the program from being terminated, and has restored the
context to its original state before the call.
To change this behaviour use "set unwind-on-terminating-exception off".
Evaluation of the expression containing the function (__cxxabiv1::__cxa_pure_virtual())
will be abandoned.
(gdb)
#+end_src

在正常的运行环境中 __cxa_pure_virtual 打印完错误后紧接着会调用 std::terminate(), 这会导致你的进程收到一个 SIGABRT 信号然后直接崩溃退出, 也就是说我现在在跑的 demo 进程就没了, 但是这里 gdb 阻止了我并且会滚到执行这个函数之前

这个报错里提到的 std::terminate 是 C++ 异常处理的终点, 当你调用了一个本不该存在的实现时, C++ 认为程序的逻辑已经彻底崩溃 ( Inconsistent State ), 除了自杀没有更好的办法

我们就按照 gdb 说的, 直接执行

#+begin_src bash
(gdb) set unwind-on-terminating-exception off
(gdb) call __cxa_pure_virtual()
pure virtual method called
terminate called without an active exception

Program received signal SIGABRT, Aborted.
Download failed: Invalid argument.  Continuing without source file ./nptl/./nptl/pthread_kill.c.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
warning: 44	./nptl/pthread_kill.c: No such file or directory
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwind-on-signal on".
Evaluation of the expression containing the function
(__cxxabiv1::__cxa_pure_virtual()) will be abandoned.
When the function is done executing, GDB will silently stop.
(gdb) kill
Kill the program being debugged? (y or n) y
[Inferior 1 (process 77892) killed]
#+end_src

完结撒花🎉

** 3. 补档

这节课的主要内容基本是讲完了, 然后翻了一下 ppt, 发现还有东西没有覆盖到, 再讲一下

好吧, 我并没有完全掌握 inheritance 这个东西.....

*** (1) derived class bassic
[Constructor]:
call a base class constructor via initializer list
[Inherits]:
all of the functions of the base class
[Inherits]:
all of the data of the base class
注意, 这里继承了 parent class 的所有的 data 和 function, 我们之前只是查看了所有的 data, 在最后的最后, 我们用一个综合的例子彻底 check 一下是不是所有的 function 也被继承了

*** (2) A comprehensive example

#+begin_src cpp Sphere.h
#include <iostream>

class Sphere {
      public:
        Sphere(double r) : r_(r) {}
        void print_1(void) { std::cout << "Sphere" << std::endl; }
        void print_2(void) { std::cout << "Sphere" << std::endl; }
        virtual void print_3(void) { std::cout << "Sphere" << std::endl; }
        virtual void print_4(void) { std::cout << "Sphere" << std::endl; }

      private:
        void copy_(Sphere const &other) { r_ = other.r_; }
        double r_;
};

class RedBall : public Sphere {
      public:
        RedBall(double r, double xxx) : Sphere(r), xxx_(xxx) {}
        // void print_1(void) { std::cout << "Ball" << std::endl; }
        void print_2(void) { std::cout << "Ball" << std::endl; }
        // void print_3(void) { std::cout << "Ball" << std::endl; }
        void print_4(void) { std::cout << "Ball" << std::endl; }

      private:
        double xxx_;
};

int main() {
        Sphere sphere_obj = Sphere(1.0);
        RedBall r = RedBall(1.0, 4.0);
        Sphere &obj = r;

        std::cout << "Printing of Sphere sphere_obj: " << std::endl;
        sphere_obj.print_1();
        sphere_obj.print_2();
        sphere_obj.print_3();
        sphere_obj.print_4();
        std::cout << std::endl;

        std::cout << "Printing of RedBall r: " << std::endl;
        r.print_1();
        r.print_2();
        r.print_3();
        r.print_4();
        std::cout << std::endl;

        std::cout << "Printing of Sphere &obj = r: " << std::endl;
        obj.print_1();
        obj.print_2();
        obj.print_3();
        obj.print_4();

        return 0;
}
#+end_src

运行:

#+begin_src bash
(base) zhb:~/Desktop$ g++ -g test.cpp -o test
(base) zhb:~/Desktop$ ./test
Printing of Sphere sphere_obj:
Sphere
Sphere
Sphere
Sphere

Printing of RedBall r:
Sphere
Ball
Sphere
Ball

Printing of Sphere &obj = r:
Sphere
Sphere
Sphere
Ball
#+end_src

然后直接 gdb 进去打印出来:
#+begin_src bash
(base) zhb:~/Desktop$ gdb ./test
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test...
(gdb) break main
Breakpoint 1 at 0x1195: file test.cpp, line 28.
(gdb) run
Starting program: /home/zhb/Desktop/test

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc3000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at test.cpp:28
28	int main() {
(gdb) n
29	        Sphere sphere_obj = Sphere(1.0);
(gdb) n
30	        RedBall r = RedBall(1.0, 4.0);
(gdb) n
31	        Sphere &obj = r;
(gdb) n
33	        std::cout << "Printing of Sphere sphere_obj: " << std::endl;
(gdb) print &sphere_obj
$1 = (Sphere *) 0x7fffffffded0
(gdb) print &r
$2 = (RedBall *) 0x7fffffffdee0
(gdb) print &obj
$3 = (Sphere *) 0x7fffffffdee0
(gdb) print sizeof(Sphere)
$4 = 16
(gdb) print sizeof(ReBall)
No symbol "ReBall" in current context.
(gdb) print sizeof(RedBall)
$5 = 24
(gdb) print sizeof(double)
$6 = 8
(gdb) x/8a (void **)&_ZTV7RedBall
0x555555557d38 <_ZTV7RedBall>:	0x0	0x555555557d78 <_ZTI7RedBall>
0x555555557d48 <_ZTV7RedBall+16>:	0x555555555404 <_ZN6Sphere7print_3Ev>	0x55555555550c <_ZN7RedBall7print_4Ev>
0x555555557d58 <_ZTV6Sphere>:	0x0	0x555555557d90 <_ZTI6Sphere>
0x555555557d68 <_ZTV6Sphere+16>:	0x555555555404 <_ZN6Sphere7print_3Ev>	0x555555555442 <_ZN6Sphere7print_4Ev>
#+end_src

这里稍微有点乱, 解读一下:
&_ZTV7RedBall 是 RedBall 的 vtable 的开始地址, 地址为0x555555557d38, 值为 0x0, 表示 offset 为 0
&_ZTV7RedBall + 1 的地址为 0x555555557d40, 该地址内存的值为 0x555555557d78 <_ZTI7RedBall>, 表示 type info
&_ZTV7RedBall + 2 和 &_ZTV7RedBall + 3 的地址分别为 0x555555557d48 <_ZTV7RedBall+16> 和 0x55555555550c, 其值为 0x555555555404 <_ZN6Sphere7print_3Ev> 还有 <_ZN7RedBall7print_4Ev>, 因为我们的 Base class Sphere 里面标记了 virtual 的只有 print_3 还有 print_4, 然后只有标记了 virtual 的 function 才会走 vtable, 没有标记 virtual 的函数都是静态绑定的, 都是在编译的时候直接根据变量类型确定了, 比如这里尽管 obj 和 r 的 vptr 一摸一样 ( 两者就是同一个 object ), 但是 obj.print_2() 走的是 Sphere 的, 因为 obj 是 Sphere & 类型, 而 print_2 又不是 virtual 不走 vptr, 所以会有之前的实验现象

还有, 我们可以注意到, 只要 base class 标记了 virtual, 不管 derived class 有没有写 override 关键字, 只要函数签名与基类虚函数一致, 派生类的函数也会自动成为对基类虚函数的重写 ( 多态行为依然生效 )

在 cpp 中, override 是一个可选但推荐使用的关键字 ( 从 cpp11 开始引入 ), 用于在 Derived Class 中显式地标明一个 virtual function 意图重写 base class 中的 virtual function, override 写在派生类虚函数的声明末尾 ( 函数签名之后 ), 表示该函数旨在覆盖基类中的某个虚函数, 如果函数签名与基类虚函数不完全匹配 ( 例如参数类型不同, 返回值不同, 或基类根本没有这个虚函数 ), 编译器会报错从而及早发现错误

如果派生类中写的函数签名与基类虚函数不匹配, 则不会构成重写, 而是变成隐藏 ( 如果函数名相同但参数不同, 基类同名函数被隐藏, 如果返回类型不兼容, 编译错误 ), 更危险的是这种情况编译器通常不会报错, 只会给出警告 ( 取决于编译选项 ), 容易导致运行时调用基类版本而非派生类版本, 造成难以发现的逻辑错误

#+begin_src cpp
class Base {
public:
    virtual void func(int) {}
};

class Derived : public Base {
public:
    void func(double) {}  // 意图重写 func(int)，但参数类型不同
};

int main() {
    Derived d;
    Base* p = &d;
    p->func(42);   // 调用 Base::func(int)，而不是 Derived::func(double)！
}
#+end_src

感觉到这里差不多了, 还有一点关于 inheritance, virtual function, polymorphism 和 object 生命周期相关的东西没讲, 这个已经是第八课的内容了, 就这样吧, 感觉 cpp 好难, 学的要力竭了, 从早上开始学这个, 学到现在一共 8 小时了, 8 h 才学懂最基础的一点东西.....


* lab inheritance

这个 lab 总的来说不难, 但是由于一些不好的习惯, 或者说不好的实现, 浪费了我大量时间, 或者说也不能算是浪费, 这让我对 cpp 的资源管理有了一个更深的理解

** life cycle

首先, 我们先讲解一下一个对象的生命周期

1. object 被创建的流程是:
(1) 得到储存该对象的内存
(2) 如果有 inheritance, 先调用 Base Class 的 constructor 进行初始化, 然后按照声明的顺序对该对象的成员进行初始化, 如果有初始列表, 比如base class的constructor调用, 还有委托构造, 还有初始成员列表, 如果没有初始列表, 就调用default constructor, 如果没有 default constructor 就会报错 ( lab inheritance 经验 ), 注意这里的初始化顺序是按照声明顺序的前后依次初始化的, 跟你在初始成员列表里面初始化的顺序无关, 你在初始列表里写的顺序是毫无作用的
(3) 执行该 class 的 constructor的函数体

注意, 如果我们在声明 class 的 member 的时候直接对 member 进行了初始化, 编译器默认的行为是把声明时对 member 的初始化写到上面流程的 (2) 里面执行的, 而不是提前执行

2. object生命周期结束的流程是:
(1) 执行 destructor 的函数体
(2) 按照声明的反顺序，即最后声明的对象最先，依次对该对象的成员调用 destructor
(3) 执行 base class 的 destructor 的函数体
(3) 释放内存

下面写一个小 demo 展示一下, 顺便展示一下有 inheritance 的时候 destructor 的表现

#+begin_src cpp lifecycle.cpp
#include <iostream>
#include <string>

class Member {
public:
    std::string name;
    Member(std::string n) : name(n) {
        std::cout << " Member " << name << " initialized" << std::endl;
    }
    ~Member() {
        std::cout << " Member " << name << " destroyed" << std::endl;
    }
};

class Base {
public:
    Base() {
        std::cout << " Base constructor body executed" << std::endl;
    }

   /* no virtual */
    ~Base() {
        std::cout << " Base destructor body executed" << std::endl;
    }
};

class Derived : public Base {
public:
    /* initialization will follow the declared order enven though not so in the initialization list */
    Member m1;
    Member m2 = Member("M2");
    Member m3;

    /* literaturally, first M3 then M1, finally Base(), but actually first Base(), then M1, and finally M3 */
    Derived() : m3("M3"), m1("M1"), Base() { /* bad notation, only for demo purpose */
        std::cout << " Derived constructor body executed" << std::endl;
    }

    ~Derived() {
        std::cout << " Derived destructor body executed" << std::endl;
    }
};

int main() {
    std::cout << std::endl << "--- Scenario 1: Correct Lifecycle (Local Object) ---" << std::endl;
    {
        Derived d;
    }
    /* d out of scope, the whole process will be demonstrate */

    std::cout << "--- Scenario 2: Polymorphic Danger (Non-virtual Destructor) ---" << std::endl;
    Base* ptr = new Derived();
    std::cout << " Deleting via Base* ..." << std::endl;
    delete ptr;

    return 0;
}
#+end_src

#+begin_src bash
(base) zhb:~/Desktop$ g++ -g lifecycle.cpp -o lifecycle
(base) zhb:~/Desktop$ ./lifecycle

--- Scenario 1: Correct Lifecycle (Local Object) ---
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
 Derived constructor body executed
 Derived destructor body executed
 Member M3 destroyed
 Member M2 destroyed
 Member M1 destroyed
 Base destructor body executed
--- Scenario 2: Polymorphic Danger (Non-virtual Destructor) ---
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
 Derived constructor body executed
 Deleting via Base* ...
 Base destructor body executed
#+end_src

在 Scenario 1 里面我们可以看到, 这个 object 的创建和销毁是一个完全对称的情况, 而且实际上只要 object 离开了作用域, 他的生命周期结束, 这个流程:
本class的destructor -> 按顺序调用member的destructor->base class的destructor -> 释放内存
是一定会发生的, 编译器保证无论发生什么 ( 正常退出, return, 抛出异常 ) 都一定会在该对象离开作用域时调用它的析构函数

但是注意即使你不在初始列表里面调用 Base class 的 constructor, 他还是会调用的, 不过这个时候调用的是 Base Class 的 default constructor, 同理即使你不在 initialization list 里面进行初始成员列表初始化 member, 编译器还是会默认的调用该 member 的 default constructor, 例如下:
#+begin_src cpp
#include <iostream>
#include <string>

class Member {
public:
    std::string name;
    Member(std::string n) : name(n) {
        std::cout << " Member " << name << " initialized" << std::endl;
    }
    Member() : name("default member") {
	    std::cout << "Member" << name << "initialized" << std::endl;
    }
    ~Member() {
        std::cout << " Member " << name << " destroyed" << std::endl;
    }
};

class Base {
public:
    Base() {
        std::cout << " Base constructor body executed" << std::endl;
    }

   /* no virtual */
    ~Base() {
        std::cout << " Base destructor body executed" << std::endl;
    }
};

class Derived : public Base {
public:
    /* initialization will follow the declared order enven though not so in the initialization list */
    Member m1;
    Member m2 = Member("M2");
    Member m3;
    Member m4;

    /* literaturally, first M3 then M1, finally Base(), but actually first Base(), then M1, and finally M3 */
    Derived() : m3("M3"), m1("M1") { /* bad notation, only for demo purpose */
        std::cout << " Derived constructor body executed" << std::endl;
    }

    ~Derived() {
        std::cout << " Derived destructor body executed" << std::endl;
    }
};

int main() {
    std::cout << std::endl << "--- Scenario 1: Correct Lifecycle (Local Object) ---" << std::endl;
    {
        Derived d;
    }
    /* d out of scope, the whole process will be demonstrate */

    std::cout << "--- Scenario 2: Polymorphic Danger (Non-virtual Destructor) ---" << std::endl;
    Base* ptr = new Derived();
    std::cout << " Deleting via Base* ..." << std::endl;
    delete ptr;

    return 0;
}
#+end_src

然后编译执行:
#+begin_src bash
(base) zhb:~/Desktop$ g++ -g lifecycle.cpp -o lifecycle
(base) zhb:~/Desktop$ ./lifecycle

--- Scenario 1: Correct Lifecycle (Local Object) ---
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
Memberdefault memberinitialized
 Derived constructor body executed
 Derived destructor body executed
 Member default member destroyed
 Member M3 destroyed
 Member M2 destroyed
 Member M1 destroyed
 Base destructor body executed
--- Scenario 2: Polymorphic Danger (Non-virtual Destructor) ---
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
Memberdefault memberinitialized
 Derived constructor body executed
 Deleting via Base* ...
 Base destructor body executed
(base) zhb:~/Desktop$
#+end_src

好了, Scenario 1 是对一个 object 的 lifecycle 的一个粗浅的了解, 接下来我们看看有 inheritance 的时候这个 life cycle 会发生什么变换, 你看这里的 Scenario 2 里面 delete 的时候调用的是 Base class 的 destructor, 而不是 Derived class 的 destructor, 这个导致我们实际上并没有释放 new Derived() 这里的 heap 空间, 我们可以 valgrind 查看一下

#+begin_src bash
(base) zhb:~/Desktop$ valgrind --leak-check=full ./lifecycle
==15329== Memcheck, a memory error detector
==15329== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==15329== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==15329== Command: ./lifecycle
==15329==

--- Scenario 1: Correct Lifecycle (Local Object) ---
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
 Derived constructor body executed
 Derived destructor body executed
 Member M3 destroyed
 Member M2 destroyed
 Member M1 destroyed
 Base destructor body executed
--- Scenario 2: Polymorphic Danger (Non-virtual Destructor) ---
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
 Derived constructor body executed
 Deleting via Base* ...
 Base destructor body executed
==15329== Mismatched new/delete size value: 1
==15329==    at 0x484A5B9: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15329==    by 0x10A4C2: main (lifecycle.cpp:54)
==15329==  Address 0x4e2d4c0 is 0 bytes inside a block of size 96 alloc'd
==15329==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15329==    by 0x10A45E: main (lifecycle.cpp:52)
==15329==
==15329==
==15329== HEAP SUMMARY:
==15329==     in use at exit: 0 bytes in 0 blocks
==15329==   total heap usage: 3 allocs, 3 frees, 74,848 bytes allocated
==15329==
==15329== All heap blocks were freed -- no leaks are possible
==15329==
==15329== For lists of detected and suppressed errors, rerun with: -s
==15329== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
(base) zhb:~/Desktop$
#+end_src

看, 这里是有很明显的内存泄漏的问题的, 这个原因就是 Base Class 的 destructor 不是一个 virtual, 根据我们之前在 lecture 07 讲述的, 如果没有被 virtual 标记, 对于这个函数编译器并不会采取 vptr 去 vtable 寻址的方式调用, 而是直接在编译时静态绑定, 是什么类型就调用什么类型的 destructor, 这里是 Base * ptr 的指向 Base class object 的指针, 所以自然调用的就是 Base class 的 destructor, 如果不信的话我们可以 gdb 进去看一下

#+begin_src bash
(base) zhb:~/Desktop$ gdb ./lifecycle
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./lifecycle...
(gdb) b main
Breakpoint 1 at 0x23bd: file lifecycle.cpp, line 48.
(gdb) run
Starting program: /home/zhb/Desktop/lifecycle

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at lifecycle.cpp:48
48	int main() {
(gdb) n
49	    std::cout << std::endl << "--- Scenario 1: Correct Lifecycle (Local Object) ---" << std::endl;
(gdb) n

--- Scenario 1: Correct Lifecycle (Local Object) ---
51	        Derived d;
(gdb) n
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
Memberdefault memberinitialized
 Derived constructor body executed
52	    }
(gdb) n
 Derived destructor body executed
 Member default member destroyed
 Member M3 destroyed
 Member M2 destroyed
 Member M1 destroyed
 Base destructor body executed
55	    std::cout << "--- Scenario 2: Polymorphic Danger (Non-virtual Destructor) ---" << std::endl;
(gdb) n
--- Scenario 2: Polymorphic Danger (Non-virtual Destructor) ---
56	    Base* ptr = new Derived();
(gdb) n
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
Memberdefault memberinitialized
 Derived constructor body executed
57	    std::cout << " Deleting via Base* ..." << std::endl;
(gdb) print ptr
$1 = (Base *) 0x55555556c6c0
(gdb) print sizeof(*ptr)
$2 = 1
(gdb) n
 Deleting via Base* ...
58	    delete ptr;
(gdb) disassemble /m
Dump of assembler code for function main():
48	int main() {
   0x00005555555563a9 <+0>:	endbr64
   0x00005555555563ad <+4>:	push   %rbp
   0x00005555555563ae <+5>:	mov    %rsp,%rbp
   0x00005555555563b1 <+8>:	push   %r13
   0x00005555555563b3 <+10>:	push   %r12
   0x00005555555563b5 <+12>:	push   %rbx
   0x00005555555563b6 <+13>:	sub    $0xa8,%rsp
   0x00005555555563bd <+20>:	mov    %fs:0x28,%rax
   0x00005555555563c6 <+29>:	mov    %rax,-0x28(%rbp)
   0x00005555555563ca <+33>:	xor    %eax,%eax

49	    std::cout << std::endl << "--- Scenario 1: Correct Lifecycle (Local Object) ---" << std::endl;
   0x00005555555563cc <+35>:	mov    0x2c05(%rip),%rax        # 0x555555558fd8
   0x00005555555563d3 <+42>:	mov    %rax,%rsi
   0x00005555555563d6 <+45>:	lea    0x2c63(%rip),%rax        # 0x555555559040 <_ZSt4cout@GLIBCXX_3.4>
   0x00005555555563dd <+52>:	mov    %rax,%rdi
   0x00005555555563e0 <+55>:	call   0x555555556230 <_ZNSolsEPFRSoS_E@plt>
   0x00005555555563e5 <+60>:	mov    %rax,%rdx
   0x00005555555563e8 <+63>:	lea    0xcf9(%rip),%rax        # 0x5555555570e8
   0x00005555555563ef <+70>:	mov    %rax,%rsi
   0x00005555555563f2 <+73>:	mov    %rdx,%rdi
   0x00005555555563f5 <+76>:	call   0x555555556200 <_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc@plt>
   0x00005555555563fa <+81>:	mov    0x2bd7(%rip),%rdx        # 0x555555558fd8
   0x0000555555556401 <+88>:	mov    %rdx,%rsi
   0x0000555555556404 <+91>:	mov    %rax,%rdi
   0x0000555555556407 <+94>:	call   0x555555556230 <_ZNSolsEPFRSoS_E@plt>

50	    {
51	        Derived d;
   0x000055555555640c <+99>:	lea    -0xb0(%rbp),%rax
   0x0000555555556413 <+106>:	mov    %rax,%rdi
   0x0000555555556416 <+109>:	call   0x55555555681c <_ZN7DerivedC2Ev>

52	    }
   0x000055555555641b <+114>:	lea    -0xb0(%rbp),%rax
   0x0000555555556422 <+121>:	mov    %rax,%rdi
   0x0000555555556425 <+124>:	call   0x555555556a96 <_ZN7DerivedD2Ev>

53	    /* d out of scope, the whole process will be demonstrate */
54
55	    std::cout << "--- Scenario 2: Polymorphic Danger (Non-virtual Destructor) ---" << std::endl;
   0x000055555555642a <+129>:	lea    0xcef(%rip),%rax        # 0x555555557120
   0x0000555555556431 <+136>:	mov    %rax,%rsi
   0x0000555555556434 <+139>:	lea    0x2c05(%rip),%rax        # 0x555555559040 <_ZSt4cout@GLIBCXX_3.4>
   0x000055555555643b <+146>:	mov    %rax,%rdi
   0x000055555555643e <+149>:	call   0x555555556200 <_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc@plt>
--Type <RET> for more, q to quit, c to continue without paging--
   0x0000555555556443 <+154>:	mov    0x2b8e(%rip),%rdx        # 0x555555558fd8
   0x000055555555644a <+161>:	mov    %rdx,%rsi
   0x000055555555644d <+164>:	mov    %rax,%rdi
   0x0000555555556450 <+167>:	call   0x555555556230 <_ZNSolsEPFRSoS_E@plt>

56	    Base* ptr = new Derived();
   0x0000555555556455 <+172>:	mov    $0x80,%edi
   0x000055555555645a <+177>:	call   0x555555556210 <_Znwm@plt>
   0x000055555555645f <+182>:	mov    %rax,%rbx
   0x0000555555556462 <+185>:	mov    $0x1,%r13d
   0x0000555555556468 <+191>:	mov    %rbx,%rdi
   0x000055555555646b <+194>:	call   0x55555555681c <_ZN7DerivedC2Ev>
   0x0000555555556470 <+199>:	mov    %rbx,-0xb8(%rbp)
   0x00005555555564dd <+308>:	mov    %rax,%r12
   0x00005555555564e0 <+311>:	test   %r13b,%r13b
   0x00005555555564e3 <+314>:	je     0x5555555564f2 <main()+329>
   0x00005555555564e5 <+316>:	mov    $0x80,%esi
   0x00005555555564ea <+321>:	mov    %rbx,%rdi
   0x00005555555564ed <+324>:	call   0x555555556220 <_ZdlPvm@plt>
   0x00005555555564f2 <+329>:	mov    %r12,%rax
   0x00005555555564f5 <+332>:	mov    -0x28(%rbp),%rdx
   0x00005555555564f9 <+336>:	sub    %fs:0x28,%rdx
   0x0000555555556502 <+345>:	je     0x555555556509 <main()+352>
   0x0000555555556504 <+347>:	call   0x555555556270 <__stack_chk_fail@plt>
   0x0000555555556509 <+352>:	mov    %rax,%rdi
   0x000055555555650c <+355>:	call   0x555555556290 <_Unwind_Resume@plt>

57	    std::cout << " Deleting via Base* ..." << std::endl;
   0x0000555555556477 <+206>:	lea    0xce2(%rip),%rax        # 0x555555557160
   0x000055555555647e <+213>:	mov    %rax,%rsi
   0x0000555555556481 <+216>:	lea    0x2bb8(%rip),%rax        # 0x555555559040 <_ZSt4cout@GLIBCXX_3.4>
   0x0000555555556488 <+223>:	mov    %rax,%rdi
   0x000055555555648b <+226>:	call   0x555555556200 <_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc@plt>
   0x0000555555556490 <+231>:	mov    0x2b41(%rip),%rdx        # 0x555555558fd8
   0x0000555555556497 <+238>:	mov    %rdx,%rsi
   0x000055555555649a <+241>:	mov    %rax,%rdi
   0x000055555555649d <+244>:	call   0x555555556230 <_ZNSolsEPFRSoS_E@plt>

58	    delete ptr;
=> 0x00005555555564a2 <+249>:	mov    -0xb8(%rbp),%rbx
   0x00005555555564a9 <+256>:	test   %rbx,%rbx
   0x00005555555564ac <+259>:	je     0x5555555564c3 <main()+282>
   0x00005555555564ae <+261>:	mov    %rbx,%rdi
   0x00005555555564b1 <+264>:	call   0x5555555567de <_ZN4BaseD2Ev>
   0x00005555555564b6 <+269>:	mov    $0x1,%esi
   0x00005555555564bb <+274>:	mov    %rbx,%rdi
   0x00005555555564be <+277>:	call   0x555555556220 <_ZdlPvm@plt>

--Type <RET> for more, q to quit, c to continue without paging--
59
60	    return 0;
   0x00005555555564c3 <+282>:	mov    $0x0,%eax

61	}
   0x00005555555564c8 <+287>:	mov    -0x28(%rbp),%rdx
   0x00005555555564cc <+291>:	sub    %fs:0x28,%rdx
   0x00005555555564d5 <+300>:	je     0x555555556516 <main()+365>
   0x00005555555564d7 <+302>:	jmp    0x555555556511 <main()+360>
   0x00005555555564d9 <+304>:	endbr64
   0x0000555555556511 <+360>:	call   0x555555556270 <__stack_chk_fail@plt>
   0x0000555555556516 <+365>:	add    $0xa8,%rsp
   0x000055555555651d <+372>:	pop    %rbx
   0x000055555555651e <+373>:	pop    %r12
   0x0000555555556520 <+375>:	pop    %r13
   0x0000555555556522 <+377>:	pop    %rbp
   0x0000555555556523 <+378>:	ret

End of assembler dump.
(gdb)
#+end_src

注意, 我们 print sizeof(*ptr) 得到的是 1 byte, 这个是因为 Base class 实际上一个数据都没有, 但是我们如果要创建 Base class 的 array 的话, 必须有个东西占位, 所以这里给了 1 byte, 我们之后如果把 Base class 的 destructor 写成 virtual, sizeof(*ptr) 就会变成 8 byte, 即 vptr 的大小

这里按照 gemini 的意思, 直接查看了编译的汇编代码, 虽然我也看不懂 x86 汇编, 但是我们可以在 gemini 的指导下看一下关键地方

#+begin_src bash
58	    delete ptr;
=> 0x00005555555564a2 <+249>:	mov    -0xb8(%rbp),%rbx   # 1. 把指针 ptr 的值读入 rbx
   0x00005555555564a9 <+256>:	test   %rbx,%rbx          # 2. 检查 ptr 是否为 NULL (安全检查)
   0x00005555555564ac <+259>:	je     0x5555555564c3     # 3. 如果是 NULL，直接跳过不执行 delete
   0x00005555555564ae <+261>:	mov    %rbx,%rdi          # 4. 把对象地址作为参数传给析构函数
   0x00005555555564b1 <+264>:	call   0x5555555567de <_ZN4BaseD2Ev>  # 5. 【关键点】硬编码调用 Base 的析构函数！
   0x00005555555564b6 <+269>:	mov    $0x1,%esi          # 6. 准备 delete 内存的大小/参数
   0x00005555555564bb <+274>:	mov    %rbx,%rdi          # 7. 把内存地址传给 operator delete
   0x00005555555564be <+277>:	call   0x555555556220 <_ZdlPvm@plt>   # 8. 调用内存释放函数
#+end_src

这个是 delete 这个 Base * ptr 时候的对应汇编, 可以看到  0x00005555555564b1 <+264>:	call   0x5555555567de <_ZN4BaseD2Ev>  这里是直接 call 了 Base 的 destructor

然后我们看一下上面的生命周期开始的时候相关的对应汇编, 对于局部变量 d:
#+begin_src bash
51	        Derived d;
   ... call <_ZN7DerivedC2Ev>  # 调用构造函数
52	    }
   ... call <_ZN7DerivedD2Ev>  # 作用域结束，自动调用析构函数
#+end_src

这里证实了我们关于生命周期的一些认识

然后我们把对应的 Base class 的 destructor 改成 virtual 的, 然后运行一下程序, 同时 gdb 进去看一下:

#+begin_src cpp
#include <iostream>
#include <string>

class Member {
public:
    std::string name;
    Member(std::string n) : name(n) {
        std::cout << " Member " << name << " initialized" << std::endl;
    }
    Member() : name("default member") {
	    std::cout << "Member" << name << "initialized" << std::endl;
    }
    ~Member() {
        std::cout << " Member " << name << " destroyed" << std::endl;
    }
};

class Base {
public:
    Base() {
        std::cout << " Base constructor body executed" << std::endl;
    }

   /* no virtual */
    virtual ~Base() {
        std::cout << " Base destructor body executed" << std::endl;
    }
};

class Derived : public Base {
public:
    /* initialization will follow the declared order enven though not so in the initialization list */
    Member m1;
    Member m2 = Member("M2");
    Member m3;
    Member m4;

    /* literaturally, first M3 then M1, finally Base(), but actually first Base(), then M1, and finally M3 */
    Derived() : m3("M3"), m1("M1") { /* bad notation, only for demo purpose */
        std::cout << " Derived constructor body executed" << std::endl;
    }

    ~Derived() override {
        std::cout << " Derived destructor body executed" << std::endl;
    }
};

int main() {
    std::cout << std::endl << "--- Scenario 1: Correct Lifecycle (Local Object) ---" << std::endl;
    {
        Derived d;
    }
    /* d out of scope, the whole process will be demonstrate */

    std::cout << "--- Scenario 2: Polymorphic Danger (Virtual Destructor) ---" << std::endl;
    Base* ptr = new Derived();
    std::cout << " Deleting via Base* ..." << std::endl;
    delete ptr;

    return 0;
}
#+end_src

#+begin_src bash
(base) zhb:~/Desktop$ g++ -g lifecycle.cpp -o lifecycle
(base) zhb:~/Desktop$ ./lifecycle

--- Scenario 1: Correct Lifecycle (Local Object) ---
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
Memberdefault memberinitialized
 Derived constructor body executed
 Derived destructor body executed
 Member default member destroyed
 Member M3 destroyed
 Member M2 destroyed
 Member M1 destroyed
 Base destructor body executed
--- Scenario 2: Polymorphic Danger (Virtual Destructor) ---
 Base constructor body executed
 Member M1 initialized
 Member M2 initialized
 Member M3 initialized
Memberdefault memberinitialized
 Derived constructor body executed
 Deleting via Base* ...
 Derived destructor body executed
 Member default member destroyed
 Member M3 destroyed
 Member M2 destroyed
 Member M1 destroyed
 Base destructor body executed
#+end_src

可见这里在 delete 这个 Base * ptr 的时候正确调用了 Derived class 的 Destructor, 我们来 gdb 看一下相关的汇编, 然后见识一下 Destructor 相关的函数指针长啥样, 先只看一下这里的汇编

#+begin_src bash
58	    delete ptr;
=> 0x00005555555564a2 <+249>:	mov    -0xb8(%rbp),%rax
   0x00005555555564a9 <+256>:	test   %rax,%rax
   0x00005555555564ac <+259>:	je     0x5555555564bd <main()+276>
   0x00005555555564ae <+261>:	mov    (%rax),%rdx
   0x00005555555564b1 <+264>:	add    $0x8,%rdx
   0x00005555555564b5 <+268>:	mov    (%rdx),%rdx
   0x00005555555564b8 <+271>:	mov    %rax,%rdi
   0x00005555555564bb <+274>:	call   *%rdx
#+end_src

我确实是看不懂汇编的, 但是 gemini 的解释是

#+begin_src bash
58	    delete ptr;
=> 0x00005555555564a2 <+249>:	mov    -0xb8(%rbp),%rax   # 1. rax = ptr (对象的首地址)
   0x00005555555564a9 <+256>:	test   %rax,%rax          # 检查是否为 NULL
   0x00005555555564ac <+259>:	je     0x5555555564bd

   # --- 核心动态查表开始 ---
   0x00005555555564ae <+261>:	mov    (%rax),%rdx        # 2. rdx = *rax (获取对象头部的 vptr)
   0x00005555555564b1 <+264>:	add    $0x8,%rdx          # 3. rdx = rdx + 8 (移动到虚表中的第二个槽位)
   0x00005555555564b5 <+268>:	mov    (%rdx),%rdx        # 4. rdx = *rdx (从虚表里取出真正的函数地址)

   0x00005555555564b8 <+271>:	mov    %rax,%rdi          # 准备 this 指针
   0x00005555555564bb <+274>:	call   *%rdx               # 5. 间接调用！跳转到 rdx 里的地址
#+end_src

我们可以查看一下 vptr, vtable, 还有对应的函数指针, 这里因为是 destructor, 和我们在 lecture 07 碰到的那种相比似乎有点不同:

#+begin_src bash
(gdb) x/gx 0x55555556c6c0
0x55555556c6c0:	0x0000555555558cb0
(gdb) x/8a (long *) 0x0000555555558cb0 - 2
0x555555558ca0 <_ZTV7Derived>:	0x0	0x555555558ce0 <_ZTI7Derived>
0x555555558cb0 <_ZTV7Derived+16>:	0x555555556af2 <_ZN7DerivedD2Ev>	0x555555556b8a <_ZN7DerivedD0Ev>
0x555555558cc0 <_ZTV4Base>:	0x0	0x555555558cf8 <_ZTI4Base>
0x555555558cd0 <_ZTV4Base+16>:	0x5555555567e6 <_ZN4BaseD2Ev>	0x555555556832 <_ZN4BaseD0Ev>
#+end_src

我们又一次看见这个 vtable 了, gdb 的格式还是那么一言难尽, 整理一下, 我们这里只整理 Derived Class 的, Base Class 的很类似的一下就能看懂的:

|----------------+----------------+---------------------------------------------|
|        内存地址 |     地址里的内容 | 对应符号以及作用                               |
|----------------+----------------+---------------------------------------------|
| 0x555555558ca0 |            0x0 | <_ZTV7Derived>, 即 offset_to_top            |
|----------------+----------------+---------------------------------------------|
| 0x555555558ca8 | 0x555555558ce0 | <_ZTI7Derived>, 即 typeinfo 指针             |
|----------------+----------------+---------------------------------------------|
| 0x555555558cb0 | 0x555555556af2 | <_ZN7DerivedD2Ev>, D2 (Complete) Destructor |
|----------------+----------------+---------------------------------------------|
| 0x555555558cb8 | 0x555555556b8a | <_ZN7DerivedD0Ev>, D0 (Deleting) Destructor |
|----------------+----------------+---------------------------------------------|

这里面的 <_ZN7DerivedD2Ev> 表示 Base Object Destructor, 它负责销毁当前类的成员并调用父类的析构, 它不负责释放内存

D0 ( 对应看到的 D0Ev ): Deleting Destructor, 它是虚表里真正被 delete ptr 调用的, 它会先调用 D2 销毁对象然后调用 operator delete 释放堆内存
Gemini 的解释如下:
更具体的说, 在 GCC 和 Clang 遵循的 Itanium C++ ABI 规范中, 为了处理不同的销毁场景, 编译器会为一个 virtual ~Destructor 生成多个入口点, 你看到的 D0 和 D2 就是其中最核心的两个

D2: Base Object Destructor ( 基础析构 )
- 对应代码: 它最接近你写的那个 ~ClassName() { ... } 的函数体
- 职责:
  - 执行你写的析构函数体, 如 std::cout << ...
  - 逆序调用成员变量, 如你的 Member m1, m2的析构函数
  - 调用基类的析构函数
关键点: 它只负责清理资源, 不负责释放内存, 它通常用于销毁栈上的对象, 或者作为子类析构链的一部分

D0: Deleting Destructor ( 删除析构 )
- 对应代码: 这是一个由编译器生成的 “包装函数”
- 职责:
  - 调用 D2 ( 完成上面的所有清理工作 )
  - 调用 operator delete ( 释放该对象占用的堆内存 )
关键点: 当你执行 delete ptr; 时, 虚表里被调用的实际是这个 D, 。因为它知道如何完整地 "毁尸灭迹"

我们下面干点坏事验证一下, 我们将把 Derived Class 的 D0 destructor 换成 Base Class 的 D0 destructor

#+begin_src bash
(gdb) n
 Deleting via Base* ...
58	    delete ptr;
(gdb) print sizeof(*ptr)
$2 = 8
(gdb) print ptr
$3 = (Base *) 0x55555556c6c0
(gdb) x/gx 0x55555556c6c0
0x55555556c6c0:	0x0000555555558cb0
(gdb) x/4a 0x0000555555558cb0
0x555555558cb0 <_ZTV7Derived+16>:	0x555555556af2 <_ZN7DerivedD2Ev>	0x555555556b8a <_ZN7DerivedD0Ev>
0x555555558cc0 <_ZTV4Base>:	0x0	0x555555558cf8 <_ZTI4Base>
(gdb) x/8a 0x0000555555558cb0 - 2
0x555555558cae <_ZTV7Derived+14>:	0x555555556af20000	0x555555556b8a0000
0x555555558cbe <_ZTV7Derived+30>:	0x0	0x555555558cf80000
0x555555558cce <_ZTV4Base+14>:	0x5555555567e60000	0x5555555568320000
0x555555558cde <_ZTV4Base+30>:	0x7ffff7e6ebe80000	0x5555555571b00000
(gdb) x/8a (long *) 0x0000555555558cb0 - 2
0x555555558ca0 <_ZTV7Derived>:	0x0	0x555555558ce0 <_ZTI7Derived>
0x555555558cb0 <_ZTV7Derived+16>:	0x555555556af2 <_ZN7DerivedD2Ev>	0x555555556b8a <_ZN7DerivedD0Ev>
0x555555558cc0 <_ZTV4Base>:	0x0	0x555555558cf8 <_ZTI4Base>
0x555555558cd0 <_ZTV4Base+16>:	0x5555555567e6 <_ZN4BaseD2Ev>	0x555555556832 <_ZN4BaseD0Ev>
(gdb) set *(long *)0x555555558cb8 = 0x555555556832
(gdb) x/2a 0x555555558cb0
0x555555558cb0 <_ZTV7Derived+16>:	0x555555556af2 <_ZN7DerivedD2Ev>	0x555555556832 <_ZN4BaseD0Ev>
(gdb) continue
Continuing.
 Base destructor body executed
[Inferior 1 (process 16180) exited normally]
(gdb)
#+end_src

完美, 你看这里我们调用了 Base class 的 destructor, 这个是因为我们成功修改了 vtable 里面的槽位, 我们对 cpp 的对象的生命周期的了解这样应该已经相当详细了

** Resource Management: more on RAII

#+begin_quote
在这里, 我们暂且先把资源认定为 heap 上 new 的 memory, 但实际上资源类型很多, 比如打开的文件句柄
#+end_quote

cpp 资源管理的核心思想就是我们不应该手动管理任何资源, 我们应该利用对象的生命周期, 或者说生命周期开始和结束必然执行的 constructor 和 destructor 这个特性来管理资源 ( 因为这个是绝对的, 即使有异常处理, 只要离开作用域 destructor 被保证一定执行 ), 具体的来说, 就是对象生命周期开始的时候获取资源, 对象的生命周期结束的时候释放资源, 将资源的生命周期和对象的生命周期强行绑定, 同时明确资源的所有权, 采取 "谁拥有谁负责" 的思路把资源的所有权给予对象, 由拥有资源的对象负责资源的获得/资源所有权转交/资源的释放

上面讲的有点抽象了, 下面讲的具体一点:

根据我们在 ECE220 里面的 run time stack 学到的知识, 我们清楚的知道 stack 是如何管理变量的, 在 cpp 里的逻辑是和 ECE220 里面的 c 语言的逻辑一摸一样的, 唯一的区别是我们保证 stack 在摧毁 cpp 的一个 object 的时候会调用这个 object 对应的 destructor, 这个是被严格保证的, 好了下面开始讲这个逻辑

因为生命周期开始 ( 比如 object 被创建 ) 时一定会调用 constructor, 而生命周期结束 ( 比如离开作用域 ) 时一定会调用 destructor 是一定会被调用的, 所以资源的获取和资源的释放自然而然就被放在了 constructor 和 destructor 上面, 这个流程保证了我们一定会执行 " 资源的获取和释放 " 这两个流程

好了再来看一下我们的困境, 通常我们的问题是忘记释放资源, 我们有什么办法可以摆脱这个问题呢?
1. 我们不需要手动释放资源, 上面过程中描述的 " 调用每个 member 的 destructor " 就可以完成资源的释放, 或者说, 我们不需要手写 destructor, default destructor 就可以完成资源释放的任务
2. 每个 member 的 destructor 不足以释放资源, 我们需要写一个 custom destructor 来释放那些没有被释放的资源

很自然的, 最佳选择是不要手动管理, 即依次调用每个 member 的 destructor 就能够完成资源释放的任务, 这就要求 对象的每一个成员的 destructor 都可以完成对该成员本身持有的资源的释放, 这代表着我们需要尽量使用那些 “自身的 destructor 就能完成对自身的资源释放” 的类型作为本 class 的成员, 主要包括:
1. 没有管理资源的类型, 比如 int, float, double 这种基本类型, 还有仅由基本类型组成的简单 class, 这些东西都是直接在 stack 上的, 会被 stack 正常摧毁, 或者说这些 class 就没有管理资源
2. 管理了一些资源资源, 但是已经确保能在本类型的 destructor 里能释放资源的 class, 比如我们自己之前实现的一些 class ( 这个要求经过详细的测试 ), 还有一些比如 std::vector, std::unique_ptr, shared_ptr 这样的东西, 我们需要尽量使用这种类型作为我们的 class 的 member type

那什么会让编译器的默认表现没法正常释放资源呢, 现在接触到的就只有裸指针, 因为裸指针在生命周期结束的时候会被当作一个long处理, 编译器只是认为他是一个long int 而不会认为他是一个指向 heap 上某一块 memory 资源的指针, 所以编译器的默认析构会造成内存泄漏, 所以为了让编译器的默认表现能正常释放资源, 我们就尽量不要用裸指针

当然也有情况我们不得不自己手动管理资源而不能依赖编译器的默认表现, 那我们需要记住的是 " 获得了资源就要记得马上管理整个资源的生命周期 ", 包括 " 什么时候销毁资源, 什么时候转移资源 ", 具体操作就是, 一旦在 constructor 里面获取了资源 ( 比如 new 了 ), 那我们马上就需要做的是处理这个资源, 比如这个资源应该如何被释放, 什么时候会被转移, 也就是马上写 custom destrcutor 处理 " 如何释放资源 " 以确保资源的生命周期能和对象的生命周期绑定, 马上写 assignment operator 处理 " 如何转移资源 "

上面这套逻辑就是 cpp 之父 Bjarne Stroustrup 推崇的 RAII ( Resource Acquisition Is Initialization )

RAII 的本质是 "契约", 是程序员与编译器之间的一个契约, 程序员承诺将资源的控制权交给一个栈对象, 编译器承诺无论发生什么 ( 正常退出、return、抛出异常 ) 保证一定会在该对象离开作用域时调用它的 destructor, 还有我们可以注意到 " 对象成员的初始化顺序 " 和 " 析构顺序 " 是严格对称的, 即初始化时是 base class -> member ( 按照 declare 顺序 ) -> 本 class 的 constructor 函数体, 最后摧毁这个对象的时候顺序是 本 class 的 destructor -> member ( 跟 declaration 顺序相反 ) -> base class destructor

这种严格对称性保证了: 如果一个对象的构造在途中心跳停止 ( 比如成员 B 的初始化抛出了异常 ), cpp 会自动按逆序销毁已经构造好的成员 ( 比如成员 A ) 而不会去销毁还没出生的成员, 这种 " 自动清理半成品 " 的特性只有靠 RAII 才能实现

然后还要引入所有权 ( ownership) 的概念:
A. 独占所有权 (Exclusive Ownership)
   这份资源只能由一个对象拥有, 这个对象负责管理这整个资源的全部生命周期, 比如 std::unique_ptr, 这个资源不能随意拷贝 ( 因为有两个拥有者就会释放两次报错 ), 但可以转移 (Move), 因为 mover 就像接力棒, 我传给你我就不再管了
B. 共享所有权 (Shared Ownership)
   这份资源可以由多个对象共同拥有, 比如 std::shared_ptr, 这个实现的逻辑是在内部维护一个计数器, 最后一个走的人 ( 计数器归零 ) 负责关灯 ( 释放内存 )
C. 观察权 (Observation/Weak Reference)
   我只是看看但是我不拥有它, 现代 cpp 里面这个是 nake pointer 应该做的事情, 或者 std::weak_ptr

** systematic methodology: 如何写出资源安全的代码

Gemini 把我零散的想法整理成了一个所谓的方法论, 这套方法论总结为 "所有权分层法"

1. 绝大部分场景: 做 "甩手掌柜", THE RULE OF ZERO!!!!
   尽可能让你的类成员本身就具备 RAII 属性, 比如 std::unique_ptr, std::vector, 这个时候我就不需要写 destructor / copy constructor / assignment operator, 非常安全, 这个就是非常著名的, 前面也提到的 the rule of zero

2. 必须手动管理时: 做 "合格的管家", THE RULE OF THREE/FIVE
   有时候你必须手动管理一些原始资源, 这个时候遵循 the rule of three/five, 一旦在 constructor 里面写了 new, 一定马上去写 destructor, assignment operator, 还有 copy constructor, 注意在写 assignment operator 还有 copy constructor 的时候注意资源是否被完整的转移/复制了, 因为有时候写 Derived Class 的 assignment operator 或者 copy constructor 的时候会忘记转移 Base class 的资源, 比如这次 lab 里面愚蠢的 triangle.cpp, 一个比较好的实践是在 Derived Class 里面显式调用 base class 的 copy constructor 或者 operator=, 一定要把这几个一套的东西实现好, 一定一定要记得!!!!!!!

3. 所有权语义显式化
   在代码里, 看到指针要立刻问自己: " 谁拥有它 ?", 如果是本 object 拥有这个对象, 那么就不应该是 MemberClass * member 这种裸指针, 应该使用 MemberClass member 这样的对象 ( stack 能正常管理 ), 或者只用 std::unique_ptr<MemberClass> ptr, 如果在代码里看见裸指针, 默认只有观察权而没有所有权

还有一些小细节, 是从上面的理解里面延伸出来的

1. 业务代码和资源管理代码分开
   资源管理应该是比较底层的 class 实现的, 底层的 class 应该实现 RAII 性质, 高层的业务代码直接使用底层的 RAII class 实现业务而不自己管理资源
2. 保证 class object 的 " 原子性 "
   尽量保证你拿到的对象是由 custom constructor 直接创建的第一手 object, 而不是经过 copy constructor 或者 operator= 经过二次处理的二手资源, 因为自己实现的 assignment operator 和 copy constructor 不一定好, 而直接由 custom constructor 直接创建的第一手 object 一定完整的正确的




* Useful Tools

记录一下使用到的有用的工具

** gcc
1. g++/gcc filename 直接默认编译, 得到 a.out
2. link .o 的时候, 直接 g++/gcc xxx.o xxx.o -o executable 就好了, -l 是用于连接 library 的


** vim
1. : 进入命令模式, !xxxx 表示执行外部指令, 然后返回到 vim
2. :term 是在 vim 里面分屏, 然后在一个屏里面打开 terminal


** gdb

这里总结一下常用的 gdb 使用命令

*** 1. 启动 gdb 的基本方法

|------------------------------+-------------------------------|
| 命令                         | 含义                          |
|------------------------------+-------------------------------|
| gdb [filename]               | 启动 gdb 并加载指定程序          |
|------------------------------+-------------------------------|
| (gdb) run [args]             | 在 GDB 中运行程序, 可带命令行参数 |
|------------------------------+-------------------------------|
| gdb --args ./filenmae [args] | 一行命令同时指定程序和参数        |
|------------------------------+-------------------------------|

*** 2. 断点设置相关命令

|-----------------------+-------------------+--------------------------------------|
| 命令                  | 命令缩写           | 含义                                 |
|-----------------------+-------------------+--------------------------------------|
| break [filename:line] | b                 | 在指定文件的指定行设置断点               |
|-----------------------+-------------------+--------------------------------------|
| break n               | b n               | 在当前文件的第 n 行设置断点              |
|-----------------------+-------------------+--------------------------------------|
| break class::function | b class::function | 在 class 的 member function 处设置断点 |
|-----------------------+-------------------+--------------------------------------|
| clear [filenmae:line] | None              | 移除指定位置的断点                      |
|-----------------------+-------------------+--------------------------------------|

*** 3. 程序执行控制命令

|------------+------+------------------------------------------------|
| 命令       | 缩写 | 含义                                           |
|------------+------+------------------------------------------------|
| run [args] | r    | 从 main 开始运行程序                             |
|------------+------+------------------------------------------------|
| continue   | c    | 继续执行程序直到断点                              |
|------------+------+------------------------------------------------|
| next       | n    | 执行下一行代码 ( 如果碰到函数不进入函数内部直接执行完 ) |
|------------+------+------------------------------------------------|
| step       | s    | 执行下一行/步代码, 如果碰到函数会进入函数内部         |
|------------+------+------------------------------------------------|
| finish     | fin  | 执行知道当前函数返回, 跳出函数                      |
|------------+------+------------------------------------------------|

*** 4. 查看代码和布局

|------------+---------------------------------------------|
| 命令       | 含义                                        |
|------------+---------------------------------------------|
| list       | 显示当前位置附近的代码                          |
|------------+---------------------------------------------|
| layout src | 打开 source code window, 实时显示当前执行的位置 |
|------------+---------------------------------------------|

*** 5. 查看重续状态和参数

|---------------------------+------+------------------------------------------------------|
| 命令                      | 缩写 | 含义                                                 |
|---------------------------+------+------------------------------------------------------|
| info args                 | None | 查看当前函数的参数                                      |
|---------------------------+------+------------------------------------------------------|
| info locals               | None | 查看当前函数内的局部变量                                 |
|---------------------------+------+------------------------------------------------------|
| print variable/expression | p    | 单音变量或者表达式的值, 比如 p sizeof(xxx), p list->head |
|---------------------------+------+------------------------------------------------------|
| backtrace                 | bt   | 查看函数调用的 stack                                   |
|---------------------------+------+------------------------------------------------------|
| frame n                   | None | 切换到指定的 stack frame                               |
|---------------------------+------+------------------------------------------------------|

*** 6. 常用快捷键

|--------+---------------|
| 快捷键  | 含义          |
|--------+---------------|
| Ctrl-l | 清屏          |
|--------+---------------|
| Ctrl-a | 移动到命令行开头 |
|--------+---------------|
| Ctrl-e | 移动到命令行结尾 |
|--------+---------------|

Ctrl-a 和 Ctrl-e 是古老的 unix 里面的 sheel 快捷键, emacs, shell, mac 原生支持


** make & makefile
make -j 可以开多进程编译, 会快非常多
不要手动 rm -rf, 使用 make clean 指令, 同时善用 Makefile 去简化一下 shell 指令

下面将从一个个例子入手, 讲解 makefile 的基本使用办法

这里是 cs225 课程推荐的 [[https://makefiletutorial.com/][makefile tutorial]], 我觉得写的非常好, 值得仔细研读, 我写的东西很多是对这个 makefile 教程的复述, 还有在做 cs225 lab 里面碰到的 makefile

*** make tutorial

*** lab_intro makefile
#+begin_src makefile
EXENAME = lab_intro
OBJS = main.o PNG.o HSLAPixel.o lodepng.o lab_intro.o

CXX = g++
CXXFLAGS = -std=c++1y -c -g -O0 -Wall -Wextra -pedantic
LD = g++
LDFLAGS = -std=c++1y -lpthread -lm

all : $(EXENAME)

$(EXENAME) : $(OBJS)
	$(LD) $(OBJS) $(LDFLAGS) -o $(EXENAME)

main.o : main.cpp lab_intro.h cs225/PNG.h cs225/HSLAPixel.h
	$(CXX) $(CXXFLAGS) main.cpp

lab_intro.o : lab_intro.cpp lab_intro.h
	$(CXX) $(CXXFLAGS) lab_intro.cpp

PNG.o : cs225/PNG.cpp cs225/PNG.h cs225/HSLAPixel.h cs225/lodepng/lodepng.h
	$(CXX) $(CXXFLAGS) cs225/PNG.cpp

HSLAPixel.o : cs225/HSLAPixel.cpp cs225/HSLAPixel.h
	$(CXX) $(CXXFLAGS) cs225/HSLAPixel.cpp

lodepng.o : cs225/lodepng/lodepng.cpp cs225/lodepng/lodepng.h
	$(CXX) $(CXXFLAGS) cs225/lodepng/lodepng.cpp


test: basic.o PNG.o HSLAPixel.o lodepng.o lab_intro.o
	$(LD) basic.o PNG.o HSLAPixel.o lodepng.o lab_intro.o $(LDFLAGS) -o test

basic.o : tests/basic.cpp tests/catch.hpp
	$(CXX) $(CXXFLAGS) tests/basic.cpp


clean :
	-rm -f *.o $(EXENAME) test out-*
#+end_src

非常好理解, 一个非常简单清晰的 makefile 结构, 注意不要把 tab 改成四个空格, tab 的 ascii 是 0x09, 空格的 ascii 是 0x20, 只不过一般的 tab 在 editor 里面被显示为四个空格 ( 当然也有 vim 这种显示为 8 个空格的 ), 要是不确定用的 tab 还是 4 x space, 你可以 :%!xxd 看一下, 然后再 :%!xxd -r 回来或者直接 normal mode 下 u 撤销, 你会看到 09 这样的, 这个就是 tab

*** lab_debug makefile
#+begin_src makefile
EXENAME = sketchify

MAIN_FILE = main.cpp

# Flags:
CXXFLAGS = -std=c++1y -c -g -O0 -Wall -Wextra -pedantic -ffloat-store
LDFLAGS = -std=c++1y -lpthread -lm
CXX = g++
LD = g++

# Discover files in dir...
CPP_FILES += $(wildcard *.cpp)
CPP_FILES += $(wildcard cs225/*.cpp)
CPP_FILES += $(wildcard cs225/lodepng/*.cpp)

OBJ_FILES += $(CPP_FILES:.cpp=.o)


# Discover files for testing...
TEST_CPP += $(filter-out $(MAIN_FILE),$(CPP_FILES))
TEST_CPP += $(wildcard tests/*.cpp)

TEST_OBJ = $(TEST_CPP:.cpp=.o)


# Rules
all: $(EXENAME)

$(EXENAME): $(OBJ_FILES)
	$(LD) $(OBJ_FILES) $(LDFLAGS) -o $(EXENAME)

test: $(TEST_OBJ)
	$(LD) $(TEST_OBJ) $(LDFLAGS) -o test

%.o: %.cpp %.h
	$(CXX) $(CXXFLAGS) $< -o $@

clean :
	-rm -f *.o $(EXENAME) test tests/*.o cs225/*.o cs225/lodepng/*.o
#+end_src

+= 是追加赋值操作符, 意思是在变量原有的值后面添加新的内容
#+begin_src makefile
# 初始时CPP_FILES是空的
CPP_FILES += $(wildcard *.cpp)          # 添加当前目录的.cpp文件
CPP_FILES += $(wildcard cs225/*.cpp)    # 再添加cs225目录的.cpp文件
CPP_FILES += $(wildcard cs225/lodepng/*.cpp) # 再添加lodepng目录的文件
#+end_src

其中 wildcard 是 n. [计]通配符 的意思, 在Makefile里是一个内置函数, 用于文件通配符匹配来返回所有匹配的文件名列表

#+begin_src makefile
$(CPP_FILES:.cpp=.o)
#+end_src

这里面的 : 是Makefile的变量替换引用语法, 意思是把CPP_FILES变量中所有以.cpp结尾的部分替换成.o, 比如 main.cpp -> main.o

#+begin_src makefile
TEST_CPP += $(filter-out $(MAIN_FILE),$(CPP_FILES))
#+end_src

filter out 函数是过滤掉的意思, 这个命令的意思是从 CPP_FILES 中排除 $(MAIN_FILE) 保留其他所有文件加入 TEST_CPP 里面

#+begin_src makefile
%.o: %.cpp %.h
	$(CXX) $(CXXFLAGS) $< -o $@
#+end_src

这里的 % 是Makefile的模式规则, %是通配符, 匹配任意字符串, 这个规则描述的是如何从一个 .cpp 文件和一个 .h 文件生成对应的 .o 文件
$<: 代表第一个依赖文件 ( 在这里是.cpp文件 )
$@: 代表目标文件 ( 在这里是.o文件 )
注意, 这里的 -o 仅仅表示 编译/链接/编译加链接 生成的文件名叫什么, 没有规定一定是要生成 executable image, 而这里的 CXXFLAGS 里面有 -c, 也就是 compile only, 所以肯定不会生成 executable image 的


** git
1. git branch
   git branch -a 可以看 all branch 名字, git branch -m/M branch-name: 重命名 / 强制重命名当前的 branch
   git branch branch-name 新建一个 branch name
2. git rm --cached filename
   把 staged 的东西放到工作区, 标记为 untracted


** svn
首先, svn 并不有用, 我只是因为要交作业不得不使用它才学的
1. svn commit
   傻逼玩意, 没有本地工作区和提交区的, 直接就 commit 到了 remote
2. svn update
   得到最新的 remote 的副本
3. svn revert file-name
   根据你的 svn, 把 file 变成上一次你 commit 的时候
4. svn diff
   类似 git diff


** linux cli command
*** dpkg
Debian PacKaGe
# 列出所有已安装的包
dpkg -l

# 查找特定包
dpkg -l | grep python

# 查看包的详细信息
dpkg -s libpng-dev

# 查看包安装的文件
dpkg -L libpng-dev

# 查看文件属于哪个包
dpkg -S /usr/include/png.h

# 安装本地.deb文件
sudo dpkg -i package.deb

# 安装并修复依赖
sudo dpkg -i package.deb
sudo apt-get install -f  # 修复依赖

# 卸载包（保留配置）
sudo dpkg -r package-name

# 完全卸载（包括配置）
sudo dpkg -P package-name

*** find
find [路径] [选项] [表达式]

# 在当前目录查找所有.cpp文件
find . -name "*.cpp"
# 在整个系统查找libpng.so（2>/dev/null隐藏错误）
find / -name "libpng.so" 2>/dev/null
# 不区分大小写查找
find . -iname "*.CPP"  # 会找到.cpp、.CPP、.Cpp等
# 只找目录
find . -type d -name "build*"
# 只找普通文件
find . -type f -name "*.o"
# 找符号链接
find . -type l
# 7天内修改过的文件
find . -mtime -7
# 30天前修改过的文件
find . -mtime +30
# 今天修改过的文件
find . -mtime 0
# 按访问时间找
find . -atime -1  # 24小时内访问过的

*** file
file + filename 可以查看文件相关信息

(base) zhb:/usr/lib/x86_64-linux-gnu$ file libc.so
libc.so: ASCII text
(base) zhb:/usr/lib/x86_64-linux-gnu$ file libc.so.6
libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=274eec488d230825a136fa9c4d85370fed7a0a5e, for GNU/Linux 3.2.0, stripped
(base) zhb:/usr/lib/x86_64-linux-gnu$
*** ldd
Library DepenDency

# 查看可执行文件的依赖
ldd /bin/ls

# 查看共享库的依赖
ldd /usr/lib/libpng.so

# 查看自己编译的程序
ldd ./myprogram
ldd /bin/ls
# 输出：
# linux-vdso.so.1 (0x00007ffd...)
# libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1
# libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
# /lib64/ld-linux-x86-64.so.2

# 解释：
# => 左边：程序需要的库名
# => 右边：系统找到的实际文件路径
# 没有 =>：特殊虚拟库
# not found：找不到的库（有问题！）

# 1. 检查缺失的库
ldd ./myapp | grep "not found"

# 2. 查看库的完整路径
ldconfig -p | grep libpng

# 3. 设置库路径
export LD_LIBRARY_PATH=/my/libs:$LD_LIBRARY_PATH
ldd ./myapp  # 再次检查

