#+title: Note

记录一下 cs225 ( 基于 cpp 的数据结构 ) 的学习

中间会夹杂很多其他学到或者用到的东西, 不一定跟 cs225 有关, 比如说在 cs225 过程中用到的 cli 工具, shell, vim 这些奇怪的东西

我认为这个课程是一个很好的熟悉 linux 还有对应开发环境, 开发工具, 底层概念的机会, 所以会记录很多这些东西

对一些 lecture 的内容记录可能不多, 有些内容不知道怎么命名就瞎起名字了

其实似乎应该叫做 linux 下面的开发体验记录以及 cs225 课程笔记, 而不只是 cs225 课程笔记

这个 note 并不全面, 甚至可能不成文, 他的作用主要是让我 keep focused, 不会事无巨细的记录每一个知识点, 有一些我会了的东西不会记录, 有一些不会的但是我觉得太难了, 不足以清晰的使用文字说明清楚的我也不会记录 ( prefer 纸质, 可能会上传 pdf )

* lecture 01

Encapsulation 封装, 是指分开 interface 和 implementation

namespace 解决复杂工程里面同名函数问题, 可 using namespace, 但是建议不要, 要习惯 namespace::xxxxx 这种 style, 比如 std::cout

constructor, default constructor ( 如果没写 constructor 会默认生成一个 automatic default constructor, 这个 constructor 会给该 class 里面所有东西赋默认值, 比如 float/double 给0.0, int 給0, pointer 给 NULL ), 自定义的 constructor, constructor 可以有很多个

指针 re-cap

header file 记得 #ifndef XXXX_H 来避免重复 include

convention 里面, xxx.h 放 declaration, xxx.c/xxx.cpp 里面放 definition / implementation


* 一些有用的知识

ECE220 / ECE120 / STM32 legacy

** 编译
*** 1. preprocess
主要是把 #include xxx.h 这种东西替换为 xxx.h source file 里面的文本, 对 macro 进行文字替换
比如说 #include "xxx.h" 在 preprocess 阶段做的就是把 xxx.h 文件的文本复制过来, 替换 #include "xxx.h" 这一行
我们上面写 guard, 即 #ifndef XXXX_H 的原因就是, 你可能在一个 source file 里面 include 了同一个文件多次, 这样你重复 declare 了一个东西多次, 可能会报错, 你加这个东西, 就会先判断, 然后如果没 include 过再 include, 保证一个文件只被 include 一次

*** 2. compile
编译器把 xxx.c 文件独立编译成对应的机器码 .o 文件, 每个 .c 文件独立编译, 未实现但是有声明是可以的, 只要语法正确即可
这个意思是说, 假如你在 xxx.h 里面写了某个函数的 declaration, 然后在 yyy.c 里 #include "xxx.h", 然后你在 xxx.c 里面实现了 xxx.h 里面 declare 的函数, 你在编译 yyy.o 的时候, yyy.c 里面并没有这个 xxx.h 里声明的函数的实现, 即使你不写 xxx.c 这个编译也是成功的

在 vim 里面查看二进制文件 ( elf 格式: :%!xxd, %表示全局, !表示外部命令, xxd 是一个解析二进制码的工具 ), 是时候对 vim 再进一步了

编译常见 option
a. -std=gnu99: 使用什么规范什么标准
b. -c: compile only, 不 link
c. -g: enable gdb debug, debug 选项
d. -O0: 优化与否, -O0 表示不优化便于 debug, 数字越大表示优化的越厉害
e. 关于容错和警告: -Wall 是 warning all 的意思, 警告大部分错误 ( 尽管声称是 warning all ), -Wextra 额外警告, 比 -Wall 更多, -pedantic 严格遵循标准 ( 学究 )

*** 3. link
把各个 .o 文件链接起来, 生成 executable image, 这个时候会有什么重复定义, 声明了没找到这些问题
比较 tricky 的地方是, 即使你在 xxx.c 里面不 #include xxx.h ( xxx.c 里面实现了 xxx.h 里面声明的函数 ), 编译器还是可以正确 link 的, 只不过没人这么干

当然, 很多时候在写 gcc 指令的时候, 我们不分开 compile 和 link, 两个是一起的

常见指令: gcc ..... -o executable, -o 后面的名字是 executable image, 然后 ./executable 就可以执行命令了
g++ -std=c++1y  -lpng -lpthread -lm xxx.o o executable
-lpng 前面的 -l 表示 lib, 然后 png 是系统 lab 库, 一般在 /usr/lib/x86_64-linux-gnu 这个里面, 里面有 .so 这种动态库 ( ros 2 control 里面用的那个 ), 也有 .a 这种静态库, 我们可以使用 file 指令查看这个东西的性质, 比如:
(base) zhb:/usr/lib/x86_64-linux-gnu$ file libImath-3_1.so.29
libImath-3_1.so.29: symbolic link to libImath-3_1.so.29.8.0

*** make 和 Makefile
贴吧上看见一个很好的介绍 https://tieba.baidu.com/p/591519800
要会自己独立写基本的 Makefile, 要能看懂并且在已有的基础上修改复杂的 Makefile, 这玩意实际上可以调用 shell 指令还是很 powerful的,
还有用于更复杂的 cmake
东西太多了暂时就不记录了, 经常用经常写自然就会了, 开个坑专门记录这些工具吧, 放在这个文件的最后

** memory
以 stm32 的内存设计为例, lc 3 内存位置忘记了懒得去查, 但是 lc3 也是和 stm32 的内存设计差不多的, stm32 的内存还更真实一点

哦, 找到 lc3 memory setting 了: https://github.com/hanbinzheng/ece220/blob/main/LC3_BASICS/memory_layout

这个是一个 stm32 h723 link 使用的 .ld 脚本: https://github.com/hanbinzheng/infantry/blob/main/STM32H723XG_FLASH.ld

关于 stm32 h7 芯片物理上有哪些存储, 这些存储有哪些特点, 以及在 memory 里面这些存储是如何规划的
下面的东西在声明我有哪些地方是合法的, 内存的哪些地方是可以放东西的
FLASH / ROM 断电不丢失, RAM 断电丢失, SRAM: Static RAM, MCU 里面基本都是 SRAM, SRAM 的 static 的意思是只要通电数据就不会丢失

TCM: Tightly Coupled Memory, 它是直接挂在 CPU 内部总线上的存储空间, 专门为 cpu 服务绕过了普通外设总线(AHB/APB), cpu 访问/写极快, 他们也算 RAM, 断电也丢失

注意, FLASH / ROM 不是不能写, 我们可以通过烧录去写, 下面说的不能写 ( 不能 w ) 是指不能在程序运行的时候快速的写

下面是简化版的 .ld 文件, 用于展示内存布局的

#+begin_src conf
/* Entry Point */
ENTRY(Reset_Handler)

/* Highest address of the user mode stack */
_estack = ORIGIN(DTCMRAM) + LENGTH(DTCMRAM);    /* end of RAM */
/* Generate a link error if heap and stack don't fit into RAM */
_Min_Heap_Size = 0x200;      /* required amount of heap  */
_Min_Stack_Size = 0x400; /* required amount of stack */

/* specify memory sections */
MEMORY
{
DTCMRAM (xrw) : ORIGIN = 0x20000000, LENGTH = 128K  /* DTCM, CPU 专属访问读写极快, Dtat TCM, 主要放的是 CPU 高频访问的数据 */
RAM_D1  (xrw) : ORIGIN = 0x24000000, LENGTH = 320K  /* SRAM Region 1, rwx 都行, 可被 CPU/DMA/外设访问, 访问延迟大于 TCM  */
RAM_D2  (xrw) : ORIGIN = 0x30000000, LENGTH = 32K   /* SRAM Region 2, 同上 */
RAM_D3  (xrw) : ORIGIN = 0x38000000, LENGTH = 16K   /* SRAM Region 3, 同上 */
ITCMRAM (xrw) : ORIGIN = 0x00000000, LENGTH = 64K   /* ITCM, CPU 专属访问极快, Instruction TCM, 极端实时的代码指令 */
FLASH   (rx)  : ORIGIN = 0x08000000, LENGTH = 1024K /* FLASH, 只能 rx, 不能 w, 因此一般放不会修改的东西, 比如常量, 程序代码, 向量表 */
}

/* Define output sections */
SECTIONS
{
        /* The startup code goes first into FLASH */
        .isr_vector : { /* 中断向量表, 在 FLASH 开头 */ } >FLASH

        /* The program code and other data goes into FLASH */
        .text : { /* 所有程序, .text 和 .text* 的都放在这里 */ } >FLASH

        /* Constant data goes into FLASH */
        .rodata : { /* 常值, .rodata 和 .rotata*, ( constants, strings, etc. ) */ } >FLASH

        /* ARM 特定段, 没研究过, 但是这俩都是 READONLY 的, 也在 FLASH */
        .ARM.extab : { /* ARM异常处理表 */ } >FLASH
        .ARM : { /* ARM异常索引表 */ } >FLASH

        /* 给 cpp 的, 我的 stm32 里面是纯 c, 没有 cpp, 没研究过 */
        .init_array : { /* C++静态构造函数数组 */ } >FLASH
        .fini_array : { /* C++静态析构函数数组 */ } >FLASH

        /* C/CPP 初始化, 没研究过 */
        .preinit_array (READONLY) : { /* C++/C 运行时初始化机制的一部分，用于在 main 函数之前执行初始化代码 */ } >FLASH

        /* Initialized data sections goes into RAM, load LMA copy after code */
        /* 运行时在 DTCMRAM 中, 加载时在 FLASH 中, 启动时把 FLASH 中的初始值 memcpy 到 DTCMRAM 中的 .data 对应位置 */
        .data : { /* 有初始值的 "静态存储期对象", 如全局变量, static 全局, static 局部 * / } >DTCMRAM AT> FLASH

        /* Uninitialized data section */
        .bss : { /* 没有显式初始化的静态存储期对象, 不占 Flash 直接放 DTCMR, 如未初始化的全局/static 全局/static 局部 */ } >DTCMRAM

        /* buffer specified for dma1 and dma */
        .dma12_buffer (NOLOAD) : { /* DMA 没有办法访问 DTCM, 所以给开一个地方在 SRAM 上面 */ } >RAM_D2

        /* User_heap_stack section, used to check that there is enough RAM left */
        ._user_heap_stack : { /* user 使用的 heap 段, 用于 malloc */ } >DTCMRAM

}
#+end_src

你会发现这里没有 stack 的地方, 这个是因为 stack 不是预先规定的, stack 是 CPU 的 SP 寄存器 + RAM 空间
规定一下 convention, 一般称地址较大的为高地址, 地址较小的为低地址, 比如说 0x0010 和 0x1000, 0x1000 算高地址, 0x0010 算低地址
stack top: 当前 stack pointer 指向的位置, stack bottom: stack 被分配的那一端的边界
主流 CPU 上, stack 是从高地址向低地址生长, PUSH 代表 SP 减少, POP 代表 SP 变大,
_estack 代表 stack 的分配边界, 最高的那个地址, stack pointer 从 _estack 这个地址开始向低地址生长, 有一些恶心的 bug 比如说 stack 长到了 heap 里面
stack overflow: stack 踩到了 heap 和 .bss 段

STM32H723内存映射:
#+begin_src txt
0x0000 0000 ┌─────────────┐ 别名区 ( 自动映射到Flash或RAM )
            │             │
0x0800 0000 ├─────────────┤ Flash起始 ( 程序在这里 )
            │   .text     │ ← 代码段
            │  .rodata    │ ← 只读数据
            │ .data初始化值 │
0x0810 0000 ├─────────────┤
            │             │
0x2000 0000 ├─────────────┤ RAM起始
            │   .data     │ ← 已初始化变量 ( 从Flash复制过来 )
            │   .bss      │ ← 未初始化变量 ( 清零 )
            │    堆(heap) │ ← malloc 使用
            │             │
            │    _estack  │ ← stack base/bottom, RAM 结束, stack pointer 从这里开始向低地址生长
0x2008 0000 └─────────────┘
#+end_src

** variable 相关
关于变量存储位置, 作用域, 生命周期, 非常重要

1. 一般局部变量, 即函数内部使用的一般变量 (无static关键字), 作用域是该函数体内部, 储存位置在 run time stack 上面, 生命周期是函数被调用时创建/初始化, 到函数 return 时生命周期结束, 比如 void function(int a, int b) {} 里面的 c 这个局部变量
   这个在 ECE220 写 run time stack 的 lc3 汇编的时候已经学的很明白了
2. static 局部变量, 一般的局部变量加上一个 static 关键字, 比如. void function(int a, int b) { static int c = a + b; }, 这个变量的作用域也是该函数内部, 即只有该函数内部才能访问这个变量, 但是这个变量的生命周期是整个程序执行的时间, 主要放在 .data/.bss 段 ( 取决于有没有初始化 )
3. 全局变量, 如直接写在 .c 文件里 ( 不在任何一个函数内部 ), 作用域是全部程序 ( 注意, 如果 local variable 和 global variable 重名, 那在函数内使用的是 local 的 ), 即任何一个程序都可以访问 ( 使用这个全局变量的程序要有 extern 关键字声明这个变量存在 ), 否则无法直接使用, 这个东西的储存位置在 .bss 或者 .data 段 ( 取决于有没有初始化 ), 生命周期是整个程序的执行时间, 注意, 全局变量的名字不能重复
4. static 全局变量, 跟全局变量唯一的区别是作用域被限定为了这个 .c 文件, 只有这个文件里的函数可以使用

** c 指针数组类型判断

我们要从运算符的角度去理解 c 里面的类型判断, 根据变量的优先级判断

先说明白一下, a[i] 里面的 [] 运算符相当于 *(a + i), 他的优先级是高于 * 运算符的

1. int *p;
   对变量 p 进行 * 运算, 得到的是 (*p), 也就是说读取 p 这个地址里存的东西得到的是一个 int, 所以 p 是一个指向 int 的指针

2. int a[10];
   0 ～ 9 里面的任意一个数字 i, 对变量 a 进行 a[i] 运算, 得到的是一个int, 所以说 a 是一个长度为10的数组

3. int *a[10];
   运算优先级上 [] 高于 *, 因为 a[i] 是*(a + i), 这里有一个括号, *(*(a + i)) 得到的是一个 int, 所以说 a 首先是一个数组, 然后对 a 进行 (*(a + i)) 得到的是 int * 类型, 即指向 int 的指针, 然后再 *, 得到 int, 所以说 a 是一个存了10个int* 变量的数组

4. int (*p)[10];
   这里的时候我们先进行的是 * 这个运算, 对 (*p) 得到的结果在进行 [] 运算, 即(*p)[i] 得到的是 int, 所以说 (*p) 是一个数组的首地址, 或者说是一个数组, p就是一个指向数组的指针

   也就是说大概是这样的, int a[10];, 然后 int (*p) [i] = &a;

5. 往下叠 buff...
   上面差不多讲清楚了, 然后就可以根据运算的优先级, 爱咋叠 buff 咋叠 buff 了

** c关键字和 GCC 提示指令
1. extern
   用于声明全局变量的

   比如说在 xxx.c 里面写了 extern int a;, 声明这里有一个全局变量 a, 但是在别的地方不知道在哪里 ( 可能在别的文件, 也可能在这个文件的后面 ), 但是我 extern int a; 声明之后, xxx.c 后面的内容就可以使用 a 这个变量了

   我们有时候会这样 (这个实际上是使用全局变量的标准模式), 在 xxx.h 里面写 extern int a;, 然后在 xxx.c 里面写 int a = 0;, 当你在其他 .c 文件里 #include "xxx.h" 之后, 经过 preprocess, extern int a; 这个声明会出现在其他文件里, 让其他文件可以访问这个全局变量, 在 xxx.c 里, 你 #include "xxx,h", preprocess 的时候有了 extern int a; 这个声明, 然后你在后面写 int a = 0;, 给了变量 a 这个定义

2. static
   表示 local, 表示这个东西仅属于当前 函数/文件, 其他 函数/文件 用不了, 这个使得我们可以重名, 比如说在 xxx.h 里面写 static int add(int a, int b) {return a + b};, 然后不同 #include "xxx.h" 的 c 文件都有这个 add 函数的 local 版本, 不会出问题, 但是如果你没有写 static, 就会出现很多个 add 函数 ( 没有 static 的时候, 这个函数默认是 global 的 ), 这个时候编译器就会报错

   static 的 variable 在 .bss 或者 .data 段, static 的函数在 .text 段, 但是只有该函数/文件可以使用

3. inline
   用于内联, 内联是一种编译器优化，建议编译器把函数调用替换为函数体本身

   如果没有内联                                      内联之后
   int square(int x) { return x * x; }             inline square(int x) {return x * x;}
   int y = square(5);                              int y = square(5);

   // 编译后:
   // call square  ; 调用函数                        // mov y, (5 * 5)   ; 直接计算结果，不调用函数
   // mov result to y

   inline 的用法:
   (1) 头文件定义函数, 编译的时候就直接展开了, 不会出现我们在 2. 里面提到的有多个函数定义的问题
   (2) 性能优化, 因为直接展开了, 没有函数调用开销, 适合用来写小函数, 比 #define 这种 macro 安全, 而且性能几乎没有区别, 我习惯用 static inline 代替有逻辑的 macro

4. const

   const 表示是指编译器会阻止对该变量做语意上的修改, 如果你通过一些奇技淫巧用指针绕过的话, 还是可以改的

   const 修饰它左边最近的东西, 如果左边没, 就修饰它右边的, const int a; 和 int const a; 完全一样

   指针相关的 const, 这个很容易搞混

   指向 const 的指针
   #+begin_src c
    const int *p;   // 或 int const *p;

    int x = 5;
    int y = 6;
    p = &x;
    ,*p = 10;   // 编译错误，指向的数据不能改
    p = &y;    // 指针本身可以改
   #+end_src

   const 指针 ( 指针本身不可改 )
   #+begin_src c
    int * const p = &x;
    *p = 10; // 可以修改指向的值
    p = &y; // 指针本身不能修改
   #+end_src

   指向 const 数据的 const 指针 ( 双重 const )
   #+begin_src c
   const int * const p = &x;
   #+end_src

   在 cpp 里面, 这个也是类似的
   #+begin_src cpp
   PNG const & a = ...;
   #+end_src
   这里的 const 修饰的是 PNG, 然后从 a 开始往左读, 是 reference to const PNG, 不能改变这个 PNG 的值, 这个是用来传参的一个重要办法, 避免拷贝, 也避免改变传如的参数

   还有一个 const 的例子
   #+begin_src cpp
   bool operator==(PNG const& other) const;

   // 等价形式
   bool operator==(PNG const& other, PNG const* const this);
   // PNG const * const this, 左边的 const 修饰 PNG, 表示不改变 PNG, 右边的 const 修饰 (PNG const *), 表示不改变这个指针
   #+end_src

5. __attribute__

   这个不是 c 的关键字, 是给 GCC 的提示和指令, 是 GCC 的特性而不是 c 语言的特点

   __attribute__ 是 GCC 的编译器指令, 用于: 给编译器额外的优化提示/给编译器额外的优化提示/启用特定的语言扩展/提供调试信息

   因为我用的也不多, 我只在处理 DMA 无法 access DTCM 的时候手动放置 buffer 的时候用了一次, 所以这里多放了几个例子, 虽然我不觉得这些例子会用到, 但是别人用到的时候要看得懂

   基本语法
   ,#+begin_src c
    // 单个属性
    type name __attribute__((attribute_name));

    // 多个属性
    type name __attribute__((attr1, attr2, attr3));

    // 函数属性
    return_type func_name(args) __attribute__((attribute_name));
   #+end_src

   函数优化提示
   #+begin_src c
    // 1. 内联控制
    void __attribute__((always_inline)) fast_func() { ... }
    void __attribute__((noinline)) big_func() { ... }

    // 2. 热/冷函数提示
    void __attribute__((hot)) critical_path() { ... }   // 经常执行
    void __attribute__((cold)) error_handler() { ... }  // 很少执行

    // 3. 纯函数/常量函数
    int __attribute__((pure)) calculate(int a, int b) {
         // 纯函数：只依赖参数，无副作用
         return a + b;
    }
    double __attribute__((const)) pi() {
         // 常量函数：相同输入永远相同输出，且不读全局变量
         return 3.1415926;
    }

    // 4. 不返回函数
    void __attribute__((noreturn)) panic() {
         while(1);  // 永不返回
    }
   #+end_src

   内存布局控制
   #+begin_src c
    // 1. 指定段
    uint8_t buffer[1024] __attribute__((section(".dma_buffer")));
    const char str[] __attribute__((section(".rodata.custom")));

    // 2. 对齐控制
    uint32_t data __attribute__((aligned(32)));  // 32字节对齐
    struct S __attribute__((aligned(64))) { ... };  // 结构体对齐

    // 3. 打包结构体（取消填充）
    struct __attribute__((packed)) Packet {
         uint8_t cmd;
         uint32_t data;  // 通常会有3字节填充，packed取消填充
    };

    // 4. 弱符号（允许覆盖）
    int __attribute__((weak)) default_value = 0;
    void __attribute__((weak)) default_handler() { ... }
   #+end_src

** cpp 入门特性

这里主要讲一下 ECE 220 用到的 cpp 入门的一些特性

*** 初始成员列表

在创立并初始化一个对象的时候, 一般流程是:
1. 分配内存 ( 为整个 object )
2. 初始化 base class 部分 ( 如果有 inheritance )
3. 按照声明顺序初始化所有数据成员 ( 始化的顺序是成员的声明顺序, 如果有初始成员列表, 使用初始成员列表的值进行初始化, 没有则默认  )
4. 执行构造函数体 ( 注意, 是构造函数题, 不是构造函数 )

初始成员列表性能上比赋值的办法快, 而且对于一些 const 的变量, 只能使用初始成员列表来做, 还有 reference 也只能用初始成员列表的办法初始化 ( reference 是 "语意上的一个 object ", 只有在初始化的时候表示 "指向哪个对象/内存地址", 后面的 = 都是改变那片内存地址上的对象的值 )

#+begin_src cpp
class MyClass {
private:
    std::string name;     // class object
    int id;               // 基本的类型
    const int version;    // const
    std::vector<int>& ref_vec;  // reference

public:
    // 在构造函数体内赋值
    MyClass(std::string n, int i, int v, std::vector<int>& vec) {
        name = n;          // name已经调用了 name 的默认构造函数, 即已经初始化了, 这里实际是 operator= 赋值
        id = i;            // 基本类型重新赋值, 影响比较小
        // version = v;    // const 的变量已经被初始化了, 这里是赋值, 但是 const 不能赋值
        // ref_vec = vec;  // reference 可以理解成 const 指针, 或者根本的, 就没有 "reference" 这种类型, reference 就是对象本身, 哪个对象是初始化的时候就确定了
    }

    // 使用初始成员列表
    MyClass(std::string n, int i, int v, std::vector<int>& vec)
        : name(n),         // 直接调用拷贝构造函数
          id(i),           // 基本类型直接初始化
          version(v),      // const attribute 初始化, 必须初始成员列表
          ref_vec(vec) {   // reference attribute 必须有初始化
        // ........
    }
};
#+end_src

#+RESULTS:

在底层, 赋值初始化会让整个再多一次赋值的操作, 效率会低

*** reference

reference 就是指向的那个 object, 只是语意上换了一个东西表示, 这让你可以操作底层的东西而无需使用指针, 你可以把它在底层理解成一个 const pointer ( int * const, 而不是 int const *, 换句话说, 指向哪里不能再变了, 但是指向的地址存的值是可以改变的 ), 但是实际上并没有那么一个变量, 编译器在看到 reference 变量的时候就只会把它当作 "该对象本身", 想象中等同于一个 * pointer 的感觉, 但是要记住实际上没有那么一个临时pointer变量


#+begin_src cpp
int main() {
	int a = 0;
	int & b = a;

	std::cout << "&a: " << &a << std::endl;
	std::cout << "&b: " << &b << std::endl;

	b = 100;
	std::cout << "a = " << a << std::endl;
	std::cout << "b = " << b << std::endl;

	return 0;
}
#+end_src

结果是:
#+begin_src bash
zhb ~/Desktop % ./a.out
&a: 0x16bcfed88
&b: 0x16bcfed88
a = 100
b = 100
#+end_src

这就是为什么我们要在初始化成员列表里面初始化 reference 了, 因为初始化的时候流程是:
1. 分配空间
2. 如果有 inheritance, 那么初始化 base class 的
3. 对于本 class 的每一个 attribute 进行默认初始化 ( reference 这里被初始化了, 但是默认初始化的时候没有指定对象是什么, 所以这个 reference 是没法用的 ), 你可以通过初始列表去干预这里, 比如说委托构造, 或者初始化成员列表
4. 执行函数体

*** operator

在 cpp 里, 运算符重载就是成员函数或普通函数, 只有名字是特殊的

#+begin_src cpp
return_type operator<op>(parameter_list) [cv] [ref] [noexcept];
#+end_src

这个没有任何神奇的, 只是一个函数名叫 operator<op> 的函数, 其中这个 operator 的左值是这个 operator 对应的 object, 然后这个右值是传入这个 method 的 arguments

比如
#+begin_src cpp
// operator function declaration
bool PNG::operator==(PNG const& other) const;

// you can write
bool c = (a == b); // a and b are PNG type objects

// this is equivalent to
bool c = q.operator==(b);
#+end_src

[cv] (const / volatile): 最常见的是 const, 如果你写 bool operator==(const Sphere& other) const;, 最后的那个 const 意味着这个运算符不会修改当前对象, 如果你有一个 const Sphere s1，它只能调用带 const 修饰的成员函数/运算符

[ref] (& / &&) —— 引用限定符 (cpp11): 它限制了运算符是给“左值”用还是“右值”用, &: 只能由 lvalue 调用, &&: 只能由rvalue调用

[noexcept] (C++11): 告诉编译器这个运算保证不会抛出异常, 编译器看到这个后会进行极致优化, 对于移动构造函数和移动赋值运算符来说加上 noexcept 非常关键

*** inheritance

忘记了, 暂时还没碰到, 先放着, 碰到了学了再写

*** function overload / virtual function

忘记了, 暂时还没碰到, 先放着, 碰到了学了再写


* lecture 02

** more on constructor

可以在 default constructor 里面调用 custom constructor 去完成 initialization, 叫做委托构造函数 ( delegating constructor )

#+begin_src cpp
#include "sphere.h"
namespace cs225 {
    // delegating constructor: 委托构造函数
    Sphere::Sphere() : Sphere(1.0) {} // 在 initialization list 的位置调用 custom constructor

    Sphere::Sphere(double r) : r_(r) {
        // other logic
    } // custom constructor
}
#+end_src

讲一下这个语法
Sphere::Sphere() : Sphere(1.0) {} 里面最右边的那个冒号叫做: 构造函数初始化列表 ( constructor initializer list ), 是 cpp 里面唯一一个可以在对象 "出生瞬间" 初始化东西的地方, 相当于是说他定义了, 在这个对象一旦被声明和初始化的时候的 behavior 是什么

#+begin_src cpp
Constructor
  : initializer1,
    initializer2,
    ...
{
    // constructor body
}
#+end_src

这里面的 initializer 可以是下面两者之一: 1. list initialization, 2. delegating initialization

但是你只能选择 list initialization 或者 delegating initialization, 不能同时两者

再强调一遍 cpp object 的初始化过程:
1. 分配内存
2. 执行 constructor initializer list 的相关内容 ( 只能在 initializer list 的地方干预, 否则就是执行每一个东西的默认的初始化 )
3. 执行构造函数体 {}

这个冒号后面的地方是我们唯一可以干预的地方

凡是 "对象一出生就必须确定的东西", 只能写在 : 后面, 比如 const, reference, delegating construction, base class object

注意区分初始化成员列表和委托构造函数, 初始化成员列表和委托构造函数的语法一摸一样, 但是你只能选择初始化成员列表或者委托构造函数中的一种, 一个是直接初始化成员, 另一个是委托给另一个构造函数

体会一下 cpp 的哲学 RAII:
RAII = Resource Acquisition Is Initialization
资源的获取 = 对象的初始化, 资源的释放 = 对象的析构

** stack & heap, RAII

一个从低地址向高地址增长 ( heap ), 一个从高地址向低地址增长 ( stack )

注意, cpp 里面不用 malloc 和 free, 用的是 new 和 delete, 其中 new 和 malloc 还不一样, new 分配地址 + 调用初始化函数, 但是 malloc 是只有分配地址, delete 会调用 destructor 同时释放内存

pain point 是如果你忘记了 delete 会内存泄漏, 如果 new 之后代码抛出错误, 还没运行到 delete 内存也会泄露, 还有对同一个指针 delete 两次会导致崩溃

从 cpp11 开始 ( 并在 Cpp14/17 中完善), 我们提倡 RAII ( 资源获取即初始化 ), 简单说就是用一个对象来包装原始指针, 当这个对象"死"掉 ( 离开作用域 ) 时, 它会自动在析构函数里帮我们调用 delete
RAII: Resource Acquisition Is Initialization,
资源获取 = 对象初始化, 资源释放 = 对象析构,
RAII 的核心只有一句话: 把资源的生命周期绑定到一个栈对象的生命周期上

当然现代有了 smart pointers, 比如 unique_ptr, 还有 shared_ptr, 这个以后碰到了再写

** memory location 重温

重温了一下 run time stack, 以及使用 lldb (md, gdb 不支持这个, 绷不住了) 去看了一下 undefined behavior, 下面是这个例子

cpp 文件, 这个 Sphere 的 object 是在 run time stack 上面被创建的, 在调用下面的函数的时候这个 stack 大概率已经被 clear 了
#+begin_src cpp
#include "sphere.h"
#include <iostream>

using namespace cs225;

Sphere *CreateUnitSphere() {
  Sphere s(1);
  return &s;
}

int main() {

  Sphere *s = CreateUnitSphere();

  double r = s->getRadius();
  std::cout << "r: " << r << std::endl;
  double v = s->getVolume();
  std::cout << "v: " << v << std::endl;

  return 0;
}
#+end_src

compile and run ( on mac )
#+begin_src zsh
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % g++ -g -c sphere.cpp
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % g++ -g -c sphere-badCreate.cpp
sphere-badCreate.cpp:8:11: warning: address of stack memory associated with local variable 's' returned [-Wreturn-stack-address]
    8 |   return &s;
      |           ^
1 warning generated.
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % g++ sphere.o sphere-badCreate.o -o bad_create
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % ./bad_create
r: 1
v: 0
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 %
#+end_src

在 ubuntu24.04 上面 compile + run
#+begin_src bash
(base) zhb:~/Desktop/code-lecture02$ g++ -c -g sphere.cpp
(base) zhb:~/Desktop/code-lecture02$ g++ -c -g sphere-badCreate.cpp
sphere-badCreate.cpp: In function ‘cs225::Sphere* CreateUnitSphere()’:
sphere-badCreate.cpp:8:10: warning: address of local variable ‘s’ returned [-Wreturn-local-addr]
    8 |   return &s;
      |          ^~
sphere-badCreate.cpp:7:10: note: declared here
    7 |   Sphere s(1);
      |          ^
(base) zhb:~/Desktop/code-lecture02$ g++ sphere.o sphere-badCreate.o -o bad_create
(base) zhb:~/Desktop/code-lecture02$ ./bad_create
Segmentation fault (core dumped)
(base) zhb:~/Desktop/code-lecture02$
#+end_src

gdb 去查看发生了啥
#+begin_src bash
Breakpoint 1, main () at sphere-badCreate.cpp:13
13        Sphere *s = CreateUnitSphere();
(gdb) info locals
s = 0x7ffff7cb738f <_GLOBAL__sub_I_eh_alloc.cc(void)+431>
r = 6.9533490978045684e-310
v = 6.9533558074180129e-310
(gdb) print &s
$1 = (cs225::Sphere **) 0x7fffffffddc8
(gdb) print &r
$2 = (double *) 0x7fffffffddd0
(gdb) print &v
$3 = (double *) 0x7fffffffddd8
(gdb) step
CreateUnitSphere () at sphere-badCreate.cpp:6
6       Sphere *CreateUnitSphere() {
(gdb) s
7         Sphere s(1);
(gdb) print &s
$4 = (cs225::Sphere *) 0x7fffffffdda0
(gdb) finish
Run till exit from #0  CreateUnitSphere () at sphere-badCreate.cpp:7
0x00005555555552e1 in main () at sphere-badCreate.cpp:13
13        Sphere *s = CreateUnitSphere();
Value returned is $5 = (cs225::Sphere *) 0x0
(gdb) print s
$6 = (cs225::Sphere *) 0x7ffff7cb738f <_GLOBAL__sub_I_eh_alloc.cc(void)+431>
(gdb) print *s
$7 = {r_ = 6.8523770472794107e+38}
(gdb) s
15        double r = s->getRadius();
(gdb) print r
$8 = 6.9533490978045684e-310
(gdb) s
cs225::Sphere::getRadius (this=0x0) at sphere.cpp:13
13          return r_;
(gdb) s

Program received signal SIGSEGV, Segmentation fault.
0x0000555555555208 in cs225::Sphere::getRadius (this=0x0) at sphere.cpp:13
13          return r_;
(gdb) s

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
#+end_src

他得到的返回值甚至不是原来的 stack 地址, 只能说 UB 是真的 Undefined Behavior
还有这里的 stack 的分布并不是真的是 local variable 先声明的先 push, 呃, 这个, emm, 只能说比较灵活吧, 但是有的地方是先声明先分配的

我们再试验一下这个 stack 的问题, 把他 print 出来
macbook 上面
#+begin_src bash
s->getRadius(): 4.17291e-314
&s (main): 0x16d7d2d18
 s (main): 0x16d7d2cb8
&r (main): 0x16d7d2d10
 r (main): 4.17291e-314
&v (main): 0x16d7d2d08
 v (main): 0
#+end_src

只能说两个表现很不一样了, 两个东西的 UB 还有 stack behavior 完全不一样呢, UB 就是完全 Undefined, 啥都有可能发生 ( compiler 的 preference 了 )

我还发现 ubuntu 和 mac 的 run time stack 的生长方向好像不一样, 先创建的 variable 在 mac 上是在高地址, 但是在 ubuntu 上是低地址:
ubuntu:
#+begin_src bash
(gdb) print &s
$1 = (cs225::Sphere **) 0x7fffffffddc8
(gdb) print &r
$2 = (double *) 0x7fffffffddd0
(gdb) print &v
$3 = (double *) 0x7fffffffddd8
(gdb) step
#+end_src
mac:
#+begin_src zash
&s (main): 0x16d7d2d18
 s (main): 0x16d7d2cb8
&r (main): 0x16d7d2d10
 r (main): 4.17291e-314
&v (main): 0x16d7d2d08
 v (main): 0
#+end_src

还有一个例子:

#+begin_src cpp
#include <iostream>

using namespace std;

int main() {

  int first = 42;
  int arr[6];

  cout << &first << endl;
  cout << &(arr[0]) << endl;
  cout << &(arr[1]) << endl;
  cout << &(arr[2]) << endl;

  return 0;
}
#+end_src

编译之后在 ubuntu 上面跑
#+begin_src bash
(base) zhb:~/Desktop/code-lecture02$ g++ stack-array.cpp
(base) zhb:~/Desktop/code-lecture02$ ./a.out
0x7ffc30b2507c
0x7ffc30b25080
0x7ffc30b25084
0x7ffc30b25088
(base) zhb:~/Desktop/code-lecture02$
#+end_src

编译之后在 mac 上面跑
#+begin_src bash
~/Desktop/cs225/lecture/lecture02/code-lecture02 $ g++ stack-array.cpp
~/Desktop/cs225/lecture/lecture02/code-lecture02 $ ./a.out
0x16fa6acf8
0x16fa6ad00
0x16fa6ad04
0x16fa6ad08
~/Desktop/cs225/lecture/lecture02/code-lecture02 $
#+end_src

这下两个一样了, 但是我发现这个顺序好像并不是我们在 lc3 里面学到的那样先 declare 的先 push, 我们再写个东西 check 一下

#+begin_src cpp
#include <iostream>

void f(int i) {
	int a = i;
	std::cout << "a: " << a << " Address of a: " << &a << std::endl;
	if (i > 0) {
		f(i - 1);
	}
}


int main(void) {
	f(3);
	return 0;
}
#+end_src

macbook
#+begin_src bash
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % g++ stack_growth.cpp
zhb ~/Desktop/cs225/lecture/lecture02/code-lecture02 % ./a.out
a: 3 Address of a: 0x16bd82d18
a: 2 Address of a: 0x16bd82cf8
a: 1 Address of a: 0x16bd82cd8
a: 0 Address of a: 0x16bd82cb8
#+end_src

ubuntu
#+begin_src bash
(base) zhb:~/Desktop$ g++ stack_growth.cpp
(base) zhb:~/Desktop$ ./a.out
a: 3 Address of a: 0x7ffe11687384
a: 2 Address of a: 0x7ffe11687354
a: 1 Address of a: 0x7ffe11687324
a: 0 Address of a: 0x7ffe116872f4
(base) zhb:~/Desktop$
#+end_src

run time stack 确实是从高地址往低地址增长的

总的来说, 就是这个 run time stack 确实是一般从高地址向低地址增长, 但是一个函数内部, 变量声明的先后和这个 stack 上变量的位置没有必然的关系

总之, 我们获得了两个确定的结论:
1. run time stack 总的方向上, 是从高地址向低地址增长的
2. 一个 array 内部, &(array[0]) < &(array[1]) < ...., 而且大概率紧密排列

其他都不是确定的, 没有一个固定的标准, run time stack 内部的 behavior 完全是编译器爱咋干就咋干


* lecture 03

我只能说这节课体验极差, 老师什么都没有讲清楚, 讲的就是一坨狗屎, 但是老师看上去自己确乎是懂的, 只是不想讲清楚, 不像某些 220 老师, 看上去自己都不懂, 下面整理清楚

** 1. 重识 reference
*** (1) reference semantics
reference: an alias of an existing object

之前一直使用的是 const pointer 的角度去理解这个 reference, 这样是有问题的, reference 实际上真的就是一个 alias, 是在编译器处理阶段就解决的, 并不是分配了一个 const pointer 类型的 variable, 或者说, reference variable 根本就不是一个 variable, 并没有真的在 stack 或者 heap 上面分配内存给这个 reference variable, 这个似乎是有点像 macro, 就是在编译的时候就直接结束了, 他就真的只是这个变量的一个 alias

一个 reference 的基本要求是:
- Must be initialized when declared.
- Cannot be reassigned to refer to a different object.
- No null references.

如果在被创建的时候没有被初始化, 会直接编译错误, 而不是 Undefined Behavior

这个是验证代码
#+begin_src cpp
#include <iostream>

int main() {
    int * x = new int;
    int & y = *x;

    y = 4;

    std::cout << "&x, on stack: " << &x << std::endl;
    std::cout << "x, on heap: " << x << std::endl;
    std::cout << "*x, value: " << *x << std::endl;

    std::cout << "y " << y << std::endl;
    std::cout << "&y: " << &y << std::endl;
    // std::cout << "*y" << *y << std::endl; // invalid

    return 0;
}
#+end_src

然后我们运行一下:
#+begin_src bash
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ reference.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./a.out
&x, on stack: 0x16b576d30
x, on heap: 0x600000c9c030
*x, value: 4
y 4
&y: 0x600000c9c030
#+end_src

在 programmer 的层面, reference 实际上就是对象的 alias, 也就是说, coding 的时候我们代指的就是那个真实的对象, 我们并没有在任何一个地方去分配一个实际的地址给这个 reference variable, 他实际上就是一个对象的 memory 的 alias, 但是在编译器的行为上, 传参数的时候, 你使用 reference 传参等价于传递一个指针, 或者说几乎等价, 老师上课说的 "pass parameter by reference" 没有 copy 是错的, 或者至少说, 在语意上是不严谨的, 你要访问这个 object, 你是一定要知道他的物理地址的, 不然没法访问, 他说的 "没有 copy " 是在人类语意上的说法, 但是在衡量这个开销的时候, 肯定是从调用函数的时候底层的表现来讲的, 在调用的时候肯定是往 stack 里面压入一个地址的, 不可能什么东西都不传递

虽然在硬件的 ABI 上面, pointer 和 reference 似乎没什么区别 ( 简化的来看, reference 就是一个 const pointer ), 但是在语意上, 两者还是有区别的, 比如说, 你传递一个参数为 pointer, 这个可以是 NULL, 或者说用 cpp 的办法是 nullptr, 并没有保证说是这个东西一定指向一个 object, 但是如果是一个 reference 的话, 这个东西在语意上是一个 object, 或者说是一块 memory 的 alias, 所以他是有保证的

*** (2) reference 用于传参
接下来讲一下传参数的三种办法, pass by value, pass by pointer, pass by reference, 顺便复习一下 const 的用法

#+begin_src cpp
// pass by object
void function(const class_name object);
void function(class_name const object);

// pass by pointer
void function(const class_name *object);
void function(class_name const *object);

// pass by reference
void function(const class_name &object);
void function(class_name const &object);
#+end_src

复习一下, const 修饰的是他左边的东西, 就是他左边的东西是不可以改变的, 比如说 int const *x;, 这里 int 是不可改变的, 也就是说, 指针 x 可以指向不同的 int, 但是x不能修改他指向的东西的值
如果写成了 int * const x;, 这种写法表示 int * 是不可改变的, 也就是说指针不能重新指向别的 int, 但是指针可以修改这个指向的 int 的值

void function(const Class object), 这个写法等价于 void function ( Class const object ), ( const 修饰左边的东西，如果没有的话就修饰右边最近的东西), 这里反正都是表示传入的是一个 const object, 但是实际上因为传入的是 object, 反正是 copy 的, 你反正没有办法改变原来的值, 所以 const 关键字加不加意义不大

void function(const Class * pointer), 这个写法也等价于 void function (Class const * pointer), 这个表示的是, pointer 指向的是一个 const object, 也就是说你不能通过这个 pointer 去修改这个pointer 指向的 object, 但是你的 pointer 可以指向不同的 const object

void function(const Class & reference), 等价于 void function(Class const & reference), 这个 const 表示这个 reference alias 指向的那个 object 是不可以改变的, 但是因为你的 reference 在初始化之后就不能重新绑定了, 所以实际上你的 reference 也不能当另一个 object 的 alias

所以我们一般在传递参数的时候, 因为 reference 不可重新绑定的特性, 以及 const 关键字修饰表示这个 reference 绑定的 object 不能被改变, 所以说 void function(const class_name &object); 的传参方式是最安全的

*** (3) tricky example

因为 pass by reference + const 的安全特性, 他对调用 const reference 的函数也做出了要求, 他要求这个函数不会改变 const reference 这个 object 而这个很容易被忘记, 一个比较 tricky 的 example 如下:

sphere.cpp
#+begin_src cpp
#include "sphere.h"
#include <math.h>

Sphere::Sphere(double r) : r_(r) {
    ;
}

double Sphere::getVolume() {
    return (4.0 / 3.0 * 3.141592654 * pow(r_, 3));
}

Sphere joinSpheres(const Sphere s1, const Sphere s2) {
    double totalVolume = s1.getVolume() + s2.getVolume();
    double newRadius = pow(
        (3.0 * totalVolume) / (4.0 * 3.141592654),
        1.0/3.0);
    Sphere result(newRadius);
    return result;
}
#+end_src

main.cpp
#+begin_src cpp
#include "sphere.h"

int main() {
    Sphere *s1 = new Sphere(4);
    Sphere *s2 = new Sphere(5);
    Sphere s3 = joinSpheres(*s1, *s2);
    delete s1; s1 = nullptr;
    delete s2; s2 = nullptr;
    return 0;
}

#+end_src

直接编译会有编译错误:
#+begin_src bash
zhb ~/Desktop % g++ -std=c++11 -c -g sphere.cpp
sphere.cpp:13:26: error: 'this' argument to member function 'getVolume' has type 'const Sphere', but function is not marked const
   13 |     double totalVolume = s1.getVolume() + s2.getVolume();
      |                          ^~
sphere.cpp:8:16: note: 'getVolume' declared here
    8 | double Sphere::getVolume() {
      |                ^
sphere.cpp:13:43: error: 'this' argument to member function 'getVolume' has type 'const Sphere', but function is not marked const
   13 |     double totalVolume = s1.getVolume() + s2.getVolume();
      |                                           ^~
sphere.cpp:8:16: note: 'getVolume' declared here
    8 | double Sphere::getVolume() {
      |                ^
2 errors generated.
#+end_src

这个是因为, 在函数 joinSpheres 里面, 我们传递的参数是 const reference, 也就是说, 我们要求不修改传入的 object, 但是在 class Sphere 的 member function getVolume 里面, 我们并没有给 getVolume 加上 const 关键字 ( 保证 *this 里面的任何一个 attribute 都不变 ), 但是在 joinSpheres 里面我们调用了 s1.getVolume() 和 s2.getVolume(), 所以编译器报错了

加上 const 关键字修饰 getVolume 以后就可以正常编译了:

sphere.cpp
#+begin_src cpp
#include "sphere.h"
#include <math.h>

Sphere::Sphere(double r) : r_(r) {
    ;
}

double Sphere::getVolume() const {
    return (4.0 / 3.0 * 3.141592654 * pow(r_, 3));
}

Sphere joinSpheres(const Sphere s1, const Sphere s2) {
    double totalVolume = s1.getVolume() + s2.getVolume();
    double newRadius = pow(
        (3.0 * totalVolume) / (4.0 * 3.141592654),
        1.0/3.0);
    Sphere result(newRadius);
    return result;
}
#+end_src

#+begin_src bash
zhb ~/Desktop % g++ -std=c++11 -c -g sphere.cpp
zhb ~/Desktop % g++ -std=c++11 -c -g main.cpp
zhb ~/Desktop % g++ main.o sphere.o -o executable
#+end_src


** 2. 重识 constructor

*** (1) default constructor 复习
这个东西老师是真的没有讲清楚, 我受不了了, 他为什么不讲清楚, 他妈的知道不知道自己去查这个东西, 自己跟 gpt 交互去学这个是很累的? 他两句话就能讲清楚, 做一个表格也就十分钟的事情, 却浪费我半个多小时去打字向 gpt 提问, 我真的是受不了了, 为什么要有意或者无意的提高知识获取的难度, 打字打多了手都酸了, 受不了一点

算了, 不管了, 先说清楚以下的东西:
1. default constructor: 定义是, 如果我们有 class class_name, object of class_name 的 default constructor 是一个不接受任何参数的 constructor for class_name, 评判一个 constructor 是不是 default 的唯一标准是接受不接受参数
2. implicitly-declared default constructor: 对 class_name 这个 class, 你没有写任何一个 constructor, 然后编译器会自动帮你生成一个 constructor, 这个 constructor 不接受任何参数, 所以是一个 default constructor, 你一旦写了任何一个 constructor, 那编译器就不会给你生成这个 implicitly-declared default constructor
3. user-provided default constructor: 你自己写的 default constructor

好了, 关于 default constructor 的定义就这么多, 接下来举例子看表现 ( 注意, cpp 里面, class 的东西没写 public 的话默认是 private 的, struct 里的东西没写 private 的话, 默认是 public 的 )

#+begin_src cpp
#include <iostream>

class B {
    public:
    int b;
    double c;
};

class A {
    public:
    int x;
    std::vector<int> v;
    B b;
};

class C {
    public:
    int x;
    std::vector<int> v;
    B b;

    C() {
        std::cout << "class C default constructor, fuck you cpp" << std::endl;
    }
};

class D {
    public:
    int x;
    std::vector<int> v;
    B b;

    D(int r) : x(r){
        std::cout << "class D custom constructor, fuck you cpp" << std::endl;
    }
};

int main() {
    // test behavior of class A, implicitly-declared default constructor
    A obj_a;
    A obj_a_ = A();

    // test behavior of class C, custom default constructor
    C obj_c;
    C obj_c_ = C();

    // test behavior of class D, no implicitly-declared default constructor
    D obj_d; // compile error
    D obj_d_ = D();
}
#+end_src

编译错误如下:
#+begin_src cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ default-constructor.cpp
default-constructor.cpp:48:7: error: no matching constructor for initialization of
      'D'
   48 |     D obj_d; // compile error
      |       ^
default-constructor.cpp:33:5: note: candidate constructor not viable: requires
      single argument 'r', but no arguments were provided
   33 |     D(int r) : x(r){
      |     ^ ~~~~~
default-constructor.cpp:27:7: note: candidate constructor (the implicit copy
      constructor) not viable: requires 1 argument, but 0 were provided
   27 | class D {
      |       ^
default-constructor.cpp:27:7: note: candidate constructor (the implicit move
      constructor) not viable: requires 1 argument, but 0 were provided
   27 | class D {
      |       ^
default-constructor.cpp:49:16: error: no matching constructor for initialization
      of 'D'
   49 |     D obj_d_ = D();
      |                ^
default-constructor.cpp:33:5: note: candidate constructor not viable: requires
      single argument 'r', but no arguments were provided
   33 |     D(int r) : x(r){
      |     ^ ~~~~~
default-constructor.cpp:27:7: note: candidate constructor (the implicit copy
      constructor) not viable: requires 1 argument, but 0 were provided
   27 | class D {
      |       ^
default-constructor.cpp:27:7: note: candidate constructor (the implicit move
      constructor) not viable: requires 1 argument, but 0 were provided
   27 | class D {
      |       ^
2 errors generated.
#+end_src

修正错误 (把有关 D 的东西直接注释掉) 之后, 运行结果

#+begin_src bash
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ default-constructor.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./a.out
class C default constructor, fuck you cpp
class C default constructor, fuck you cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $
#+end_src

可见我们对这个东西的理解是对的, 对于 class C 来说, 这里直接调用的是 custom 的 default constructor

*** (2) copy constructor

copy constructor 的判定是 "函数签名层面的", 不是 "你在函数里做了什么", 对 class A 来说, copy constructor 是一个构造函数, 满足
(1) 构造函数名是 A
(2) 第一个参数是 const A & 类型或等价形式
(3) 其余参数 (如果有) 都有默认值 ( 但是我们一般不考虑其他参数 )

copy constructor 是在使用一个已经有的 object 对另一个新的 object 进行初始化的时候调用的, 而不是对一个已经有的 object assign value 的时候调用的 ( 这个是 operator= )

Automatic Copy Constructor 对 pointer 只是进行了 shallow copy, 所以如果你需要 copy 这个 pointer 指向的地址的内容的话, 你需要自己写 custom copy constructor

对于不止一个参数的 copy constructor, 我们澄清一下:
#+begin_src cpp
A(const A &other, int x = 0); // copy constructor
A(const A &other, int x);
#+end_src

第一个参数永远是 "被拷贝对象", 剩下的参数是可选的且必须有默认值, 保证无参调用时也可以调用这个函数 (因为在大多数情况下 copy constructor 会在只给一个对象的时候被调用), 如果你写了一个额外参数但不给默认值, 编译器就不再认它是 copy constructor

典型形式:
#+begin_src cpp
// copy constructor
A(const A& other);
A(A const& other);

// 不是 copy constructor, 即使你真的在做 copy 这个任务
A(const A other);
#+end_src

不使用 A(const A other) 这个形式的原因是, 这里的参数是使用 value 传递的, 你要得到这个 value, 就要调用 copy constructor, 但是你的 copy constructor 又是值传递的, 这样会无限递归

再次强调, copy constructor 在 "初始化新对象" 时被调用, 而不是在 assign value 的时候被调用

#+begin_src cpp
ClassName a;
ClassName b = a;   // 不是赋值是初始化, copy constructor, 等价于 A b(a);
b = a;  // 这个是赋值, 等价于 b.operator=(a);
#+end_src

写个小程序验证一下
#+begin_src cpp
#include <iostream>

class aClass {
    public:
        int a;
        double b;
        aClass() {
            ;
        }

        aClass(const aClass & another) : a(another.a), b(another.b) {
            std::cout << "custom copy constructor called" << std::endl;
        }

        aClass operator=(const aClass & another) {
            this->a = another.a;
            this->b = another.b;
            std::cout << "operator = is called" << std::endl;
            return another;
        }
};

int main() {
    aClass a;
    aClass b = a;
    b = a;
    return 0;
}
#+end_src

编译运行, 得到
#+begin_src bash
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ copy-constructor.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./a.out
custom copy constructor called
operator = is called
custom copy constructor called
#+end_src

这里有三次 copy constructor 被调用, 第三次是在 operator= 的返回的时候, 因为我们返回的类型不是 reference, 是一个 aClass 的 object, 所以这里调用了一次 copy operator, 你可以通过改写这个 operator& 的返回类型, 变成 const reference 返回, 这样就不会有多余拷贝 ( 也是标准的 reference 版的预防成为 lvalue 的 operator= 的写法 )

#+begin_src cpp
#include <iostream>

class aClass {
    public:
        int a;
        double b;
        aClass() {
            ;
        }

        aClass(const aClass & another) : a(another.a), b(another.b) {
            std::cout << "custom copy constructor called" << std::endl;
        }

        aClass const & operator=(const aClass & another) {
            this->a = another.a;
            this->b = another.b;
            std::cout << "operator = is called" << std::endl;
            return another;
        }
};

int main() {
    aClass a;
    aClass b = a;
    b = a;
    return 0;
}
#+end_src

编译运行结果
#+begin_src bash
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./a.out
custom copy constructor called
operator = is called
#+end_src

当然, 写成
#+begin_src cpp
aClass & operator=(const aClass & another) {
    this->a = another.a;
    this->b = another.b;
    using namespace std;::cout << "operator = is called" << std::endl;
    return *this;
}
#+end_src

也是可以的, 这个写法非常有趣, 事实上这个就是 STL 的标准的 operator= 的写法, 返回的是 reference, 绑定的是 operator= 的 lvalue, 这个允许了 (a=b) = c 这种写法

关于 implicitly-declared copy constructor, 这个东西是 element-wise member copy, 就是说, 如果你的 class 有一个 attribute 是 type * ptr;, 那么他只是复制一遍 ptr 这个地址, 不会把 ptr 指向的 object 再复制一遍, 如果你已经写了一个 copy constructor, 那这样编译器就不会自动给你生成 implicitly-declared copy constructor, 这样就会报错

当然, 你可以使用 defaulted copy constructor, 就是像下面这样

#+begin_src cpp
struct A {
    A(const A&) = default;
};
#+end_src

这个意思是, 你 explicitly 要求要一个 copy constructor, 但是要求他表现的跟 implicitly-declared constructor 一样

*** (3) puzzle example

我们下面分析一下一个 sphere 的例子, 讲一下理论上应该怎么 behave, 实际上应该怎么样

#+begin_src cpp
#include "sphere.h"
#include <iostream>

using namespace std;

namespace cs225 {

  Sphere::Sphere() : Sphere(1.0) {
    cout << "Default ctor" << endl;
  }

  Sphere::Sphere(double r) {
    cout << "1-param ctor" << endl;
    r_ = r;
  }

  Sphere::Sphere(const Sphere &s) {
    cout << "copy ctor" << endl;
    r_ = s.r_;
  }


  double Sphere::getRadius() const {
    return r_;
  }

  void Sphere::setRadius(double r) {
    r_ = r;
  }

  double Sphere::getVolume() const {
    return (4 * r_ * r_ * r_ * 3.14159265) / 3.0;
  }

}
#+end_src

这里面的 constructor 讲明白了你在调用哪个, 然后我们实现一下 copy by value 的 函数

**** a. pass by value

#+begin_src cpp
#include "sphere.h"
#include <math.h>

using namespace cs225;

Sphere joinSpheres(Sphere s1, Sphere s2) {

  double totalVolume = s1.getVolume() + s2.getVolume();

  double newRadius = pow((3.0 * totalVolume) / (4.0 * 3.141592654), 1.0/3.0);

  Sphere result(newRadius);

  return result;
}


int main() {

  Sphere *s1 = new Sphere(4);
  Sphere *s2 = new Sphere(5);

  Sphere s3 = joinSpheres(*s1, *s2);

  return 0;
}
#+end_src

理论上来说, 我们得到的应该是
1. Sphere *s1  = new Sphere(4) 是一个 one parameter constructor
2. Sphere *s2  = new Sphere(5) 是一个 one parameter constructor
3. 传参是传 value, joinSpheres(*s1, *s2) 里面 *s1 和 *s2 各一次 copy constructor
4. Sphere result(newRadius); 是一个 one parameter constructor
5. return 的时候从 result 这个 local variable 把参数复制到 joinSpheres stack 的 return value 的值, 调用一次 copy constructor
6. Sphere s3 = joinSpheres(*s1, *s2);, return 的值赋给 s3, 再调用一次 copy constructor

跑一下验证一下:
#+begin_src cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ -c -o0 sphere.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ -c -o0 joinSpheres-byValue.cpp
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ g++ sphere.o joinSpheres-byValue.o -o byVaule
~/Desktop/cs225/lecture/lecture03/code-lecture03 $ ./byVaule
1-param ctor
1-param ctor
copy ctor
copy ctor
1-param ctor
~/Desktop/cs225/lecture/lecture03/code-lecture03 $
#+end_src

实际上我们猜测的后面两个 copy constructor 都没有被调用

这个是因为, 在现代 cpp 中有 NRVO (Named Return Value Optimization) 优化, 这个优化的语意是这种情形的 result 直接构造在调用方的返回对象存储位置上, c++11 起, 允许后面两个 copy 不发生, c++17 起, 直接强制规定这两个 copy 不发生, 所以我们这里的 joinSpheres 里面的 result 那个对象是直接建立在 s3 上面的, 我们 gdb 进去看一看

#+begin_src bash
(base) zhb:~/Desktop$ g++ -c -g sphere.cpp
(base) zhb:~/Desktop$ g++ -c -g byValue.cpp
(base) zhb:~/Desktop$ g++ sphere.o byValue.o -o byValue
(base) zhb:~/Desktop$ gdb ./byValue
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./byValue...
(gdb) b main
Breakpoint 1 at 0x1439: file byValue.cpp, line 21.
(gdb) run
Starting program: /home/zhb/Desktop/byValue

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at byValue.cpp:21
21	int main() {
(gdb) info locals
s1 = 0x12000
s2 = 0x2e78786362696c67
s3 = {r_ = 6.9533558074168272e-310}
(gdb) p &(s3)
$1 = (cs225::Sphere *) 0x7fffffffdec0
(gdb) p &(s3.r_)
$2 = (double *) 0x7fffffffdec0
(gdb) n
23	  Sphere *s1 = new Sphere(4);
(gdb) n
1-param ctor
24	  Sphere *s2 = new Sphere(5);
(gdb) n
1-param ctor
26	  Sphere s3 = joinSpheres(*s1, *s2);
(gdb) b cs225::Sphere::Sphere(double)
Breakpoint 2 at 0x555555555275: file sphere.cpp, line 13.
(gdb) continue
Continuing.
copy ctor
copy ctor

Breakpoint 2, cs225::Sphere::Sphere (this=0x7fffffffdec0, r=5.7387935458815473) at sphere.cpp:13
13	    cout << "1-param ctor" << endl;
(gdb) p this
$3 = (cs225::Sphere * const) 0x7fffffffdec0
(gdb) exit
A debugging session is active.

	Inferior 1 [process 46315] will be killed.

Quit anyway? (y or n) y
(base) zhb:~/Desktop$
#+end_src

你会发现这个 this 指针就是 s3 的地址, 只能说老师对于这个东西的理解还是很久之前的, 现代 cpp 已经不这么做了

**** b. pass by const value

不想写了, 自己跑一下 lecture/lectore03/code-lecture03 里面的 demo 吧, 我感觉上面的已经分析的很清楚了, ppt 里面也有, 相信如果上面 pass by value 的例子看懂之后你一定是会的


* lecture 04

这节课的核心是 resource management, 主要是一些概念上的介绍, coding 和 hardware 层面的东西比较少

或者说, 我前面 lecture 01/02/03 还有知识铺垫做的比较全面导致这里似乎没有那么多具体知识点可以讲 🤪

the rule of three 实际上可以扩展到 the rule of five ( 算上 movement constructor 还有 movement assign operator, 为 cpp11 往后的语言特性设计的 ), 这个以后碰到了再说

这里要开始着重体会 cpp 里面的设计哲学 RAII (resource acquaintance is initialization)

还有说一下, in cpp, never copy code, 要抽象逻辑然后复用, copy code 的时候你大概率是做错了 ( 比如对于 copy constructor 和 operator=, 里面都涉及从一个 object 创建/修改另一个 object, 可以把这个逻辑抽象为 copy_ 作为一个 private 函数, 然后在 copy constructor 和 operator= 里面调用这个 private member function copy_ )

** 1. destructor

the last function being called for an existing instance before it appears, the purpose is to cleanup this resource

当一个 object 被创建的时候, constructor 被 called, 当一个 object 被 destroyed 的时候, 有一些东西也要被 called, 这个东西就是 destructor, 注意 destructor 没有 manually called 的情况, 他就是 automatically called, like your object is deleted from the heap, or gets out of scope on the stack, 你永远不应该 manually call destructor

至于一个 object 什么时候被 destroyed? 当一个 object 的生命周期结束了, 他就会被 destroyed

default destructor is provided, and it has no parameters, 语法是跟 classname 同名, 但是多一个 ~, 没有任何参数

#+begin_src cpp
class Sphere {
    public:
        Sphere(); // default constructor
        ~Sphere(); // destructor
}
#+end_src

default destructor 又叫 Implicitly-defined Destructor, 它的函数体是空的 {}, 他的行为是会自动且递归地调用类中所有成员变量的析构函数以及基类的析构函数, 对于基本类型 ( int, double, ..) 的指针, 他并不会 delete [] 指针指向的东西, 这个就很灾难了, memory leakage, surprise!!!

编译器认为指针只是一个数值 ( address ), 它不知道这个地址背后是一块需要手动释放的资源, 这就是为什么你必须自定义析构函数并调用 delete

** 2. operator
*** (1) 基本的 operator overload

cpp 里面可以 overload 很多 operator, 语法设计和逻辑在 cpp 入门特性/operator 那里讲过了, 不再重提, 这里列举一下可以被 overload 的 operator

arithmetics: + - * / % ++ --
bitwise: & | ^ ~ << >>
assignment: =
comparison: == != > < >= <=
logic: ! && ||
other: [] () ->

这节课的重点是在说 resource management, 所以我们着重重新讲一下 assignment operator

*** (2) operator=

如果我不写 operator=, 只要你的类里没有一些极端情况 ( 比如包含 const 成员或引用成员, 这些不可更改), 编译器会自动生成一个默认的赋值运算符

自动实现的函数签名是:

#+begin_src cpp
T& T::operator=(const T& other) {
    // assignment logic
    return *this; // 默认的 behavior 是返回 operator= 的 lvalue 的 reference
}
#+end_src

这个 implicitly-defined copy assignment operator 的行为是执行 member-wise assignment, 也就是说它对类中的每个成员调用其对应的 operator=

对于内置类型 (int, 指针), 它执行的是 shallow copy, 这个很容易造成混乱

我们自己写 assignment operaotr 的时候, 要遵循上面的函数签名的写法, 里面实现的逻辑可以改, 但是函数签名一定要是这个

下面讲一下为什么会选择使用上面描述的函数签名

最主要的原因是, 在 cpp 里面 built in class 的 assignment 返回的都是 reference to the object itself, 我们需要 matching 这个操作

cpp 里面, a = b 返回的是 a reference to object a, 也就是 a reference to the lvalue of the operator =, 这个是一个 convention, 尽管你可以随便定义

下面讲解一下逻辑:

首先确定一下, 我们要么 return object, 要么 return reference, 不会 return pointer 的, 因为 return pointer 的话类型对不上, 很不合理
其次, 我们如果只是希望 return value 做 rvalue 的话 ( 也就是说, 你只会写 a = (b = c); 不会写 (a = b) = c; ), 那 return object 和 return reference 都可以, return object 会多一次创建对象 ( 因为有  NRVO, 即 Named Return Value Optimization 的存在, 所以不会 copy construct 好多次, 但是 construct 一次是不可避免的 ), 所以不如直接 return const reference
但是如果我们希望 return value 也能做 lvalue 的话 ( 也就是说你希望 a = (b = c) 和 (a = b) = c 都是合法的 ), 那 return object 是不行的, 我们只能 return reference 了, return 的一般是 *this, 也就是说 operator= 的 lvalue 这个 object, 因为一般我们 operator= 的 rvalue 是不希望被改变的, 所以我们一般传参传的是 const class_name & another, 我们希望 return value 做 lvalue 的话返回这个肯定是不行的 ( 还有就是这个 parameter 是 const reference, 不是 reference, 编译的时候实际会报错 )

** 3. the rule of three
*** (1) The rule of three
看上面的 implicitly-declared operator=/destructor 的表现 ( shallow copy 还有把内置类型的指针当作一般数值而不 delete ), 我们知道的是, 一旦我们 new 了东西我们就不能相信这个默认的 destructor/operator=, 我们要自己处理, 实际上这个情景要求我们同时自己实现 copy constructor, operator=, destructor, 或者说, 一旦我们需要实现这三者的任何一个, 我们基本就要把这三者都实现, 这个就是 the rule of three

the rule of three 的具体含义:

#+begin_quote
如果你发现你的类需要手动实现以下任意一个函数, 那么你极大概率需要同时实现剩下两个:
- Destructor: 释放资源
- Copy Constructor: 确保拷贝时资源也被正确处理
- Copy Assignment Operator: 确保赋值时旧资源释放，新资源拷贝
#+end_quote

这个是 RAII 的具体体现, 或者说是 cpp 下管理资源的具体体现

当然还有 the rule of five, 还有 the rule of zeor, the rule of three 是自己裸的手动管理资源的时候要做的, 当涉及智能指针了之后会有不一样的地方

*** (2) The Rule of Five:
#+begin_quote
If it is necessary to define any one of these three functions in a class, it will be necessary to define all five of these functions:
- Copy constructor
- Assignment operator
- The destructor
- Move constructor
- Move assignment operator
#+end_quote

对于 move constructor 还有 move assignment operator, 这里只做简要讲解:

Move Constructor (Steals resources from a temporary instead of copying), syntax: Sphere(const Sphere&& s);
Move Assignment (Releases current resources, then takes ownership from s), syntax: Sphere & operator=(const Sphere&& s);

**** move constructor & move assignment operator
下面是 gemini 的讲解, 我觉得很对, 就直接 copy 过来了:

move constructor 和 move assignment operator 不展开讲了, 以后碰到再说, 他解决的问题是 "原先资源的传递只能 copy 所有内容, 效率极低", Move的用途就在于不申请新内存不拷贝数据, 而是直接将源对象内部的指针 "偷" 过来并将源对象的指针置空 (nullptr), 这本质上是将昂贵的深拷贝降级为极其廉价的指针赋值

Move Constructor: 它的参数是一个 右值引用 (T&&), 右值引用告诉编译器 "这个源对象是一个临时的快要死掉的东西, 你可以随便蹂躏它的内部成员"
实现逻辑:
1. 接管资源: 将源对象的指针成员直接赋值给当前对象的指针
2. 切断联系(关键): 将源对象的指针设为 nullptr, 这一步至关重要, 否则源对象析构时会 delete 掉你刚刚“偷”过来的内存 ( 触发 RAII 保护机制 )
#+begin_src cpp
// 假设 Sphere 内部有一个 double* data_
Sphere(Sphere&& other) noexcept {
    this->data_ = other.data_;  // 指针拷贝
    other.data_ = nullptr;      // 令源对象失去所有权防止析构时释放内存
}
#+end_src

Move Assignment Operator: 签名通常是 Sphere& operator=(Sphere&& other) noexcept;
实现逻辑上, 移动赋值比移动构造多了一步，因为它必须处理当前已经持有的资源
1. 自赋值检查: 判断 this == &other
2. 释放旧资源: delete 掉当前对象原本持有的堆内存 ( 防止泄漏 )
3. 转移所有权: 同移动构造, 把 other 的指针拷贝过来
4. 源对象置空: other.data_ = nullptr
5. 返回 *this
#+begin_src cpp
Sphere& operator=(Sphere&& other) noexcept {
    if (this != &other) {
        delete data_;           // 1. 扔掉自己的旧货
        data_ = other.data_;    // 2. 偷别人的新货
        other.data_ = nullptr;  // 3. 让别人彻底放手
    }
    return *this;
}
#+end_src

为什么必须加 noexcept？

在嵌入式开发或高性能场景中这非常重要, 像 std::vector 这种容器在扩容 (reallocate) 时, 如果你的移动构造函数没有标记 noexcept, 它为了保证强异常安全性会退而求其次使用拷贝构造, 如果你忘了加 noexcept 你写的移动逻辑可能永远不会被调用, 导致性能大幅下降

*** (3) The Rule of Zero

从 the rule of five, 我们可以得到一个 collary, 即 "The Rule of Zero": 你的类应该尽量不手动编写任何一个上述五个函数, 因为容易出错

这怎么做到？ 利用 RAII 对象, 如果你的类成员全部是 "知道如何管理自己" 的对象 ( 比如 std::vector, std::string, std::unique_ptr ), 编译器生成的默认行为就完全正确

#+begin_quote
Classes that declare custom destructors, copy/move constructors or copy/move assignment operators should deal exclusively with ownership. Other classes should not declare custom destructors, copy/move constructors or copy/move assignment operators.

–Scott Meyers
#+end_quote



* Useful Tools

记录一下使用到的有用的工具

** gcc
1. g++/gcc filename 直接默认编译, 得到 a.out
2. link .o 的时候, 直接 g++/gcc xxx.o xxx.o -o executable 就好了, -l 是用于连接 library 的


** vim
1. : 进入命令模式, !xxxx 表示执行外部指令, 然后返回到 vim
2. :term 是在 vim 里面分屏, 然后在一个屏里面打开 terminal


** make & makefile
make -j 可以开多进程编译, 会快非常多
不要手动 rm -rf, 使用 make clean 指令, 同时善用 Makefile 去简化一下 shell 指令


** git
1. git branch
   git branch -a 可以看 all branch 名字, git branch -m/M branch-name: 重命名 / 强制重命名当前的 branch
   git branch branch-name 新建一个 branch name
2. git rm --cached filename
   把 staged 的东西放到工作区, 标记为 untracted


** svn
首先, svn 并不有用, 我只是因为要交作业不得不使用它才学的
1. svn commit
   傻逼玩意, 没有本地工作区和提交区的, 直接就 commit 到了 remote
2. svn update
   得到最新的 remote 的副本
3. svn revert file-name
   根据你的 svn, 把 file 变成上一次你 commit 的时候
4. svn diff
   类似 git diff


** linux cli command
*** dpkg
Debian PacKaGe
# 列出所有已安装的包
dpkg -l

# 查找特定包
dpkg -l | grep python

# 查看包的详细信息
dpkg -s libpng-dev

# 查看包安装的文件
dpkg -L libpng-dev

# 查看文件属于哪个包
dpkg -S /usr/include/png.h

# 安装本地.deb文件
sudo dpkg -i package.deb

# 安装并修复依赖
sudo dpkg -i package.deb
sudo apt-get install -f  # 修复依赖

# 卸载包（保留配置）
sudo dpkg -r package-name

# 完全卸载（包括配置）
sudo dpkg -P package-name

*** find
find [路径] [选项] [表达式]

# 在当前目录查找所有.cpp文件
find . -name "*.cpp"
# 在整个系统查找libpng.so（2>/dev/null隐藏错误）
find / -name "libpng.so" 2>/dev/null
# 不区分大小写查找
find . -iname "*.CPP"  # 会找到.cpp、.CPP、.Cpp等
# 只找目录
find . -type d -name "build*"
# 只找普通文件
find . -type f -name "*.o"
# 找符号链接
find . -type l
# 7天内修改过的文件
find . -mtime -7
# 30天前修改过的文件
find . -mtime +30
# 今天修改过的文件
find . -mtime 0
# 按访问时间找
find . -atime -1  # 24小时内访问过的

*** file
file + filename 可以查看文件相关信息

(base) zhb:/usr/lib/x86_64-linux-gnu$ file libc.so
libc.so: ASCII text
(base) zhb:/usr/lib/x86_64-linux-gnu$ file libc.so.6
libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=274eec488d230825a136fa9c4d85370fed7a0a5e, for GNU/Linux 3.2.0, stripped
(base) zhb:/usr/lib/x86_64-linux-gnu$
*** ldd
Library DepenDency

# 查看可执行文件的依赖
ldd /bin/ls

# 查看共享库的依赖
ldd /usr/lib/libpng.so

# 查看自己编译的程序
ldd ./myprogram
ldd /bin/ls
# 输出：
# linux-vdso.so.1 (0x00007ffd...)
# libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1
# libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
# /lib64/ld-linux-x86-64.so.2

# 解释：
# => 左边：程序需要的库名
# => 右边：系统找到的实际文件路径
# 没有 =>：特殊虚拟库
# not found：找不到的库（有问题！）

# 1. 检查缺失的库
ldd ./myapp | grep "not found"

# 2. 查看库的完整路径
ldconfig -p | grep libpng

# 3. 设置库路径
export LD_LIBRARY_PATH=/my/libs:$LD_LIBRARY_PATH
ldd ./myapp  # 再次检查

